### ISSUE TITLE
Sloeber's Auto Format Sometimes Makes a Mess of Things

### ISSUE THREAD

**Issue by gfvalvo** [Sloeber/arduino-eclipse-plugin#1000]
So, for the most part, Sloeber's auto format function does a pretty good job. But, for things like specifying a multi-dimensional array over multiple lines it produces pretty poor results.

For example, here's what the code looks like after formatting with Arduino IDE's.
```
uint8_t byteArray[][4] =
{ {0x12, 0x4D, 0x1F, 0xFF},
  {0x9B, 0xDE, 0xCA, 0xAC},
  {0xAA, 0xCC, 0x83, 0x22},
  {0x34, 0x71, 0x9F, 0xFF}
};
```

Beautiful and easy to read right? Here's Sloeber's opinion of what it should look like:
```
uint8_t byteArray[][4] = { { 0x12, 0x4D, 0x1F, 0xFF },
		{ 0x9B, 0xDE, 0xCA, 0xAC }, { 0xAA, 0xCC, 0x83, 0x22 }, { 0x34, 0x71,
				0x9F, 0xFF } };
```
It's a mess, and it only gets worse with bigger arrays.
Any way to fix this?

Thanks.

_**EDIT:**_
Never mind. I found "Never join already wrapped lines" under Preferences --> C/C++ --> Code Style --> Formatter --> Edit --> Lne Wrapping

Please close this issue.

**Comment by jantje** [comment]
Thanks for finding the solution yourself :-)

**Comment by wimjongman** [comment]
Yay! Issue #1000!
