### ISSUE TITLE
Sloeber 4.3 ESP8266 Issue -> 'make' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Tavi62** [Sloeber/arduino-eclipse-plugin#1012]
Hello,

I have a fresh copy of sloeber 4.3 and installed the esp8266 from the json file included in the release. If i try to verify an empty sketch i get the following error message. I tried to unzip 2 times the Sloeber but it did not make any difference. For esp32 it works.

error message|:

17:17:29 **** Incremental Build of configuration Release for project tete ****
"P:\\sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ..\sloeber.ino.cpp'
'Starting C++ compile'
make -C "P:\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip/src" install TOOLS_PATH="P:\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-"
'make' is not recognized as an internal or external command,
operable program or batch file.
subdir.mk:18: recipe for target 'sloeber.ino.cpp.o' failed
make: *** [sloeber.ino.cpp.o] Error 1

17:17:29 Build Failed. 2 errors, 0 warnings. (took 376ms)

**Comment by jantje** [comment]
Don't select the option to build from source.
If you do (on windows) you have to set the path to make in the environment variable sloeber_path_extension}

**Comment by Tavi62** [comment]
Hello,

Thank you very much for your fast feedback, unfortunately my technical skills are not high enough to be able to understand what you instructed me. could you please be more specific?

Thank you.

**Comment by Tavi62** [comment]
It worked. Thank you very much.

**Comment by NanneStephan** [comment]
and wat is the solution?  can't seem to find it

**Comment by Tavi62** [comment]
It was solved. As Jante replied....in the new release it was also fixed.

**Comment by NanneStephan** [comment]
Yes thx, I just found out what I did wrong. bin running in circle's and I could not find it.

**Comment by HobbyDev1** [comment]
I have the same problem with the fresh and newly installed sloeber (version berylium). But I don't see the way out. Can you please detail the necessary steps? Thanks a lot!

**Comment by lbeck37** [comment]
I've got the same problem (can't find make) on V4.3.3 from http://eclipse.baeyens.it/index.shtml a couple of weeks ago, I'm not sure what @jantje meant by not building from source. Isn't that how I build the system, from source? I've been looking for where I find "environment variable sloeber_path_extension" so I can add the path to make.
Thanks
