### ISSUE TITLE
Cannot run Arduino on new install of Eclipse

### ISSUE THREAD

**Issue by RA5040** [Sloeber/arduino-eclipse-plugin#1014]
Hi,
I have a new installation of Eclipse (latest build) and I am not seeing the Arduino controls on the toolbar; I do not have Arduino in Window/Preferences and I cannot change the perspective to Arduino because it is not there.  I am running Windows 10 and I have Eclipse cpp-photon2 installed on my F: drive (no spaces anywhere!!).  I have installed the Arduino AVR Boards platform (Help/Arduino Downloads Manager).

If I go to Help/Install New Software and search for the Arduino Eclipse plugin it only shows the Arduino plugin v4.3 if I have 'Hide items that are already installed' unchecked, so it thinks that the plugin is installed.

If I run Eclipse from the C: drive things are a tiny bit better because I now have the Arduino perspective showing (although it has a red square and <Arduino> is in brackets). But I still have no controls and no Arduino is Window/Preferences.

Is this a problem with the lastest release of Eclipse, or am I doing something stupid??

**Comment by RA5040** [comment]
Well, I've got it to work by some miracle.  I need to sleep on it and go through the installation again ... but honestly, it's a nightmare and there are no instructions that I can find that are of any help.  When I have this figured ... and some help here would be appreciated! ... I will do a write-up.

(This morning I installed an ESP32 Wrover Kit board with JTAG and got hardware debugging working both on the command line and in Eclipse ... it wasn't easy, but at least Espressif has some decent documentation).

**Comment by jantje** [comment]
have you read this? http://eclipse.baeyens.it/installAdvice.shtml

**Comment by RA5040** [comment]
Yes, of course I have.  What's needed are clear instructions. When everything is installed correctly it all works very well, but anything out of the ordinary and it's a nightmare.

I'm working my way through it and trying to figure out how I can get around the problem. But I can tell you that I've completely had to abandon a clean Eclipse installation to which I tried to add the plugin ... nothing I tried worked. At this point I don't know if it's because I had the installation on a different drive, if it has to do with the latest version of Eclipse, or V4.3 of Sloeber, or configuration changes in Eclipse, or a combination of all of these.  

I've gone through the install  several times again (as Administrator and installing on the root of the C: drive), without having made any prior changes to Eclipse, and it's 50% there: right now I can build but I can't download to a Nano: I get timeouts. I've tried another Nano, same thing. Both work on the Arduino IDE ... so something wrong with the Eclipse setup.

I'll have another go tomorrow but I would appreciate some real help rather 'Don't panic' notes! As you can probably tell I'm not enjoying this :) (but I am going through it carefully and systematically and I am writing down everything and also (you will be please to hear, I hope) writing up some documentation as I go along ... it may be of help to someone in the future.

**Comment by RA5040** [comment]
I've noticed that I have several versions of Eclipse CPP Photon on my system and the ini file all has this line in it:
--launcher.library
C:\Users\Robert\.p2\pool\plugins\org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.700.v20180518-1200
Could this be causing a problem?
I have had the error message that the Eclipse launcher was unable to locate it's shared companion library.

**Comment by jantje** [comment]
Normal install of the product is untar unzip run
In windows you need 7zip to do those actions
on mac you can not do that in the downloads folder
It is unclear how much more info one needs.

Eclipse comes with oomph. as you have pool stuff you are using oomph. My advice: "turn oomph off as good as you can" (There is no easy turn off switch). Oomph  breaks the OO rule data encapsulation which can cause lots of weird problems.

**Comment by RA5040** [comment]
I would like to install the plug-in, not the full package release. So it isn't just a question of unzipping.  Installing a plug-in is an option that you provide (and it worked for me in V4.2) so it isn't unreasonable that you should have some installation steps (it would not take you more than half an hour to do). OR ... if you give me the steps I will do the write-up for you.

I don't have a clue about what you mean about "turn off oomph as good as you can". I only know Eclipse from a user point of view (and only recently at that) so I need more than a comment like that to "turn off oomph".

BTW ... I have been doing software development all of my life (a long time!) so I do know about unzipping files! At least I know that much :)

**Comment by RA5040** [comment]
OK, for now I've downloaded the full package and installed it. It seems to work fine.

But I do still want to be able to install the plug-in to an existing Eclipse installation.

**Comment by jantje** [comment]
>But I do still want to be able to install the plug-in to an existing Eclipse installation.

We don't officially support the plugin because it is so easy to make mistakes. Missing plugins, wrong versions. That is why we made the product.
You can install the plugin. I tried it via the marketplace from a java product and from a cdt product and both worked. Your mileage may vary.
At least -after having played with the product- now you know what it should look like

**Comment by jantje** [comment]
>Also, what about upgrades? Again this means starting from scratch every time ... not very nice!

No that is not true
As I said; I installed the plugin using the eclipse marketplace on a java and cdt product without pain.
But the eclipse update/install procedure does have some flaws (it may be lack of recent documentation resulting in "bad update sites" or real bugs; I don't know) resulting in "sometimes painful situations needing a lot of expertise to fix (read; from time to time I fail to upgrade my own eclipse installs).

So supporting that is a nightmare; as such we do not support it.
Which does not mean "It doesn't work". Everything is there (including all the source code) and works (for instance nightly updates and release updates tested on all os'es)

**Comment by RA5040** [comment]
Yes, well that is the nightmare I had ... whatever I did I could not install the plugin correctly on one installation of Eclipse, but I was able to on another.  I understand that it's a nightmare to support ... but what makes Arduino so excellent is that everything works on it. So people going from the Arduino IDE to Eclipse Sloeber will expect something similar (OK, some pain is fair enough, but not a head-banging session that goes nowhere). It's a problem ... and I certainly don't have a solution, although one thing you could do is to set up a section on your website where you could post installation notes from users.  I would be happy to supply mine.

BTW: I have found a small little bug: the issue with the PSRAM Failed that I reported is that in the Board Specification you do not give the option to disable PSRAM for modules which don't have it (which is fair enough): but you should then set it to disabled by default. If you select the ESP32 Dev Module, for instance, you will find that there is an option to enable/disable PSRAM (since it has PSRAM), but in the ESP32 Wrover module there is no such option.

**Comment by jantje** [comment]
>So people going from the Arduino IDE to Eclipse Sloeber will expect something similar (OK, some pain is fair enough, but not a head-banging session that goes nowhere).

That is why we made the product. That one is simple and easy. I can't fix the eclipse update site mess.

>although one thing you could do is to set up a section on your website where you could post installation notes from users. I would be happy to supply mine.

The website is here on github. feel free to contribute. The master is pushed to sloeber.io every night.

>BTW: I have found a small little bug: the issue with the PSRAM

IMHO this is not a Sloeber bug. Boards.txt state this is a option for the board. Boards.txt does not specify defaults.
