### ISSUE TITLE
Install Latest Board Package

### ISSUE THREAD

**Issue by gfvalvo** [Sloeber/arduino-eclipse-plugin#1016]
Hi. So Arduino IDE found a new version of Adafruit's SAMD Board Package (v1.2.2). But Sloeber only sees up to v1.2.1 (see attached picture). How do I make Sloeber find the new version?

Thanks!

**EDIT:** Using Sloeber 4.3.

![platforms](https://user-images.githubusercontent.com/23526904/44628805-7a88e780-a915-11e8-8869-8492baf889ae.JPG)

**Comment by jantje** [comment]
Do you have the refresh option on in the third party index url's?

**Comment by gfvalvo** [comment]
Yes I do. But, I see now that maybe the refresh doesn't happen until I close and reopen the IDE. After that the v1.2.2 option appeared and I was able to install it.

Please close this issue.

Thanks.
