### ISSUE TITLE
Parameters of espota not correct when not in main cpp file

### ISSUE THREAD

**Issue by Bascy** [Sloeber/arduino-eclipse-plugin#1020]
I'm experimenting with OTA for our ESP32. I know the ESP32 is not supported but this issue is not specifically for the ESP32.

If I use a test script with every configuration code of the ArduinoOTA object then the call of espota is corerct, including the correct portnr and password.

```
// csMasterMain.cpp
void setup() {
  ArduinoOTA.setPort(8200);
  ArduinoOTA.setHostname("CSenseMaster");
  ArduinoOTA.setPassword("something");
}
```
>D:\sloeber4.3\/arduinoPlugin/packages/arduino-esp32/tools/espota.exe -i espressif.local -p 8200 --auth="something" -f D:\C-Sense2.0\source\csMainMaster/Debug/csMainMaster.bin 

If I move the code that set these configuration settings to a different source file, i.e. one containing a container object for the ArduinoOTA, then espota is called with the wrong (default) parameters.

```
//myOTA.cpp / myOTA.h

class MyOTA {
 public:
  void init() { 
      ArduinoOTA.setPort(8200);
      ArduinoOTA.setHostname("CSenseMaster");
      ArduinoOTA.setPassword("something");
  }
}

//csMasterMain.ccp
void setup() {
   myOTA.init();
}

```
> D:\sloeber4.3\/arduinoPlugin/packages/arduino-esp32/tools/espota.exe -i espressif.local -p 8266 --auth=no_pwd_found_in_code -f D:\C-Sense2.0\source\csMainMaster/Debug/csMainMaster.bin

Is there a way to specify the parameters of espota other then setting the ArduinoOTA configurations in the main source file?
I also would like to specify the host port (-P) as I need to use NAT to give the ESP32 access to my virtual development machine. How can I get that parameter added to the espota command line?

**Comment by jantje** [comment]
I do not understand what you are talking about.
First of there is a esp32 json file you can use. https://dl.espressif.com/dl/package_esp32_index.json

> If I move the code that set these configuration settings to a different source file, i.e. one containing a container object for the ArduinoOTA, then espota is called with the wrong (default) parameters.

I have no clue what you are talking about. Can you provide an example of where the wrong parameters are used and tell me what you think are the correct parameters?

**Comment by Bascy** [comment]
I added example code to the orignal post

**Comment by Bascy** [comment]
That's what I afraid of ... Its not exactly clear to me why you should read those settings from the setup code in the main sourcefile, as that severly limits development possibilities. It will also not work if you change the portnr in the code, as the operational script still has the old portnr ...

Can I override the settings used, or use other settings (like -P) by defining them somewhere else? Like boards.txt or an other settings file?

**Comment by jantje** [comment]
Just make a standard eclipse external launch configuration with the port an password you want
Don't forget to also configure the build tab.
![afbeelding](https://user-images.githubusercontent.com/1175841/45590164-e5d14280-b932-11e8-8663-78fbd3abbbfd.png)
![afbeelding](https://user-images.githubusercontent.com/1175841/45590174-faadd600-b932-11e8-86cb-2533e799e4d4.png)

Note that I have been where you are going and in the end I simply put the commands back in setup. I found that the disadvantages to moving this code in a class constructor or initializer did not outweigh the disadvantages.
