### ISSUE TITLE
Third party index url's - JSON name package.json not allowed

### ISSUE THREAD

**Issue by lecommander** [Sloeber/arduino-eclipse-plugin#1037]
I just tried to add this json file:
https://github.com/esp8266/Arduino/blob/master/package.json

I'm getting the error message: 
json files should start with "package_" or "library_" https://github.com/esp8266/Arduino/blob/master/package.json is ignored

How can I get that file included or would it be possible to to allow also "package.json" and "library.json"

**Comment by jantje** [comment]
Your url is wrong. it should be
https://raw.githubusercontent.com/esp8266/Arduino/master/package.json

**Comment by lecommander** [comment]
Thank you for the correction of the url.
Unfortunetely the issue remains - error log:

> json files should start with "package_" or "library_" https://raw.githubusercontent.com/esp8266/Arduino/master/package.json is ignored

I think this is caused because file name is not **package_**xyz.json - as the error log indicates.
