### ISSUE TITLE
Feature inclusions should always be installmode=root

### ISSUE THREAD

**Issue by wimjongman** [Sloeber/arduino-eclipse-plugin#1038]
https://github.com/Sloeber/arduino-eclipse-plugin/blob/5f42de7cb53d4158422efa865348ef2b66b99b46/io.sloeber.product/arduino.product#L350

People! When adding features to the product, please be aware that they should have installmode=root otherwise the product may not be able to update individual features.

Installmode=root tells tycho that the feature is NOT a child of the product but a individual updatable component.

The line above should therefore be fixed.

**Comment by jantje** [comment]
No clue what you are talking about but it looks as if you found a issue causing installation problems :-)
Thanks

**Comment by wimjongman** [comment]
Bam!
