### ISSUE TITLE
Default list of update sites

### ISSUE THREAD

**Issue by sk8nfool** [Sloeber/arduino-eclipse-plugin#1048]
I noticed that CDT is not selected in the list of available update sites - is there a reason for this? I also noticed that there are several un-named sites - what's with them?
 
![image](https://user-images.githubusercontent.com/12006794/49397580-01661100-f70a-11e8-9bd9-d557c4c29c6f.png)

**Comment by jantje** [comment]
I'm not sure what is going on with the update sites right now but it sure isn't funny.
At my place sites keep on disappearing and names are blanc.
The good news is that if you have the update sites it works :-s
CDT is no longer needed as it is now part of the eclipse stuff
Nebula might be needed
Sloeber nightly or stable ... you know

**Comment by sk8nfool** [comment]
CDT integrated into Eclipse. Interesting. Thanks.

**Comment by uzi18** [comment]
more like repository of cdt is available from eclipse main repository
