### ISSUE TITLE
Application name on macOS

### ISSUE THREAD

**Issue by Crazor** [Sloeber/arduino-eclipse-plugin#1049]
**Describe the bug**
The application name on macOS has cosmetic issues in two places. First, the app bundle is named "sloeber.app" instead of "Sloeber.app", which looks off in the Finder and in the Dock. This is easily fixable for me by renaming, but for consistency, this should be fixed in the build process eventually.

Second, and more important, the name of the main menu (the one in between the  and the File menu) is "Sloeber, the Eclipse Arduino IDE" instead of "Sloeber". This is really taking up unnecessary menu bar space and results in hidden status menus on lower-res monitors like the 13" MacBook Air. I need to switch out of Sloeber to an app with fewer menus before I can use 1Password, Dropbox etc.
Unfortunately, I didn't find a way yet to patch this on my end.

**Screenshots**
![menu](https://user-images.githubusercontent.com/128295/49634345-b47d8580-f9fc-11e8-9082-3c87b95fc657.png)
![bundle](https://user-images.githubusercontent.com/128295/49634346-b5161c00-f9fc-11e8-977b-582adc4f33a2.png)
![dock](https://user-images.githubusercontent.com/128295/49634348-b5161c00-f9fc-11e8-9997-2ebdcff5698c.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave (but all versions affected)
 - Sloeber Version 4.3.1

**Comment by jantje** [comment]
As to internationalisation I replaced "Sloeber, the Eclipse Arduino IDE" with"Sloeber"
I however fail to find why it is sloeber.app and not Sloeber.app

**Comment by wimjongman** [comment]
Closing. Please reopen if it is not solved.

**Comment by jantje** [comment]
Thanks @wimjongman :-)
