### ISSUE TITLE
HEX files overly large

### ISSUE THREAD

**Issue by polwel** [Sloeber/arduino-eclipse-plugin#1051]
The HEX files generated by Sloeber seem excessively large.

I built an empty sketch (just created a new project, clicked the 'Verify' button). I am using the latest version of Sloeber (4.3.1 I suppose?). The HEX file is about 10 kB. The latest Arduino IDE toolchain manages to fit it into less than 1.5 kB.

I was under the impression that Sloeber *does* run the actual Arduino toolchain, so I am confused.

I am running the stand-alone version of Sloeber, on Windows.

**Comment by jantje** [comment]
>I was under the impression that Sloeber does run the actual Arduino toolchain, so I am confused.

That is the intend. If you see a difference report as follows
Platform (inclusive version) used in Sloeber and Arduino IDE
Board used
code used
output of arduino ide (verbose build)
output sloeber console

**Comment by polwel** [comment]
Sorry for not getting back earlier. Naturally, it turned out I had selected different boards in Sloeber than in the Arduino IDE.

The issue can be closed. Sorry for the inconvenience.

**Comment by jantje** [comment]
Thanks for confirming thsi as a non issue
