### ISSUE TITLE
V4.3.1 unable to download library_jantje_index.json and package_jantje_index.json

### ISSUE THREAD

**Issue by aaszabo** [Sloeber/arduino-eclipse-plugin#1059]
**Describe the bug**
Installation cannot be finnished, because neither libraries nor packages can be downloaded in the 4.3.1 version of Sloeber extension of Eclipse.
Error message comes up at every startup, when it tries to finish the installation:

>Unable to download https://raw.githubusercontent.com/jantje/ArduinoLibraries/master/library_jantje_index.json
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty<

>Unable to download https://raw.githubusercontent.com/jantje/hardware/master/package_jantje_index.json
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty<

**To Reproduce**
Just start the application

**Expected behavior**
Download json files and update library and package references

**Screenshots**
![image](https://user-images.githubusercontent.com/18376017/50740864-cb7ae780-11f5-11e9-9338-ec7fc7ea86e1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Java: openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
Installed Sloeber version (V4.3.1_linux64.2018-10-10_08-21-58.tar.gz): 
![image](https://user-images.githubusercontent.com/18376017/50740890-35938c80-11f6-11e9-924a-5a467935b4dc.png)

**Additional context**
I downloaded the json files manually and put them into the arduinoPlugin folder of the Soleber Eclipse main folder. And then in the Arduino Preferences setting the list of Third party index URL's were extended the URL of the files. the But it doesn't fix the issue.
It seems that nothing can be updated.
![image](https://user-images.githubusercontent.com/18376017/50741143-8658b480-11f9-11e9-9163-80a815a3c014.png)

**Comment by jantje** [comment]
did you allow sloeber/java to access the internet?

**Comment by aaszabo** [comment]
It runs under my permissions. There is no restriction on anything to access the internet. Also Help/Eclipse marketplace connect to the server and provides a tons of modules for download.

Please try to reproduce it by creating the same environment as I described it in the registration entry of this issue.
I am about to enter into a project so I really need this solution.
Thanks in advance for any help.

**Comment by aaszabo** [comment]
Why was this closed? There is no solution. please tell me how to solve this.

**Comment by jantje** [comment]
Are you a patreon?

**Comment by wimjongman** [comment]
Because you seem to use Sloeber professionally and we do not provide support for local installation issues for free. 

So please be a chap and support us on Patreon 🤝. Then we will google the solution and send you the link.

**Comment by aaszabo** [comment]
I am a hobbyist here. My profession is something else. By the way I paid something via Paypal to Jantje, when the former version in Eclipse run well and it made me happy.
Find a solution via google is not what I am looking for. I thought you have the knowledge or will to solve this issue. Anyway thanks for your time.

**Comment by jantje** [comment]
The problem with paypall direct sponsoring (which is very rare) is that it is hard to find out who gave what. Though I'm not at all a fan of patreon's thought police it currently is the most viable option for me.
Any ways thanks for the support. I'm pretty sure there is a local issue (firewall stuff) or there was a temporary hickup on the network.
If the failing is persistent, a workaround is to download the zip and put it in the downloads folder.
