### ISSUE TITLE
Fresh install of Sloeber, having path issue with avr-g++ on mac

### ISSUE THREAD

**Issue by jamesatlasp** [Sloeber/arduino-eclipse-plugin#1062]
This may be a user error, but I cannot tell. A little help getting the IDE working will be appreciated!

When I try to build a project on the Mac, it bombs out as below. Note that this project builds on Windows. When I check out a new copy of the repo, it complains that platform.txt was deinstalled?

**Bug/ Compile Error Trace**
11:08:00 **** Build of configuration Release for project SBM_Master ****
make all 
Building file: ../sloeber.ino.cpp
Starting C++ compile
"/Applications/sloeber.app/Contents/Eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR     -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.6.23/cores/arduino" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.6.23/variants/mega" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/libraries/NTPClient/3.1.0" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/libraries/SD/1.2.3/src" -I"/Users/jamo2002/workspace/SBM_Master/Acquire_Data" -I"/Users/jamo2002/workspace/SBM_Master/Cmd_Tlm" -I"/Users/jamo2002/workspace/SBM_Master/Ethernet" -I"/Users/jamo2002/workspace/SBM_Master/ext_src/Arduino_FreeRTOS/src" -I"/Users/jamo2002/workspace/SBM_Master/ext_src/CFA533" -I"/Users/jamo2002/workspace/SBM_Master/ext_src/menuSystem" -I"/Users/jamo2002/workspace/SBM_Master/LCD_Menu" -I"/Users/jamo2002/workspace/SBM_Master/MemoryFree" -I"/Users/jamo2002/workspace/SBM_Master/sbm_config" -I"/Users/jamo2002/workspace/SBM_Master/State_Machine" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.6.23/libraries/SPI/src" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.6.23/libraries/EEPROM/src" -I"/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.6.23/libraries/Wire/src" -MMD -MP -MF"sloeber.ino.cpp.d" -MT"sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "../sloeber.ino.cpp"  -o  "sloeber.ino.cpp.o"
/bin/sh: /Applications/sloeber.app/Contents/Eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++: No such file or directory
make: *** [sloeber.ino.cpp.o] Error 127

 - OS: [Mac High Sierra]
 - Sloeber 4.3 stable

**Comment by jantje** [comment]
I guess you do not have arduino avr version 1.6.23 installed on your mac.
Check preferences->arduino->platforms

**Comment by jamesatlasp** [comment]
Thanks for your help @jantje! It didn't, well mostly didn't. It looks like sometimes you can install sloeber from scratch and the "finishing installation" steps that run after launching it the first time don't always complete. You don't get an error message, as best I can tell. The ....avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/ folder was empty. 

This was a fresh install, so I am 99.9% certain I didn't manage to mess up the plugins before making this ticket. 

Anyways, thank you for your assistance since you are the master of how the whole system integrates. We are back up and running.

**Comment by jantje** [comment]
I assume you have deinstalled and reinstalled the platform.
If things go wrong in this area there are actually 2 things that can go wrong
1) The downloaded file got corrupted (in this case you will need to delete the file manually from the downloads folder)
2) the compressed file extraction fails (in this case -if it is a tool zip- you have to delete tool folders to get them reinstalled)
In all cases you should get a error and a error should be logged in the errror log which can be viewed with the error viewer
