### ISSUE TITLE
Same code runs on ESP32 when compiled/uploaded in Arduino IDE but crashes under Sloeber               

### ISSUE THREAD

**Issue by JL1946** [Sloeber/arduino-eclipse-plugin#1067]
This issue MAY have been addressed before but I cannot find a solution for it.

I am including a link below to a sketch that compiles and runs on ESP32-WROOM Dev Board when the tasks are run in the Arduino IDE.

The same sketch compiles in Sloeber and is uploaded to the same board.

 **Expected behavior**
should run without consequence

**Failure Mode**
1. Sloeber compiled/uploaded Sketch causes constant reboots on Dev Board
2. Watchdog (WDT) times out

**Note**
I followed suggestions herein and moved all declarations, variables, includes, etc. to a header file which is included with the gist.

**Sketch and associated files can be found at:**
[https://gist.github.com/JL1946/c9a1919a30260973241e3e4dca31b263](https://gist.github.com/JL1946/c9a1919a30260973241e3e4dca31b263)

**ESP32 Crash Information - Output fromSerial Monitor**
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00 
mode:DIO, clock div:2 
load:0x3fff0018,len:4
load:0x3fff001c,len:928
ho 0 tail 12 room 4
load:0x40078000,len:9280
load:0x40080400,len:5860
entry 0x40080698 
�`�f�fx�x�����f~���~��~��fx`�f~x��fxf~f��ff��������ff�������������f��~��f����ff�f�fx�x���������ff����~�~����ff�������`����f���f�������`xf���fx���Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Core 1 register dump:
PC      : 0x40093d88  PS      : 0x00060134  A0      : 0x80092f0a  A1      : 0x3ffbe860  
A2      : 0x3ffb4394  A3      : 0x3ffbc704  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00060123  A7      : 0x00000000  A8      : 0x3ffbc704  A9      : 0x3ffbc704  
A10     : 0x00000019  A11     : 0x00000019  A12     : 0x00000001  A13     : 0x00000001  
A14     : 0x00060121  A15     : 0x00000000  SAR     : 0x00000014  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffd  
Core 1 was running in ISR context:
EPC1    : 0x40092392  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40093d88

Backtrace: 0x40093d88:0x3ffbe860 0x40092f07:0x3ffbe880 0x400919bf:0x3ffbe8a0 0x40091a29:0x3ffbe8e0 0x400860c5:0x3ffbe900 0x40107166:0x3ffbe920 0x40085dba:0x3ffbe960 0x400d2a17:0x3ffbe980 0x400d1a67:0x3ffbe9a0 0x40081365:0x3ffbe9c0 0x40081885:0x3ffbe9e0 0x401424a3:0x00000000

Core 0 register dump:
PC      : 0x40092392  PS      : 0x00060034  A0      : 0x80092bb4  A1      : 0x3ffbe360  
A2      : 0x3ffbddcc  A3      : 0x0000cdcd  A4      : 0xb33fffff  A5      : 0x00000001  
A6      : 0x00060021  A7      : 0x0000abab  A8      : 0x0000abab  A9      : 0x3ffbe360  
A10     : 0x00000003  A11     : 0x00060023  A12     : 0x00060021  A13     : 0x6000e044  
A14     : 0x0000002a  A15     : 0x3ffb5620  SAR     : 0x00000018  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x40136ea4  LEND    : 0x40136edf  LCOUNT  : 0x00000000  

Backtrace: 0x40092392:0x3ffbe360 0x40092bb1:0x3ffbe390 0x40090d93:0x3ffbe3b0 0x40093a59:0x3ffbe3d0 0x4008188e:0x3ffbe3e0 0x4013b35e:0x00000000

**Sloeber Install Details*
![image](https://user-images.githubusercontent.com/25297557/52170264-4f50c280-2715-11e9-915d-c0f4fa73adc2.png)

** Additional Comments**
I do not know if you would like to see additional items.
Please let me know via comments

**Comment by jantje** [comment]
My first idea is: are you sure you use the exact same esp32 platform version on arduino ide and sloeber?

**Comment by jantje** [comment]
No response for 7 days so I assume the versions are different

**Comment by JL1946** [comment]
Sorry... I caught the flu bug that is going around in Canada. I'm still not well, But I can tell you that the versions were the same. I have not revisited the issue since, and will when I feel better. Thanks...
