### ISSUE TITLE
Cannot delete plugin library from project

### ISSUE THREAD

**Issue by mvackel** [Sloeber/arduino-eclipse-plugin#1075]
If a project uses a library that is present at the plugin folder, for instance, the OneButton library, at ECPLISE_HOME\ardunoPlugin\libraries\OneButton\1.3.0, and you have a modifiedt lib stored at your private libraries folder, it is not possible to delete the plugin library from the project to use the modified private version. 

After right clicking the original lib and "Delete", the plugin automatically adds the lib again to the project.

I think that the expected action would be to simply remove the reference from the project and let the private version be used.

**Comment by jantje** [comment]
Sloeber will prefer the private library to the general library. If it doesn't there is probably some naming or setup problem.
Given the fact that Sloeber reinstalls the missing library (a option you can turn off in the preferences) it looks like the private library is not properly "installed"
