### ISSUE TITLE
Sloeber Linker Script Manipulation?

### ISSUE THREAD

**Issue by coogle** [Sloeber/arduino-eclipse-plugin#1086]
Is there a way to modify the .ld scripts used in a Sloeber project? I am trying to make a build that uses [rBoot](https://richard.burtons.org/2015/05/18/rboot-a-new-boot-loader-for-esp8266/), but to be done correctly I need to specify the exact locations I'd like my firmware to link to / upload to instead of 0x0

Any help getting a more complicated build setup like this working would be great!

**Comment by uzi18** [comment]
you need to modify esp8266 core files
