### ISSUE TITLE
Sloeber SAM21G (Arduino Zero/MKR) support

### ISSUE THREAD

**Issue by sgtJohnny** [Sloeber/arduino-eclipse-plugin#1092]
I tried to use files of the SAM21G boards (Zero, MKR) with sloeber, but i get a problem.

The Hardware Files were copied to the arduinoPlugin folder, just like it can be done with avr custom boards. Now i can select the boards without a problem.

I also copied the toolchain folders but my problem is in linking the subdir.mk. In the AVR version, they show the full sloeber path. In the SAM version, i only get a stub "/bin/arm-non-eabi-gcc", which results in :

"The system cannot find the path specified."

**AVR subdir.mk**
"I:\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++"

**SAM21 subdir.mk**
"/bin/arm-none-eabi-g++"

To fix this error, i unticked "generate make automatically" and then edited the subdir.mk with the absolute paths for gcc, core and variant. Sadly there are alot of subdir.mk files that would need to be modified. 

Is there a way to change this globally?

**Comment by jandrassy** [comment]
install the packages with Boards Manager for proper board's package tools instalation
