### ISSUE TITLE
Arduino Due Native USB Port

### ISSUE THREAD

**Issue by AlexandreBras** [Sloeber/arduino-eclipse-plugin#1095]
Hello,

I have been working with Eclipse IDE for a few days now with the arduino due.

But now I have developed my board based on the arduino due processor (SAM3X8E ).

With the arduino IDE I can program code into the board using just the native USB Port, with ecplise IDE this is not possible.

I have tried with a genuine arduino due, also with native usb port and the error is the same. The board, and COM port are selected properly as you can see with the image attached.

The console outputs this:

"Starting upload
Uploading project "MY_PCB_TEST" with "BOSSAC"
Forcing reset using 1200bps open/close on port : "COM11"
PORTS { COM11,} / { COM11,} => {}
PORTS { COM11,} / { COM7, COM11,} => { COM7,}
Com port reset took 500 ms.
Using port "COM7" from now onwards
Ending reset

Launching: C:\DEV\CV\eclipse_ESP32\arduinoPlugin\packages\arduino\tools\bossac\1.6.1-arduino/bossac.exe --port=COM7 -U true -e -w -b C:\DEV\CV\MY_PCB_TEST/Release/MY_PCB_TEST.bin -R
Output:
Atmel SMART device 0x285e0a60 found
Erase flash
done in 0.014 seconds

Write 24392 bytes to flash (96 pages)

[ ] 0% (0/96 pages)
[== ] 9% (9/96 pages)
[===== ] 18% (18/96 pages)
[======== ] 28% (27/96 pages)
[=========== ] 37% (36/96 pages)
[============== ] 46% (45/96 pages)
[================ ] 56% (54/96 pages)
[=================== ] 65% (63/96 pages)
[====================== ] 75% (72/96 pages)
[========================= ] 84% (81/96 pages)
[============================ ] 93% (90/96 pages)
[==============================] 100% (96/96 pages)
done in 1.155 seconds
Set boot flash true
CPU reset.
The execution of command "1.6.1-arduino/bossac.exe" is done."

And then a window says that COM11 was not found.

As anyone been able to program code to the arduino due through the native usb port?

Thank you.
![due](https://user-images.githubusercontent.com/36440438/60432739-ea819180-9bfa-11e9-9774-addd72269bbd.JPG)

**Comment by wimjongman** [comment]
Use COM7
