### ISSUE TITLE
On windows, the private library path and private hardware path point to the wrong place

### ISSUE THREAD

**Issue by madhephaestus** [Sloeber/arduino-eclipse-plugin#1098]
**Describe the bug**
The default location for Arduino to place the sketchbook is 
```
<UserHome>Documents/Arduino/
```
the default generated by the plugin is 
```
<UserHome>/Arduino/
```
**To Reproduce**
1. Open a standard Arduino install and install a library using the library manager
2. open Sloeber and attempt to use theat library
3. the library is not found, and Sloeber attempts to download it

**Expected behavior**
I would expect Sloeber to look for libraries and toolchains in the same default directory as Arduino by default

**Desktop (please complete the following information):**
 - Windows 10 Arduino 1.6.x and 1.8.x

**Additional context**
This is the line that is wrong:

https://github.com/Sloeber/arduino-eclipse-plugin/blob/296aedb05df3478f06d2687f951a0d03c664f18c/io.sloeber.core/src/io/sloeber/core/api/Defaults.java#L33

**Comment by jantje** [comment]
Looks like they use the  "Documents" folder now on windows like on mac. probably also on Linux. So this should be a really easy fix (remove the mac test).
I guess the same applies for the hardware path.

**Comment by madhephaestus** [comment]
no, not on linux, its still in $HOME on linux
