### ISSUE TITLE
Additional steps to get Ethernet examples working?

### ISSUE THREAD

**Issue by slushpuppy** [Sloeber/arduino-eclipse-plugin#1107]
Hi,

     I am using a controllino board and I am not able to get any of the Ethernet examples working. Those same examples run perfectly fine on Arduino IDE. May I know if I require additional steps in Sloeber IDE to get Ethernet library to work?

Thank you

**Comment by slushpuppy** [comment]
Well that was odd.. I had to delete the project, reinstall the boards/libraries before it worked.

**Comment by jantje** [comment]
Good to see it works :-)
