### ISSUE TITLE
Not working in MacOS Catalina 

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [Sloeber/arduino-eclipse-plugin#1125]
the newest Sloeber seems not working in Mac OS Catalina. Is there anyone using Sloeber with Catalina?

**Comment by jantje** [comment]
have you seen #1111 ?

**Comment by Heltec-Aaron-Lee** [comment]
Thank you.

**Comment by Heltec-Aaron-Lee** [comment]
Seems the #1111 not help me. When I tried to open it, it show me following messages:
![image](https://user-images.githubusercontent.com/32860565/74221369-f256f780-4cec-11ea-9d6d-f5f380ef3046.png)

This means "Sloeber is broken, move it to trash?"

**Comment by jantje** [comment]
have you seen #1141
