### ISSUE TITLE
ESP8266 Platforms

### ISSUE THREAD

**Issue by agusma** [Sloeber/arduino-eclipse-plugin#1127]
thank you for sloeber, great IDE for Arduino based project.
I am using Sloeber v4.3.2
the problem with this version is that it cannot create projects for esp8255 v 2.5.1 and v2.5.2

**Comment by erdemuncuoglu** [comment]
There are known issues with v2.5.1 and v2.5.2 which are fixed in v2.6.1.
I suggest you to use v2.6.1 or higher.
