### ISSUE TITLE
How to define global #define ?

### ISSUE THREAD

**Issue by executer-uno** [Sloeber/arduino-eclipse-plugin#1128]
Hello, I can not make declaration prior to Arduino includes
I need to define
#define NO_GLOBAL_SERIAL
prior to Arduino.h include. To disable serial ports declaration.

If set it in first line of *.ino file then it inserted to second line of *.ino.cpp
```
#ifdef __IN_ECLIPSE__
//This is a automatic generated file
//Please do not modify this file
//If you touch this file your change will be overwritten during the next build
//This file has been generated on 2020-01-14 14:27:02

#include "Arduino.h"
#define NO_GLOBAL_SERIAL
```

Are there any option to define NO_GLOBAL_SERIAL before Arduine include?

**Comment by jantje** [comment]
Look at project properties->arduino->compiler options
There you can add -DNO_GLOBAL_SERIAL to the command line.
