### ISSUE TITLE
Serial Monitor in Sloeber Arduino IDE

### ISSUE THREAD

**Issue by NorbertNix** [Sloeber/arduino-eclipse-plugin#1132]
Sloeber Serial Monitor
Hallo and good evening,
I have no exp. with c++ in your Sloeber environment.
So im a newbi, sorry for that. :-)

+++ What id did
Installed Sloeber IDE :-)
Created a Ardunio project
Configured Board,
Created index with io.h and arduion.h (like your YT Vidio)
Created Communication to COM3 (checked my environmend befor)
Started Coding
Compile (no Errors)
Upload (no Errors)
Checked Serial Monitor (no output)

**Expected behavior**
See the output like coded in the Sketch.
I expected that i get an error but in minimum i find the Output "Test" two times in that monitor

**Screenshots**
![grafik](https://user-images.githubusercontent.com/60114861/72756161-affa3900-3bcc-11ea-9361-91c3396857ef.png)

![grafik](https://user-images.githubusercontent.com/60114861/72756295-09626800-3bcd-11ea-8812-494c395ae473.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser firefox

**Smartphone (please complete the following information):**
 -
**Additional context**

**Comment by jantje** [comment]
your bautrates do not match
