### ISSUE TITLE
Rows in table disappear when the mouse moves

### ISSUE THREAD

**Issue by Mark-81** [Sloeber/arduino-eclipse-plugin#1135]
**Describe the bug**
Rows in tables disappear when the mouse moves on.

**To Reproduce**
1. Go to Project > Properties > C/C++ Build > Environment or Project > Properties > C/C++ General > Paths and Symbols
2. Click on the table in the right pane
3. Move the mouse
4. The rows disappear and the behavior is very weird

**Expected behavior**
I expect the rows stay there...

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/18552813/72922097-b9121400-3d4c-11ea-900d-45b9bc73e68c.jpg)

As you can see, when I grabbed the screenshot my mouse was on the only visible row, but *all* the rows of the table were populated.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10 64-bit

**Comment by jantje** [comment]
This is probably related to the colour scheme you use.
