### ISSUE TITLE
Adding a library changes the version of previous selected libraries

### ISSUE THREAD

**Issue by umpfel** [Sloeber/arduino-eclipse-plugin#1139]
**Description / to Reproduce**
In some cases I have multiple versions of a library. For example:
```
Sloeber/arduinoPlugin/libraries/MyLibrary/..
..master
..1.2.0
..1.5.1
```

1. Via Arduino -> "Add a library to the selected project" add the "MyLibrary" to the project
2. In the project in the libraries folder, do a right click on "MyLibrary" -> "Properties" -> "Resource" -> "Location" -> "Edit" select the version of the library that you want to use (e.g. 1.5.1 because master is still under development and not ready to use).
3. Build project -> everything working as expected
4. Now add another library to the project
5.  **Error:** The versions of my previously added libraries are also changed. So instead of `MyLibrary/1.5.1` -> `MyLibrary/master` is now used.

**Expected behavior**
I would expect that only the new library is added and all existing libraries should remain untouched

**Desktop:**
 - OS: LinuxMint 19.3
 - Sloeber plugin version: 4.3.1.201910070607

**Comment by jantje** [comment]
If you do not want to use the latest version you can not use the arduino library stuff.
You can create your own folder FI myLibs and link to the version code you want and delete the link in libraries folder.
The stuff under the folders libraries and core is controlled by Sloeber. Not by you.
