### ISSUE TITLE
Failed to create project for stm32 

### ISSUE THREAD

**Issue by hasikp1** [Sloeber/arduino-eclipse-plugin#1140]
Unable to create a new project.
Failed to create project java.lang.reflect.InvocationTargetException.
I have attached the error log and the screenshot of the project settings.
 
[eclipserr.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/4120996/eclipserr.log)

![Screenshot (27)](https://user-images.githubusercontent.com/48294216/73241522-424f9d80-41c8-11ea-8fa1-d0cb89a2e059.png)

**Comment by jantje** [comment]
Are you using the sloeber product? It looks as if there is a conflicting CDT Sloeber plugin

**Comment by hasikp1** [comment]
Which one should I use?. There are two in the eclipse market place.
![plugin](https://user-images.githubusercontent.com/48294216/73806486-a210fe80-47ef-11ea-83e3-af7df66b2536.png)

**Comment by erdemuncuoglu** [comment]
Second one: "The Arduino Eclipse plugin named Sloeber V4"

Alternatively you can add nightly repository into eclipse:
Open from menu `Help -> Install New Software...` then press button `Add..`
Put below into form
Name: Sloeber nightly
Location: http://eclipse.baeyens.it/update/V4/nightly

**Comment by jantje** [comment]
You should download from http://eclipse.baeyens.it/
