### ISSUE TITLE
{build.system.path} should be the 'actual platform', not the 'target platform'

### ISSUE THREAD

**Issue by jandrassy** [Sloeber/arduino-eclipse-plugin#1150]
An arduino core can be used as referenced. It is described in ["Arduino IDE 1.5 3rd party Hardware specification"](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#referencing-another-core-variant-or-tool). 

In Sloeber `{build.system.path}` evaluates to 'target platform' (board platform), not to 'actual platform' (core platform) as it should.

The Arduino SAM and the STM STM32 cores use the `system` folder. This cores now can't be used as referenced with Sloeber. 

A workaround of this Sloeber problem now is to replace in platform.txt `{build.system.path}` to  `{build.core.path}/../../system`.

Examples of referencing a core from custom hardware definitions: https://github.com/jandrassy/my_boards

**Comment by jantje** [comment]
IMHO I fixed this 2 days ago. Due to other issues it is not yet available in the nightly. Hopefully tomorrow.
https://github.com/Sloeber/arduino-eclipse-plugin/commit/774007cc63fd0f07bc53ebc97611063198cc6480

**Comment by jandrassy** [comment]
thank you
