### ISSUE TITLE
folder name starting with 'eclipse-' corrupted in makefile 

### ISSUE THREAD

**Issue by jandrassy** [Sloeber/arduino-eclipse-plugin#1153]
Nightly plugin version 4.3.3.202003070521 and current HEAD generates to makefile
```
AR += \
/home/duro/eclipse/-workspace/Test3/Release/arduino.ar \

```
```
/home/duro/eclipse/-workspace/Test3/Release/arduino.ar: $(AR_OBJ)
	@echo 'Starting archiver'
```
the right folder should be `eclipse-workspace`. folder `/home/duro/eclipse` exists too. then
```
     /home/duro/eclipse/-workspace/Test3/Release/arduino.ar: No such file or directory
makefile:73: recipe for target '/home/duro/eclipse/-workspace/Test3/Release/arduino.ar' failed
```

for other workspace folder with `-` the makefile is ok.
```
AR += \
/home/duro/runtime-EclipseApplication/Blink/Release/arduino.ar \
```

EDIT .settings/org.eclipse.cdt.core.prefs contains
```
environment/project/io.sloeber.core.toolChain.release.1221121858/A.BUILD.PATH/value=${eclipse_home}-workspace/Test3/Release
```
the other project has a full path
```
environment/project/io.sloeber.core.toolChain.release.366347866/A.BUILD.PATH/value=/home/duro/runtime-EclipseApplication/Blink/Release
```

**Comment by jantje** [comment]
As I have seen - being used in both project name and in folder names I guess this problem only occurs in workspace names.

**Comment by jandrassy** [comment]
the problem is in .settings/org.eclipse.cdt.core.prefs
`A.BUILD.PATH/value=${eclipse_home}-workspace/Test3/Release`

part of the path is missmatched as a variable

**Comment by jantje** [comment]
I can not reproduce the issue here
![afbeelding](https://user-images.githubusercontent.com/1175841/81016914-a4700c80-8e61-11ea-8ad2-c7e76b56835a.png)

**Comment by jandrassy** [comment]
Eclipse is installed in
/home/duro/eclipse/
and workspace is
/home/duro/eclipse-workspace/
so something matches ${eclipse_home} in /home/duro/eclipse-workspace/ and replaces it to
${eclipse_home}-workspace/
resulting in
/home/duro/eclipse/-workspace/

**Comment by jantje** [comment]
I'll try this specific combination.
```
Eclipse is installed in XXX/eclipse/
and workspace is  XXX/eclipse-workspace/
```
Seems like you are on unix.
If I can't reproduce in windows I'll try linux.
IMHO this seems to be a very specific case.

**Comment by jandrassy** [comment]
Yes I am on Linux. 
The location and name of folder eclipse-workspace is default.
I don't know how many people install eclipse in home folder and name it eclipse. The current installer offers a folder named for example java2020-03 and creates a subfolder named eclipse in it. I deleted the java2020-03 part so I ended up with folder named eclipse. (And I name my Eclipse installation folder always eclipse.)
And it is possible, that the bug could match other variables to other paths too.

**Comment by uzi18** [comment]
have linux and use almost the same workspace is in eclipse-workspace or arduino-workspace 
but in facts did not created new project for long time

**Comment by jantje** [comment]
Tested on linux and windows.
I can't recreate the problem

**Comment by jantje** [comment]
Anyone could recreate this issue?
