### ISSUE TITLE
Can't upload to arduino

### ISSUE THREAD

**Issue by mikep01** [Sloeber/arduino-eclipse-plugin#1156]
Error message reporting failure when uploading to arduino:
Failed to run the Upload recipe 
Cannot run program "" (in directory "C:\{my eclipse directory}"): CreateProcess error=87, The parameter is incorrect

**To Reproduce**
Create a project using EPS8266 2.6.3
Build
Press "upload"

**Expected behavior**
The upload should complete without error.

**Desktop (please complete the following information):**
Windows 10

Sloeber plugin 4.3.3.202003110521

**Comment by mikep01** [comment]
In case it helps - when moving from 4.3.1 to 4.3.3, I must open each existing project to the arduino properties, then hit "apply and close" before the project will build.
If I don't do that, it won't build but it will upload.
If I do update the properties, it'll build but no longer upload. New projects build but do not upload either.

**Comment by jantje** [comment]
> 
> 
> In case it helps - when moving from 4.3.1 to 4.3.3, I must open each existing project to the arduino properties, then hit "apply and close" before the project will build.
> If I don't do that, it won't build but it will upload.
> If I do update the properties, it'll build but no longer upload. New projects build but do not upload either.

That is the normal upgrade process. http://eclipse.baeyens.it/how_to.shtml#/n

Something basic is currently wrong when handling environment variables in CDT. I'm investigating but current thinking is that it is a racing condition which makes it very hard to debug 😕

**Comment by mikep01** [comment]
Fixed for new projects, thanks!
Still a problem for projects created before this version.

**Comment by jantje** [comment]
As this was a regression in between releases I'm simply closing this issue
