### ISSUE TITLE
Project does not work after import from Git

### ISSUE THREAD

**Issue by uwekoenig** [Sloeber/arduino-eclipse-plugin#1168]
**Describe the bug**
After importing a project from Git it does not work correctly. E.g. it is not possible to compile the project because it happens nothing when pressing the buttons. In the Project Explorer many entries except the source code are missing.

**To Reproduce**
1. Create a new project "Arduino Sketch"
2. Right click on the project in Project Explorer > Team > Share Project ...
3. Select the repository to share with
4. File > Switch Workspace
5. Create a new workspace
6. Window > Perspective > Open Perspective
7. Select Git
8. Clone the repository
9. Right click on the repository > Import Project ...
10. Import both folders and check if the project is now open in the Project Explorer
11. The problem is now, that many items in the Project Explorer are missing (see the screenshots)

**Expected behavior**
The project opens like in the other workspace or machine.

**Screenshots**
View in Project Explorer in workspace where the project was created
![grafik](https://user-images.githubusercontent.com/23554459/78554718-f21a3a80-780b-11ea-8c2e-f5eae5e1a044.png)

View in Project Explorer in another workspace where the project was imported from Git
![grafik](https://user-images.githubusercontent.com/23554459/78554416-67d1d680-780b-11ea-8e73-a3501c2803a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.3.2

**Comment by uzi18** [comment]
please leave also git repo link to test

**Comment by jantje** [comment]
you need to open the project properties->arduino->apply and close
Note that it is a good practise to mark .project and .cproject as unchanged

**Comment by uwekoenig** [comment]
@uzi18: Here is a repository for testing:
https://github.com/uwekoenig/SloeberGit.git

@jantje: "Aduino" does not exist in Project Properties, after importing both projects from the Git repository.
![grafik](https://user-images.githubusercontent.com/23554459/78597115-3679fa80-784d-11ea-836b-d4b718d75d3b.png)

With your comments I think I found the problem now. It is necessary to import only one of the shown projects (the one with the right path).
![grafik](https://user-images.githubusercontent.com/23554459/78597582-139c1600-784e-11ea-9fa8-de9d40f63c8a.png)
When doing it in that way everything works like expected. Thank you for your quick support!

**Comment by jantje** [comment]
Nice to hear it works
