### ISSUE TITLE
Building project with ESP8266WebServer library fails

### ISSUE THREAD

**Issue by JochenKoehler69** [Sloeber/arduino-eclipse-plugin#1178]
Hi together,

I tried to build up a project described in [WifiManager](https://randomnerdtutorials.com/wifimanager-with-esp8266-autoconnect-custom-parameter-and-manage-your-ssid-and-password/). Building as Release-Project without debugging capability is working well. However when I try to build it with debug-capabilities I got these error messages:

> 'Starting C++ compile'
"D:\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-ID:\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-ID:\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-ID:/Arduino/WifiAPSwitch/NodeMCU_V10_Debug/core" -c -Wall -Wextra -g -ggdb -Og -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DDEBUG -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_CORE -DDEBUG_ESP_SSL -DDEBUG_ESP_WIFI -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_UPDATE -DDEBUG_ESP_HTTP_SERVER -DDEBUG_ESP_UPDATER -DDEBUG_ESP_OTA -DDEBUG_TLS_MEM -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10802 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_ESP12\""  -DESP8266   -I"D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"D:\sloeber\arduinoPlugin\packages\Jantje\hardware\esp8266\1.0.0\libraries\gdb" -I"D:\Arduino\libraries\MyLibrary" -I"D:\Arduino\libraries\sscanf" -I"D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.6.3\libraries\DNSServer\src" -I"D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src" -MMD -MP -MF"sloeber.ino.cpp.d" -MT"sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "..\sloeber.ino.cpp"  -o  "sloeber.ino.cpp.o"
In file included from D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer.h:235:0,
                 from ..\sloeber.ino.cpp:12:
D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'bool esp8266webserver::ESP8266WebServerTemplate<ServerType>::authenticate(const char*, const char*)':
D:\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:143:77: error: 'class String' has no member named 'equalsConstantTime'
       if(base64_encode_chars(toencode, toencodeLen, encoded) > 0 && authReq.equalsConstantTime(encoded)) {
                                                                             ^
subdir.mk:18: recipe for target 'sloeber.ino.cpp.o' failed
make: *** [sloeber.ino.cpp.o] Error 1
"D:/sloeber/arduinoPlugin/tools/make/make all" terminated with exit code 2. Build might be incomplete.

19:40:26 Build Failed. 3 errors, 0 warnings. (took 810ms)

Could anybody help me here?
I'm pretty sure that all project configurations are okay because without including the ESP8266WebServer library everything works fine.

Bye
Jochen

**Comment by jantje** [comment]
looks like https://github.com/esp8266/Arduino/issues/4919
