### ISSUE TITLE
Serial monitor colours not right after a disconnect/reconnect

### ISSUE THREAD

**Issue by dajtxx** [Sloeber/arduino-eclipse-plugin#1190]
Connect COMx - msgs black
Connect COMy - msgs red
Disconnect COMx
Connect COMx - msgs red

Now both COMx and COMy messages are red.

Found this while testing the timestamp changes.

**Comment by jantje** [comment]
That is very right. The code uses a simple counter and an array.
https://github.com/Sloeber/arduino-eclipse-plugin/blob/master/io.sloeber.ui/src/io/sloeber/ui/monitor/views/SerialMonitor.java#L522

**Comment by jantje** [comment]
I guess it works now with the nightly.
