### ISSUE TITLE
Sloeber installs mbed as default instead of avr

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#1196]
When installing a fresh sloeber normally it installs the latest avr platform.
Now it installs the arduino_beta mbed platform

**Comment by speedfixer** [comment]
Should there be a recent nightly that has all the targets?
Specifically - a linux 64 build is what I need.

**Comment by jantje** [comment]
@speedfixer I don't understand your question nor the link to this issue which is a default only problem for a new installation

**Comment by speedfixer** [comment]
Agreed.

I'm in Linux.
For anyone that hits this:

go to tab Windows
then --> Arduino/Platforms and Boards

select correct type of board - in this case standard arduino, not arduino-beta

then select lib version (latest?) and board

If the files aren't downloaded yet, they will be - it will take awhile, watch the messages at the lower right.

Once selected here, you may not need to select them again, but you will have more choices now in your sketch selection properties section.

If they weren't already downloaded, they won't be selectable in the project/sketch properties selection.

Perhaps I missed something in the install/setup/config notes - but I hope this helps others.

david

**Comment by networkname** [comment]
Thanks your post really helped. I am trying Sloeber for the first time and I was trying to figure out what was going on. For anyone else the only thing missing was you need to make sure to choose the proper platform folder under Project | properties | Arduino. If you could give more details about which libraries to select that would help.

**Comment by jantje** [comment]
The libraries depend on your project. Some libraries (read the ones with the same name as the header) are even installed automagically if in one of the provided json files.
But as a professional programmer you probably want to import the libraries from github and link them in private libraries.
In short
Arduino IDE focusses n beginners and has only one way to do things.
Sloeber focusses on professional users and there are more ways to do things than I can think of.
