### ISSUE TITLE
Improvement request: Add filter to serialmonitor so only 1 serialconnection data is shown.

### ISSUE THREAD

**Issue by ceugster** [Sloeber/arduino-eclipse-plugin#1203]
Monitor view displays all data from different serial ports in same field. Would be nice, if when I pick a port from the combo the the output of only this currently selected port is showing up and when switching to other port, only that output is shown.

**Comment by jantje** [comment]
The text style shows which port the info is coming from.
This is done this way to easily see the communication between 2 arduino's.
Adding a filter could be a add-on
