### ISSUE TITLE
Eclipse Aurduino Due Upload Issues

### ISSUE THREAD

**Issue by ghost** [Sloeber/arduino-eclipse-plugin#1207]
**Describe the bug**
When uploading to Arduino Due, I receive an error that states "No device found on /dev/cu.usbmodem14301" after launch. Where "cu.usbmodem14301" is the port. The bug is described in more detail in "Additional context"

**To Reproduce**
Attempt to upload a new sketch to Arduino Due.

**Expected behavior**
For the program to upload without issue.

**Screenshots**
<img width="1507" alt="Screen Shot 2020-07-21 at 11 02 14" src="https://user-images.githubusercontent.com/68603226/88071309-a59c0600-cb41-11ea-9781-6cb1962f7200.png">

**Desktop (please complete the following information):**
 - OSX CATALINA 10.15.5 (19F101)
 - ECLIPSE Version: 2020-06 (4.16.0) Build id: 20200615-1200
 - SLOEBER Version: V4.3.3

**Additional context**
At this point, I have determined that the issue is within sober where during the "Launch" process it executes a call to BOSSAC:

Launching: /Users/alex/eclipse/cpp-2020-06/Eclipse.app/Contents/Eclipse//arduinoPlugin/packages/arduino/tools/bossac/1.6.1-arduino/bossac --port=/dev/cu.usbmodem14301 -U false -e -w -b /Users/alex/eclipse-workspace/demo801/Release/demo801.bin -R 

I attempted to do this through Terminal modifying the PORT parameter to " port=cu.usbmodem14301 " 
Everythiung operates correctly. The issue is that Sloeber adds the "/dev/" and that needs to not be there. I have tried modifying it manually to no avail. However, it seems like that IS needed for the RESET that the DUE needs at 1200 baud but NOT for upload.

**Comment by jantje** [comment]
Whjich of the 2 usb ports of the due are you using?
Do you have the same problem with the other port?
Can you provide a screenshot of your project properties->arduino?
