### ISSUE TITLE
Can't install V4.3.3 on OS X Catalina

### ISSUE THREAD

**Issue by arieavnur** [Sloeber/arduino-eclipse-plugin#1209]
**Describe the bug**
Trying to open the sloeber.app, get "the file is corrupted, move it to trash."
**To Reproduce**
1. On OS X 10.15.5
2. Download the 4.3.3 packaged file, or V4.3.3_mac64.2020-04-23_11-36-51.zip 15-58-14-204.zip,
3. Open it with the archive utility as instructed. 
4. Double click on the Sloeber.app file, 
5. Get: “Sloeber.app” is damaged and can’t be opened.
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] )S X 10.15.5
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22]  13.1.1 (15609.2.9.1.2)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by erdemuncuoglu** [comment]
Check this out,
[http://eclipse.baeyens.it/stable.php?OS=MacOS](http://eclipse.baeyens.it/stable.php?OS=MacOS)

**Comment by arieavnur** [comment]
Same result, see image attachment below.

**Comment by jantje** [comment]
The instructions contain another step

> Due to mac new security approach a simple download and extract will not work.
> 
> Follow following steps to install.
> 
> 1)download with mac browser.
> 
> 2)unpacked the sloeber ide zip file with the macOS native Archive Utility. Not in the download folder!!!
> 
> 3)in the folder where you extracted Sloeber run: **sudo xattr -r -d com.apple.quarantine Sloeber.app**
> 
> Read the info on this site at: install->start here-> MacOS comments

**Comment by arieavnur** [comment]
But I get from the download a sloeber.app and not sloeber.zip or some other archive...

**Comment by arieavnur** [comment]
It worked this time!! Thank you.
But my board—Uno R3 isn’t among the boards list offered by the create project form. 
What do I do? Where do I find documentation?
Thanks,
Arie.

**Comment by jantje** [comment]
you are hitting #1196 
Here is the workaround https://github.com/Sloeber/arduino-eclipse-plugin/issues/1196#issuecomment-646379295
