### ISSUE TITLE
eclipse snap app: install failure: perms error

### ISSUE THREAD

**Issue by corbolais** [Sloeber/arduino-eclipse-plugin#1212]
**Describe the bug**
Installing sloeber arduino plugin fails as snap package permissions deny installation:

    Sloeber does not have write access to /snap/eclipse/48 and therefore can not create the folder /snap/eclipse/48/arduinoPlugin

**To Reproduce**

    snap install eclipse --classic

Then install the sloeber arduino plugin as described on the marketplace page (drag icon into eclipse).

After a restart of eclipse:

```
Failed to download "https://github.com/Sloeber/arduino-eclipse-plugin/releases/download/V4_3_2/examples_Arduino_1_8_10.zip".
/snap/eclipse/48/arduinoPlugin/downloads/examples_Arduino_1_8_10.zip
An internal error occurred during: "Finishing the installation ..".
Index: 0, Size: 0
[more arduino libs fail to "download" as they cannot be written inside a snap package]
```

**Expected behavior**
Install sloeber arduino plugin and its dependencies w/o failures.

**Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by jantje** [comment]
If you use the nightly #1199 you can use SLOEBER_HOME to point to where Sloeber can write
Otherwise create a linked folder
