### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by bell21498** [Sloeber/arduino-eclipse-plugin#1214]
Hello
When i compile with Arduino IDE everything is OK.
When i compile with Sloeber gives me errors. Why??
Is there something to settings that i miss it??
I am new to Sloeber ...  I like it ..  I want to use it..

**Comment by erdemuncuoglu** [comment]
Can you give more information about your issue like error.log, console output, etc.

P.S. you can find a good bug report template [here](https://github.com/Sloeber/arduino-eclipse-plugin/issues/new?template=bug_report.md)

**Comment by bell21498** [comment]
I fix it..Everything works good..Thanks.
