### ISSUE TITLE
Unable to compile: /bin/avr-size not found

### ISSUE THREAD

**Issue by Kashouryo** [Sloeber/arduino-eclipse-plugin#1218]
**Describe the bug**
make can not locate the location of /bin/avr-size

**To Reproduce**
1. Create a new project
2. restart IDE
3. hit verify and error

**Expected behavior**
compile and upload normally 

**Screenshots**
"/bin/avr-size" is not recognized as an internal or external command, operable program or batch file
makefile:70: recipe for target 'sketch1' failed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (why browser?)
 - Version 81.0 b2 (sure...)

**Comment by jantje** [comment]
Sounds like a typical configuration problem.
Which board do you use and how did you install it?

**Comment by Kashouryo** [comment]
This is the core that I am using https://github.com/dbuezas/lgt8fx
MiniCore and Arduino OEM core works fine

**Comment by jantje** [comment]
This seems to be a very general problem.
This is now fixed in master but unfortunately my build server (that pushed changes to the update site) is down

**Comment by Kashouryo** [comment]
Thank you for fixing it! I am sorry to hear that your server got attacked(from your website). Maybe consider using a CI or GitHub Action to build your nightly binary?

**Comment by Kashouryo** [comment]
With this new release, I am having a new issue:

Starting upload
Uploading project "test" with "AVRDUDE"
no reset because we are using a programmer


Launching:  
Output:
Cannot run program "" (in directory "C:\Users\dell\Documents\sloeber-workspace"): CreateProcess error=87, the parameter is incorrect
failed to upload "L/test/test}/Release/MegaHitsv2.hex"

**Comment by jantje** [comment]
Do you build the code yourself?
If not you do not have the fix.
Anyway, for the new problem check your project properties->aduino.

**Comment by Kashouryo** [comment]
yes, I just pulled git master branch, which contains the newest code.

**Comment by jantje** [comment]
I think this one can be closed now. Please reopen if I think wrong ;-)
