### ISSUE TITLE
make: *** No rule to make target `clean'. message is shown when the make file does not yet exist.

### ISSUE THREAD

**Issue by rlogiacco** [Sloeber/arduino-eclipse-plugin#122]
I'm running Arduino Eclipse on Arduino IDE 1.5.5.r2, which I do know it's not supported.

I'm a Java developer with a little experience on Eclipse, I might be able to help if you pinpoint me

**Comment by asphalak** [comment]
i m using Atmega 128 board in Ubuntu OS, i got following error when i type "make clean"

asphalak@asphalak-HP-Pavilion-11-x360-PC:~$ make clean
make: *** No rule to make target `clean'.  Stop.

i m already check make file but i found it ok.

**Comment by jantje** [comment]
type "make clean"?
Can you elaborate? As far as I know there is no such thing as typing "make clean" in the arduino eclipse plugin.

**Comment by asphalak** [comment]
i m using atmega 128 AVR controller not arduino..

**Comment by rlogiacco** [comment]
That's totally unclear: are you seeking help on the Arduino Eclipse Plugin or on some other tool? This is the issue tracker for the Arduino Eclipse Plugin my friend....
