### ISSUE TITLE
Way to open existing Arduino project without creating sample file

### ISSUE THREAD

**Issue by rmspacefish** [Sloeber/arduino-eclipse-plugin#1228]
Hi,

Thanks for creating this great plugin. I have a small improvement suggestion.
Maybe I did not see the option, but is there a way to open an "exisiting" project and ommit the generation of sample files?
I had an existing project inside a folder, I created a project inside that folder. Then I deleted the sample files (a .cpp file with setup, loop was already existing) and everything worked just fine. I think it would be nice if there is an option to just not add any sample files. What do you think about this?

Also, another small question: What is the purpose of the sloeber.ino.cpp file created? It seems to mimic the primary .ino file a little bit and when I deleted it, the code still compiled without issues.

Kind Regards
Robin

**Comment by jantje** [comment]
If the sketch name is the [foldername.ino] and you select default ino project no files should be created.

**Comment by rmspacefish** [comment]
Ah okay, thanks for the tip.
I think an explicit option still would be nice.

**Comment by jantje** [comment]
Feel free to implement one.

**Comment by rmspacefish** [comment]
Got following error when trying to build the SDK on Windows 10. Do you have an idea what might cause this?

`
C:\Users\Robin\NoSyncDokumente\arduino-eclipse-plugin>mvn clean verify -PSDK,latest -DskipTests=true
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[ERROR] Internal error: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'JavaSE-12' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'JavaSE-12'
`

Maybe I will have more luck on Ubuntu.

**Comment by jantje** [comment]
It looks like it tries to build with java 12 and it doesn't find one
Note that I havn't build the sdk the last couple of months so it may have been an issue before you applied changes

**Comment by jantje** [comment]
FYI the SDK is to build a development environment for sloeber
Sloeber is the development environment for arduino boards

**Comment by jantje** [comment]
SDk builds fine here. Did you use maven 3.6.3?

**Comment by rmspacefish** [comment]
Yes, I installed the newest version 3.6.3

**Comment by jantje** [comment]
I have looked at the changes you have and I don't see any relation to sloeber sdk so I don't think the fact that the sdk build fails on your system is relevant.

**Comment by jantje** [comment]
@rmspacefish are you still working on this?

**Comment by rmspacefish** [comment]
Hi, I haven't had a chance to look at it again. Can you give a hint on how to "load" the changes after making them? 

Kind Regards
Robin

**Comment by jantje** [comment]
>Can you give a hint on how to "load" the changes after making them?

I'm not sure what you mean here. I assume you want to debug them or get them in some production environment.
Debug->simply debug the product in your eclipse environment where you made the changes
spread out 1->do the maven build  (as described here https://github.com/Sloeber/arduino-eclipse-plugin) and put the update site on a server (This will cause conflicts conflict with the sloeber update site so this is not a sustainable solution)
spread out 2-> Do the maven build and spread the product

**Comment by rmspacefish** [comment]
I just want to test whether the new feature (was quite small after all) just works. So instead of the default installed Sloeber Plugin, I would just like to use the version of the plugin with my changes. Can this be done by debugging it?

**Comment by jantje** [comment]
> Can this be done by debugging it?

yes off course. That is what debugging is for. You can even step through the code to validate that things do what you intended them to do.

**Comment by rmspacefish** [comment]
Alright, I will try to test it today or tomorrow.
