### ISSUE TITLE
Failed to download url http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2 error code is: 404

### ISSUE THREAD

**Issue by tdestro** [Sloeber/arduino-eclipse-plugin#1230]
download https://github.com/Sloeber/arduino-eclipse-plugin/releases/download/V4_3_3/V4.3.3_mac64.2020-04-23_11-36-51.zip

Failed to configer Sloeber
Failed to install [DEPRECATED] Arduino mbed-enabled Boards
Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2".
Failed to download url http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2 error code is: 404

java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by jantje** [comment]
This is a duplicate of #1196 with the added thing arduino mbed now seems deprecated
