### ISSUE TITLE
Problem with product installation

### ISSUE THREAD

**Issue by mclenaghan** [Sloeber/arduino-eclipse-plugin#1238]
Windows 10 64 bit, fresh installation from product downloaded today.
I'm getting an error:

Failed to configer Sloeber
Failed to install [DEPRECATED] Arduino mbed-enabled Boards
Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2".
Failed to download url http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2 error code is: 404

I haven't found this mentioned in the notes - although I could have missed it!

**Comment by jantje** [comment]
duplicate of #1235

**Comment by mclenaghan** [comment]
My apologies. There was a filter to only show open issues – so I missed the other one.

 

Ian
