### ISSUE TITLE
getting error when debugging Dictionary library code in Sloeber 

### ISSUE THREAD

**Issue by ponmathanaro** [Sloeber/arduino-eclipse-plugin#1239]
OS: Win10 64 bit
Sloeber: V4.3.3
Mingw-w64 : i686-8.1.0-posix-dwarf-rt_v6-rev0
Dictionary(Libarary) - 3.1.0 - added through Arduino-->Library Manager

When Debugging the sketch having "Dictionary" library code, build failed with below error and seeing error in libraries-->Dictionary folder

06:58:45 **** Incremental Build of configuration localdebug for project DemoFile ****
"C:\\unitTest\\Sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ..\sloeber.ino.cpp'
'Starting C++ compile'
"C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\tools\MinGW\5.3.0/bin/g++" -c -g -O0 -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_UNO -DARDUINO_ARCH_PC   -DLOCAL_RUN   -I"C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino" -I"C:\unitTest\Sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.8.3\variants\standard" -I"C:\unitTest\Sloeber\arduinoPlugin\libraries\LiquidCrystal\1.0.7\src" -I"C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\libraries\Servo" -I"C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\libraries\Wire" -I"C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src" -MMD -MP -MF"sloeber.ino.cpp.d" -MT"sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "..\sloeber.ino.cpp"   -o "sloeber.ino.cpp.o"   -Dsrandom=srand -Drandom=rand
In file included from ..\sloeber.ino.cpp:9:0:
C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src/Dictionary.h: In member function 'String Dictionary::json()':
C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src/Dictionary.h:512:7: error: ambiguous overload for 'operator=' (operand types are 'String' and 'char')
     s = '{';
       ^
In file included from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Print.h:26:0,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Stream.h:26,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Arduino.h:16,
                 from ..\sloeber.ino.cpp:7:
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:87:11: note: candidate: String& String::operator=(const String&) <near match>
  String & operator = (const String &rhs);
           ^
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:87:11: note:   conversion of argument 1 would be ill-formed:
In file included from ..\sloeber.ino.cpp:9:0:
C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src/Dictionary.h:512:7: error: converting to 'String' from initializer list would use explicit constructor 'String::String(char)'
     s = '{';
       ^
In file included from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Print.h:26:0,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Stream.h:26,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Arduino.h:16,
                 from ..\sloeber.ino.cpp:7:
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:88:11: note: candidate: String& String::operator=(const char*) <near match>
  String & operator = (const char *cstr);
           ^
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:88:11: note:   conversion of argument 1 would be ill-formed:
In file included from ..\sloeber.ino.cpp:9:0:
C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src/Dictionary.h:512:7: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
     s = '{';
       ^
In file included from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Print.h:26:0,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Stream.h:26,
                 from C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/Arduino.h:16,
                 from ..\sloeber.ino.cpp:7:
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:89:11: note: candidate: String& String::operator=(const __FlashStringHelper*) <near match>
  String & operator = (const __FlashStringHelper *str);
           ^
C:\unitTest\Sloeber\arduinoPlugin\packages\Jantje\hardware\pc\1.0.2\cores\arduino/WString.h:89:11: note:   conversion of argument 1 would be ill-formed:
In file included from ..\sloeber.ino.cpp:9:0:
C:\unitTest\Sloeber\arduinoPlugin\libraries\Dictionary\3.1.0\src/Dictionary.h:512:7: error: invalid conversion from 'char' to 'const __FlashStringHelper*' [-fpermissive]
     s = '{';
       ^
subdir.mk:18: recipe for target 'sloeber.ino.cpp.o' failed
make: *** [sloeber.ino.cpp.o] Error 1
"C:/unitTest/Sloeber/arduinoPlugin/tools/make/make all" terminated with exit code 2. Build might be incomplete.

06:58:47 Build Failed. 6 errors, 0 warnings. (took 2s.140ms)
[Sloeber_debug issue_Dictionary Library.docx](https://github.com/Sloeber/arduino-eclipse-plugin/files/5442877/Sloeber_debug.issue_Dictionary.Library.docx)

**Comment by jantje** [comment]
First of.
This is not a Sloeber issue but a https://github.com/jantje/hardware issue
Secondly
The https://github.com/jantje/hardware is not considered a final working project but a base to get started and contribute.

In this particular situation it seems there are some string conversion and addition methods in the dictionary library that are incompatible with the https://github.com/jantje/hardware repository
