### ISSUE TITLE
Adding Libraries for Other Hardware

### ISSUE THREAD

**Issue by rmerriam** [Sloeber/arduino-eclipse-plugin#1242]
Linux Eclipse 2020-09 

I added the ESP32 package from https://dl.espressif.com/dl/package_esp32_index.json. This is for Sparkfun ESP32 Thing. 

Can compile and upload `blink`. 

None of the examples or libraries from this package are available. They are in the plugin directory. How do I get them into the plugin?

**Comment by jantje** [comment]
So I added the json
![afbeelding](https://user-images.githubusercontent.com/1175841/97579462-5f80f900-19f2-11eb-8bfe-ac2b31927876.png)

Then installed platform  version 1.0.4
![afbeelding](https://user-images.githubusercontent.com/1175841/97579718-b25ab080-19f2-11eb-8596-d92d4f84db8f.png)

waited for it to install 

I tried creating a new project based on the BasicOTA example
![afbeelding](https://user-images.githubusercontent.com/1175841/97580644-db2f7580-19f3-11eb-9653-36830d8686f2.png)
![afbeelding](https://user-images.githubusercontent.com/1175841/97579999-0bc2df80-19f3-11eb-84e0-fd645eb5e832.png)

And indeed the example is not there
![afbeelding](https://user-images.githubusercontent.com/1175841/97580745-01551580-19f4-11eb-930e-46cc5f08a530.png)

But it is available in the add libraries
![afbeelding](https://user-images.githubusercontent.com/1175841/97580982-4f6a1900-19f4-11eb-8ca3-4cbc1ee8147c.png)

and he does pick the correct one
![afbeelding](https://user-images.githubusercontent.com/1175841/97581112-77f21300-19f4-11eb-80b4-d0a73a30187a.png)

So as a workaround you can create the default ino and copy and past the example code over the default ino content.
This worked fine for me with basicOTA
![afbeelding](https://user-images.githubusercontent.com/1175841/97581654-1b432800-19f5-11eb-9c20-783cf8e36782.png)

**Comment by jantje** [comment]
I tried again now finding the library and all is well here on my system

**Comment by rmerriam** [comment]
Okay, got it to work. Wasn't aware that examples would show up under the libraries. Thanks.

Also found you can check using `Project | Properties | Resource | Linked Resource | Linked Resource `. That lists all the libraries and their directories.

**Comment by jantje** [comment]
>On mine it did load the BasicOTA.ino file into the project. But it also loaded the other .ino files from other projects. I'll test that more for another issue.

When you create a sketch based on examples you can select multiple examples. Sloeber remembers your previous selections and add the new ones. At the bottom you can see how many have been selected.
![afbeelding](https://user-images.githubusercontent.com/1175841/97711392-59a41a00-1abd-11eb-8620-24f447b72a59.png)

The reason you can select multiple is for if you want a project using spi, wire, servo's .... you can have all the code in one go. Though it won't compile.
