### ISSUE TITLE
JANTJE.EXTRA.COMPILE  different from JANTJE.extra.compile

### ISSUE THREAD

**Issue by mr-miky** [Sloeber/arduino-eclipse-plugin#1244]
**Describe the bug**

**To Reproduce**
1. Load an old project
2. Open proprieties of project
3. Select Arduino/Builder options
4. You see that there are no extra commands to add

**Expected behavior**
That would load the extra commands of the old project

**Desktop (please complete the following information):**
 - OS: Fedora linux 32
 - Eclipse Platform Version: 2020-09 (4.17) Build id: I20200902-1800
 - Sloeber: (plugin version) 4.3.3.202010230421

The problem is that the configuration paring is case sensitive and in the old project the configuration is saved in JANTJE.EXTRA.COMPILE while the plugin searches and saves in JANTJE.extra.compile.
Could we make sure that if JANTJE.extra.compile is not found, a NON case sensitive search is done and then the parameter is saved in an updated way?

**Comment by jantje** [comment]
The update instructions http://eclipse.baeyens.it/how_to.shtml#/n state that after your step 
3 Select Arduino/Builder options
You need to select apply and close
Without the apply and close issue #1231 ( which includes a CDT fix) stopped the uppercasing as the CDT fix removed the internal CDT upper-casing of environment variables. As sutch all environment variables need to be get lowercased.

It may be that manual work is needed to change the project properties->C/C++ build make for existing projects. I didn't check that.
