### ISSUE TITLE
Current Stable Installation fails

### ISSUE THREAD

**Issue by pablo2000** [Sloeber/arduino-eclipse-plugin#1266]
Current stable release installs, but when the secondary installation start (when starting Sloeber for first time) the following error is generated:

Failed to configer Sloeber
Failed to install [DEPRECATED] Arduino mbed-enabled Boards
Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2".
Failed to download url http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2 error code is: 404

**Comment by jantje** [comment]
duplicate of #1264
