### ISSUE TITLE
Create new project with automatic indexing or sloeber.ino.cpp.o failed

### ISSUE THREAD

**Issue by KlausJoergensen** [Sloeber/arduino-eclipse-plugin#1304]
The problem comes with the last eclipse update.
Every time I open Eclipse and verify or upload a sketch to Uno or Mega this error is displayed:
subdir.mk:18: recipe for target 'sloeber.ino.cpp.o' failed
make: *** [sloeber.ino.cpp.o] Error 1

I found some tips and hints in the web, but nothing helped.
Preferences\Index unused headers checked or not checked.

Then I created a new Arduino Project with the Blink example.
The Indexer runs over all projects, all the red X in every project vanished and the error is gone.
Now I create a new project every time I started eclipse and it runs and runs.  

Eclipse Build id: 20201210-1552
Sloeber v4.3
Windows 10 64bit

Kindly regards
Klaus

**Comment by jantje** [comment]
Given #1263 I'm surprised it works at all.
Maybe consider testing 4.4 beta https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1290
