### ISSUE TITLE
The type 'BearSSL::WiFiClientSecure' must implement the inherited pure virtual method 'Print::write' 

### ISSUE THREAD

**Issue by OOHehir** [Sloeber/arduino-eclipse-plugin#1308]
Hello,

I'm working on BasicHTTPSClient.ino [https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino](url). It compiles & runs successfully in Arduino but in eclipse I'm getting the error:

The type 'BearSSL::WiFiClientSecure' must implement the inherited pure virtual method 'Print::write' 

Have you seen this before? I attach the setting

Thanks,

![Screenshot from 2021-02-27 14-16-55](https://user-images.githubusercontent.com/40183643/109389923-8bf84380-7906-11eb-977e-6728b6835ad5.png)

**Comment by jantje** [comment]
did you try to turn of warning in project properties->arduino->compile settings?

**Comment by OOHehir** [comment]
Apologies for raising this, yes a code based issue. I thought it had something to do with the program not running correctly but it's running now.

Many thanks for all your work by the way, great to have it integrated with eclipse!

Leo
