### ISSUE TITLE
ESP32 arduino library V1.0.5 compilation error, copy .CSV file path error.

### ISSUE THREAD

**Issue by LusterWong** [Sloeber/arduino-eclipse-plugin#1312]
Win10 LTSC
Sloeber for v4.3.3

The ESP32 library 1.0.5 is a recent release
Create a new project in selober and select library 1.0.5. Error message is as follows:
```
"F:\\software\\Sloeber\\arduinoPlugin\\tools\\make\\make" all 
F:/software/Sloeber/arduinoPlugin/tools/make/make --no-print-directory pre-build
cmd /c if exist "D:\App\New\partitions.csv" copy /y "D:\App\New\partitions.csv" "D:\App\New\Release\partitions.csv"
cmd /c if not exist "D:\App\New\Release\partitions.csv" copy "F:\software\Sloeber\/arduinoPlugin/packages/esp32/hardware/esp32/1.0.5\tools\partitionsmin_spiffs.csv" "D:\App\New\Release\partitions.csv"
```
Obviously, the path is wrong.  This glitch is a bit like #1210 , I described the problem there.
However, if you copy the relevant CSV file (e.g. min_spiffs.csv) to New\Release\ and rename it to "Partitions. CSV", the compilation will be successful !

In addition I tried to make all at D: App\New\Release\. It compiled successfully, but failed to generate bin. 

I don't know if it was Sloeber or v1.0.5 that caused the failure, because v1.0.4 is fine

**Comment by jantje** [comment]
For esp 1.0.5 you will need sloeber V4.4 currently in beta.
Please return to esp Versio 1.0.4 or join the beta testing https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1290
