### ISSUE TITLE
MacOS Big Sur: "failed to create the java virtual machine" 

### ISSUE THREAD

**Issue by SundialServices** [Sloeber/arduino-eclipse-plugin#1323]
Downloaded to MacOS Big Sur (latest: 11.2.3), removed the quarantine attribute, and tried to start the application by clicking on the icon.  Received an alert, "failed to create the Java virtual machine."

The Java version is the very latest one:  Version 8 Update 281, just downloaded from "java.com."

There is no prior version of Eclipse on this system.

**Comment by jantje** [comment]
Which Sloeber version?

**Comment by wimjongman** [comment]
Sloeber latest does not work with java 8. You have to install java 11 or higher.

try an open source download: https://adoptopenjdk.net/

**Comment by SundialServices** [comment]
The MacOS install page specifically says: "Sloeber *requires* Java **8**!  Other versions will not work!"

http://eclipse.baeyens.it/stable.php?OS=MacOS

If this is not the case, and if Sloeber needs something other than "what you get for MacOS from java.com," the instructions need to be updated accordingly.

Confirming now that installing OpenJDK-11 (LTS) from the above referenced site **did** resolve the problem.

**Comment by jantje** [comment]
Strange Latest Sloeber release is 4.3 and should work fine on Java8
Nightly and 4.4 (currently in beta) must have java 10 or bigger

I agree on the documentation issue so It should not be closed

**Comment by jantje** [comment]
updated web site
