### ISSUE TITLE
Release testing 4.4 test case 3. os:Win10 20H2 - success

### ISSUE THREAD

**Issue by SturmWolfgang** [Sloeber/arduino-eclipse-plugin#1327]
- using self built version (not an upgraded V4.3 version))
under Help/About Sloeber/Installation Details/ its 4.4.0.2021.03271019
- installed "darkest dark theme" from marketplace
- installed ESP8266 platform (2.7.4)
- pointed workspace to v4.3 workspace
- convert message appears 
- no errors of conversion process
- all my projects are closed except the current one - like before
- the current project is compiling fine and upload was successful, no issues so far
- on first compiling the indexer needs a rebuild - it showed errors - which were  gone after refreshing the indexer
- My Hardware is: Huzzah ESP8266
- I like the new option in the serial monitor to show the timestamp :-)
- a little bit surprising (positive of course) I found, that the location of my library path I did not need to reconfigure - the settings were taken over from V4.3 (maybe out of the workspace settings) - I mean the setting of "Private Library path" from the preference of the Arduino menu

**Comment by jantje** [comment]
Thanks for the feedback

>a little bit surprising (positive of course) I found, that the location of my library path I did not need to reconfigure - the settings were taken over from V4.3 (maybe out of the workspace settings) - I mean the setting of "Private Library path" from the preference of the Arduino menu

I think this is caused by oomph. I say so because there is no code in Sloeber to do this and oomph is build to do that.
FYI I'm not a fan of oomph as it breaks the encapsulation principle of object oriented design .
