### ISSUE TITLE
Release testing 4.4. os:Mac11.2.3 beta 4.4 - unexpected finishing installation

### ISSUE THREAD

**Issue by robzed** [Sloeber/arduino-eclipse-plugin#1329]
**Describe the bug**

I get this every launch

<img width="581" alt="image" src="https://user-images.githubusercontent.com/4871013/113561136-0863fd80-95fc-11eb-8c0f-541ebf92ac4d.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/4871013/113561325-4eb95c80-95fc-11eb-8881-c9e9aa4292e2.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Quit Sloeber and relaunch

**Expected behavior**
Doesn't show dialog after first launch

**Screenshots**
See above.

**Comment by jantje** [comment]
This is by design (F.I. download new json files)
If you click always run in background it will be less visible
