### ISSUE TITLE
Can't find private libraries

### ISSUE THREAD

**Issue by judge2005** [Sloeber/arduino-eclipse-plugin#1331]
The 'Import Arduino Libraries' dialog no longer lists any libraries in my private directory for any of my projects. I have no idea when this stopped working.

I deleted the path from the 'Private Library Path' section of the 'Arduino' preferences dialog and re-added it, but it doesn't help. I checked the 'Automatically import libraries based on includes', that doesn't help. I restarted eclipse - doesn't help. I moved the path to the top of the list - doesn't help.

 - OS: Windows 10
 - Eclipse:
Eclipse IDE for C/C++ Developers

Version: Photon Release (4.8.0)
Build id: 20180619-1200

Sloeber:
  Sloeber, the Eclipse Arduino IDE (plugin version)	4.3.1.201810101819	io.sloeber.feature.feature.group	Sloeber.io

**Comment by jantje** [comment]
as this is a really old Sloeber version it must be some config error or some incompatibility with a newer plugin

**Comment by judge2005** [comment]
Does 4.3.3 work with Eclipse Photon 4.8.0?

**Comment by jantje** [comment]
I honestly don't have a clue.

**Comment by judge2005** [comment]
OK. What version of Eclipse was it built for?

**Comment by judge2005** [comment]
It was the presence of a couple of .cpp and/or .h files in the library folder. e.g. if the library folder is mylibs, which has this structure:
```
mylibs
    \lib1
    \lib2
    afile.cpp
    afile.h
```

**Comment by jantje** [comment]
That may be the root cause". However that should mean mylibs is available as library.
