### ISSUE TITLE
Sorting of items in arduino section of project properties

### ISSUE THREAD

**Issue by weissen123** [Sloeber/arduino-eclipse-plugin#1336]
sorting of items in Arduino section of project properties is quite messy (e.g. sorted in a strange random way).
e.g. items in flash size (for esp8266 boards ver. 2.7.4) of Arduino properties are sorted like this:
<img width="434" alt="flash_size_sloeber" src="https://user-images.githubusercontent.com/32977465/115120079-df544d00-9fab-11eb-92cd-3156da8de232.png">

items of flash size in Arduino IDE are sorted in a nice logical way:
<img width="499" alt="flash_size_arduino_ide" src="https://user-images.githubusercontent.com/32977465/115120108-fd21b200-9fab-11eb-8fa6-1a6e15a2f124.png">

sorting of items in Arduino IDE corresponds to the sorting of items in boards.txt / boards.sloeber.txt. sorting of items in Arduino project properties in sloeber is therefore unexpected and inconvenient.

**Comment by jantje** [comment]
This is fixed now in V5
![image](https://github.com/user-attachments/assets/d0f7ec11-093b-455c-b51b-6a250f7eeef5)
