### ISSUE TITLE
Sloeber toolbar and menu disappear if I install subclipse

### ISSUE THREAD

**Issue by judge2005** [Sloeber/arduino-eclipse-plugin#1341]
Sloeber toolbar and menu disappear if I install subclipse

1. Download and unzip the windows zip from here: https://github.com/Sloeber/arduino-eclipse-plugin/releases/tag/V4_3_3
2. Run it and let it initialize (windows asks me if I want to trust it).
3. Select 'Install new software...' and add this repo: https://subclipse.github.io/updates/
4. Select everything but the maven support and install it.
5. Sloeber restarts and all the sloeber menu and toolbar items are gone.

**Comment by jantje** [comment]
Are you still in arduino perspective?

**Comment by judge2005** [comment]
Yes

**Comment by jantje** [comment]
I assume you are on Sloeber 4.3 and the update updated CDT to CDT10
Which cause hot issue #1263

**Comment by judge2005** [comment]
K. I’ll try and build a nightly...

**Comment by jantje** [comment]
Closing due to no response
Please reopen if not fixed
