### ISSUE TITLE
Release testing 4.4 test case 4.3 -> 4.4 Win10 (Use Alternative size command not reacting on Apply button, only Apply and Close works)

### ISSUE THREAD

**Issue by ArminJo** [Sloeber/arduino-eclipse-plugin#1343]
I checked Use Alternative size command, clicked Apply, switched tab to board selection and back and voila, **the box is unchecked again** 😞

**Comment by jantje** [comment]
Actually .... in my book, you should not even have to press apply before switching, the value should still be there.
Thanks for testing :-)

**Comment by ArminJo** [comment]
Thanks for developing this great tool 🥇 
I considered to switch my huge workspace to 4.4 so I made a few last test, but I think it is better to wait a bit.

**Comment by jantje** [comment]
>I considered to switch my huge workspace to 4.4 so I made a few last test, but I think it is better to wait a bit.

Thanks for doing the tests. And indeed waiting is better. There may be incompatibilities between beta releases.

**Comment by jantje** [comment]
This one seems fixed :-)
