### ISSUE TITLE
build fails for esp32 due to error in subdir.mk : path to compiler is missing

### ISSUE THREAD

**Issue by lvlerber** [Sloeber/arduino-eclipse-plugin#1345]
**Describe the bug**
The build stops at the first compile:
![image](https://user-images.githubusercontent.com/42242133/116588201-883f6800-a91b-11eb-9b49-5d03cd801a8d.png)
As you see the command in the subdir.mk is "/bin/xtensa-esp32-elf-gcc".  The complete path is missing and the cmd can't be executed in the shell.
![image](https://user-images.githubusercontent.com/42242133/116579405-a5bc0400-a912-11eb-9ebf-1613b5995691.png)

**To Reproduce**
1.  In arduino settings add this third party url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
2. In project arduino settings select platform esp32/2.0.0-alpha1 and board NodeMCU-32S
3. try to build your sketch'
4. 

provide the name of the board and the platform version you are using.  
ESP32 nodeMCU-32S

Provide the json url and a screenshot of project properties->arduino  
![image](https://user-images.githubusercontent.com/42242133/116579001-4100a980-a912-11eb-8308-9487cfbdb707.png)

**Expected behavior**
The .mk file should contain a correct compile command.  In the 1.6.0 version that is 
"C:\Apps\eclipse\arduinoPlugin\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-97-gc752ad5-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM .......(with many, many extra parameters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: w10
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
I know it is an alpha version, but 1.6.0 doesn't contain the core sources for - amongst others - esp_event.

**Comment by jantje** [comment]
Newer versions of ESP32 do not work on Sloeber V4.3
V4.4 is in beta and still has some issues

**Comment by gfvalvo** [comment]
I see this issue was closed. Is there now a Sloeber with support for latest ESP32 core?

**Comment by jantje** [comment]
Due to massive support; V4.4 is still in beta.
Issues are closed when "fixed" not when released. This is what the "fixed in nightly" tag is used for.
