### ISSUE TITLE
Serial monitor mixes all ports data

### ISSUE THREAD

**Issue by rribalta** [Sloeber/arduino-eclipse-plugin#1354]
Serial monitor mixes all ports data, it shows data received from all ports at the same time, not just the selected port.

**Comment by jantje** [comment]
Normal behaviour is:
Only show data from opened ports
Show data from each port in its own colour
The selected port in the serial monitor is the one you will act upon; like close or send data

Based on your description I would say: "as designed"

**Comment by rribalta** [comment]
You're right, I missed that each port can have its own color and I assumed it was a bug. I'm closing this issue. Thanks.
