### ISSUE TITLE
"bash" in the path conflicting with the external builder

### ISSUE THREAD

**Issue by elgui** [Sloeber/arduino-eclipse-plugin#1363]
No successful build (blink included).
This has been reported ( #472), then closed as fixed since 4.0

At launch :
"eclipse.buildId=unknown
java.fullversion=11.0.10+9
JRE 11 Windows 8 amd64-64-Bit Compressed References 20210120_899 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 0a86953833 based on jdk-11.0.10+9
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -perspective io.sloeber.application.perspective
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -perspective io.sloeber.application.perspective
it.baeyens.arduino.core

we have found programs in the path that might conflict with our external builder.
The conflicting programs are bash.
The program might still function but if you get strange build errors you know where to look

**Comment by jantje** [comment]
Given I see "it.baeyens.arduino.core' in the dump.
Which version of sloeber are you using?

**Comment by elgui** [comment]
I just downloaded 4.4.0

**Comment by elgui** [comment]
reinstalled, all good...
