### ISSUE TITLE
Build issue with Arduino Nano 33 IOT

### ISSUE THREAD

**Issue by pbd9608** [Sloeber/arduino-eclipse-plugin#1379]
I have been working with the Arduino IDE and decided to branch out to a new tool.  I found Sloeber, installed it and tried it first on the Blink project with an Arduino Uno board.  It worked well with that board.  I am working a project with the Arduino Nano 33 IOT board and tried the example SerialCallResponse example and I am getting a Build Error:

C:\Users\...\AppData\Local\Temp\ccDaToI4.s:1446: Error: selected processor does not support `mrc p15,0,r2,c12,c1,0' in Thumb mode
make: *** [core\core\USB\subdir.mk:30: core\core\USB\CDC.cpp.o] Error 1

I am not sure where to even go look for this problem.

**Comment by jantje** [comment]
Works fine here
![afbeelding](https://user-images.githubusercontent.com/1175841/132137909-9342aa14-3675-4b13-80d1-e1060b3d0d5a.png)

When I see

>C:\Users...\AppData\Local\Temp\ccDaToI4.s

And as I know Sloeber normally does not do anything outside of the folder it is installed and the workspace folder selected at the start (unless you use version control which uses liks to you version control folders)
So I think there is a problem with you setup.
A couple of screenshots would get us a long way.
Here are my project properties
![afbeelding](https://user-images.githubusercontent.com/1175841/132137955-66137034-dd2b-4f68-a815-bf4fe10897a2.png)
Here my arduino preferences
![afbeelding](https://user-images.githubusercontent.com/1175841/132137974-96f1bde7-90b6-464b-9cb7-32a96ffba061.png)
And my boardsmanager
![afbeelding](https://user-images.githubusercontent.com/1175841/132137986-7fe17e1b-ab1b-4a9c-8941-1f0146993bcc.png)

If you can upload the screenshots of these settings on your system we can take a deeper look

**Comment by jantje** [comment]
FYI the upload protocol on my setting in the project properties is empty because I tested on the nightly which works differently for upload.
Normal in latest release V4.4.0 is to have default

**Comment by pbd9608** [comment]
![image](https://user-images.githubusercontent.com/90148439/132256828-8777c901-5e04-4c5d-97b8-33bd47fa19fb.png)
![image](https://user-images.githubusercontent.com/90148439/132256971-fda20e33-514e-4eeb-990d-c17f8d33c899.png)
![image](https://user-images.githubusercontent.com/90148439/132257296-c0bd6181-7dde-425e-abac-765fec42546c.png)

**Comment by pbd9608** [comment]
thank you  for the quick response.  Would it be good to remove and reinstall?

**Comment by jantje** [comment]
This all looks good. 
I see no reason why reinstall of sloeber is needed. Maybe reinstall of the samd platform could fix the issue but I doubt that for the problem at hand.
Can you provide an expanded view from the project like below?
![afbeelding](https://user-images.githubusercontent.com/1175841/132260019-8b79b645-1981-410f-bba7-892b13154898.png)
note that examples is under libraries which should not be the case. I'll make a issue for that problem.

And the build log in a file?

**Comment by pbd9608** [comment]
![image](https://user-images.githubusercontent.com/90148439/132260654-3a7b771a-3fba-437c-a077-644236938d48.png)

**Comment by jantje** [comment]
This project view seems to be fine
The malformed url's in the error log should not be there
Can you provide 
![afbeelding](https://user-images.githubusercontent.com/1175841/132262527-c0741dcb-e066-4554-94ff-72a9b5690529.png)
And please the content of the console for the build log in a file

**Comment by pbd9608** [comment]
![image](https://user-images.githubusercontent.com/90148439/132263007-2da09b7e-425e-4292-bbb4-99d5e16f2713.png)

**Comment by pbd9608** [comment]
[Console content.docx](https://github.com/Sloeber/arduino-eclipse-plugin/files/7117928/Console.content.docx)

**Comment by jantje** [comment]
I don't know why you added the last line to the third party index url's
That may cause problems, at least it should remove the malformed format messages in the error log

**Comment by jantje** [comment]
I have no clue whatsoever is going on on your system.
You say the default sketch works fine but this example not.
This seems contradictory with the fact that the file that fails compiling must be compiled for both the project and with the same compile instructions. As this file is linked it is the exact same file and the command should be the exact same for both projects and is basically the same as on my system (I only see a swap of 2 include paths which I think is acceptable)

It is also strange that there is no red square with a cross on the 2 core folders here as the failing file is in those folders https://github.com/Sloeber/arduino-eclipse-plugin/issues/1379#issuecomment-913854473

Also the error message does not relate back to the cpp file and is marked as an assembler error in ccDaToI4.s

In my setup I failed to find any references to ccDaToI4.s

Somewhere somehow something on your system is wierd and causing problems. I would propose to start from a new sloeber install and document all the steps taken.

**Comment by pbd9608** [comment]
> I don't know why you added the last line to the third party index url's
> That may cause problems, at least it should remove the malformed format messages in the error log
The area to choose the microcontroller had boxes that I assumed were check boxes and they would not respond, so I tried to add the Arduino .json file.  I then figured out that the text was a folder that would open when selected.

**Comment by pbd9608** [comment]
> I have no clue whatsoever is going on on your system.
> You say the default sketch works fine but this example not.
> This seems contradictory with the fact that the file that fails compiling must be compiled for both the project and with the same compile instructions. As this file is linked it is the exact same file and the command should be the exact same for both projects and is basically the same as on my system (I only see a swap of 2 include paths which I think is acceptable)
> 
> It is also strange that there is no red square with a cross on the 2 core folders here as the failing file is in those folders [#1379 (comment)](https://github.com/Sloeber/arduino-eclipse-plugin/issues/1379#issuecomment-913854473)
> 
> Also the error message does not relate back to the cpp file and is marked as an assembler error in ccDaToI4.s
> 
> In my setup I failed to find any references to ccDaToI4.s
> 
> Somewhere somehow something on your system is wierd and causing problems. I would propose to start from a new sloeber install and document all the steps taken.

I was beginning to think a re-install would be the best way to attack this. 

From your comments below, the Blink project worked on an UNO board.  When I went to the Nano board, I changed to a project that would give me a serial output so that I could verify the serial ports were working.

I will delete and reinstall Sloeber, but it may be next week before I can get to it.  I will let you know how it goes.

Thank you for the help and insight.

Paul

**Comment by jantje** [comment]
It has been a while now.
Do you have a update?
