### ISSUE TITLE
When creating a project based on an example the example folder is in the libraries folder

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#1380]
Sloeber 4.4 nightly
When working for issue #1379 I noticed that a new project created based on an example has the example folder in libraries.
![afbeelding](https://user-images.githubusercontent.com/1175841/132260160-15ee383a-a089-40d6-959b-755d15f375db.png)
In this case this will not cause issues but it should not be there
Simply deleting should do the trick

**Comment by pbd9608** [comment]
I don't understand,  What are you asking me to delete?

I thought that is where you put projects or the includes did not work correctly.

**Comment by jantje** [comment]
The libraries/examples folder should not be there. You can safely delete it.
In this case it is not needed as the project does not contain troublesome files (ino is only processed if it is in the project root)
