### ISSUE TITLE
makefiles are recreated every time a build is started

### ISSUE THREAD

**Issue by ArminJo** [Sloeber/arduino-eclipse-plugin#1397]
Every time I start a new build, all makefiles are recreated. This takes a few seconds - for nothing 😞 
![makefilebuildInSloeber](https://user-images.githubusercontent.com/3881884/137710278-ecdc86d4-8ccc-4480-a756-3aace247cf12.jpg)
I cross checked it with the AVR Eclipse plugin, it does not recreate the makefiles!
What is the trigger for this recreation and how can I avoid it?
Thanks
Armin

**Comment by jantje** [comment]
>I may have shortcut the complex partial update code to simple always generate everything

I have shortcut the complex partial update code to simple always generate everything.
So this behaviour has been in Sloeber for a very long time.
I'm not really feeling confident nor eager to fix this as I think this whole makefile generation should be done differently but it works so ....
