### ISSUE TITLE
degree symbol bug

### ISSUE THREAD

**Issue by neorob85** [Sloeber/arduino-eclipse-plugin#1401]
I'm using sloeber 4.4 on windows 10 to program a esp8266 (nodemcu) with latest arduino libraries (pubsubclient 2.8.0 and esp8266 platform 3.0.2).

Take this instruction:

```
  mqttclient.publish("topic", "symbol °C");

```

If it's compiled with arduinoIDE or platformIO, everything works on the right way.
On the contrary if it's compiled with sloeber, is trasmitted the weird "ef bf bd" character instead of the right degree symbol (c2 b0)

Any idea how to resolve it?

**Comment by jantje** [comment]
This is probably related to the file format setup in eclipse.
If you select a file and right click it select properties->resource you can see the type of file that is used
![afbeelding](https://user-images.githubusercontent.com/1175841/139753644-cd2d3f88-f641-4b04-af1b-765eb54cf82b.png)
Most likely that will be CP1215 inherited from the workspace. You can change the workspace settings in windows->preferences->general->workspace
![afbeelding](https://user-images.githubusercontent.com/1175841/139753784-03cffc99-bb3c-4c00-86cf-3207c8585520.png)

**Comment by neorob85** [comment]
I set up "Text file encoding" from "Cp1252" to "UTF-8" and now seems working as expected.
Thankyou @jantje ! :)

**Comment by jantje** [comment]
I labelled this as a known limitation but basically the problem is that eclipse has plenty of file encoding options to store files so you have to set the file encoding to a toolchain "supported" value.
So basically it is a known limitation because eclipse is over qualified 😮
