### ISSUE TITLE
board jsons not parsing

### ISSUE THREAD

**Issue by MangyDogUK** [Sloeber/arduino-eclipse-plugin#1403]
![image](https://user-images.githubusercontent.com/35331819/140171405-e217941f-e4b1-47ef-bf9a-69ea786678a9.png)

Running latest sloeber...
been having a nightmare getting it to install on a fresh windows install, with JDK installed.

**Comment by MangyDogUK** [comment]
Sorry for not the great bug report... im really tired from loads of system rebuilding over the last few days... This is the last thing to get working.

**Comment by jantje** [comment]
Do you have the log file? Seems very similar to #1384

**Comment by MangyDogUK** [comment]
[error.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/7471270/error.log)

**Comment by MangyDogUK** [comment]
Adding --illegal-access=permit to eclipse ini didnt work.

**Comment by jantje** [comment]
According to the log you are on java 17 so parsing json files is not going to work.Which is confirmed by the loggings
```
!ENTRY io.sloeber.core 4 0 2021-10-31 23:17:51.186
!MESSAGE Failed to parse json file "G:\embedcpp-2021-09\eclipse\arduinoPlugin\package_index.json"
!STACK 0
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @13140c17
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
```
It can be the workaround no longer works in java17.

I also see `java.io.IOException: Unable to resolve plug-in "io.sloeber.application".` which basically says your install is not ok.

**Comment by MangyDogUK** [comment]
OK, its not ok :D so what do i need to do to get it working... as the usual methods dont seem to be working.

**Comment by jantje** [comment]
use java 11

**Comment by MangyDogUK** [comment]
![image](https://user-images.githubusercontent.com/35331819/140553952-4719dee0-b441-49d8-9a20-db04a7641032.png)

still getting this after removing JDK17 and installing 11...

**Comment by MangyDogUK** [comment]
[error.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/7487916/error.log)
fresh install fresh workspace

**Comment by jantje** [comment]
How do you install?

**Comment by MangyDogUK** [comment]
Downloaded latest eclipse from eclipse.... Selected the embedded option as I use some of the tools it come with.
Then i go to the market place and install sloeber from there.

I have also tried installing via install new software and the link off your site.

**Comment by jantje** [comment]
The marketplace install on latest eclipse will hit #1361
We do not support this path as it is very error prone.
FYI Part of CDT embedded is (and has been for a long time) in Sloeber

>I have also tried installing via install new software and the link off your site.

I do not understand what you mean with that statement
Here is where you should be http://eclipse.baeyens.it/stable.php?OS=Windows
or you can go directly to the releases here on github https://github.com/Sloeber/arduino-eclipse-plugin/releases

**Comment by MangyDogUK** [comment]
![image](https://user-images.githubusercontent.com/35331819/140586332-81369591-4a10-40af-9ed8-a81015486ddc.png)
installed via the install new software.... And getting that again.

**Comment by jantje** [comment]
You need java 11

**Comment by MangyDogUK** [comment]
JAVA11 is installed  Sent from Mail for Windows From: jantjeSent: 05 November 2021 22:46To: Sloeber/arduino-eclipse-pluginCc: MangyDogUK; AuthorSubject: Re: [Sloeber/arduino-eclipse-plugin] board jsons not parsing (Issue #1403) You need java 11—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jantje** [comment]
please provide error log

**Comment by MangyDogUK** [comment]
[error.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/7489359/error.log)

**Comment by MangyDogUK** [comment]
looking at the log it says java 16, but i did install jdk 11

**Comment by jantje** [comment]
As I said it is using java 16. 
You can modify the sloeber.ini to point to the java you want it to use
```
-vm
C:/Program Files/Java/jdk-11.0.4/bin/javaw.exe
```
By the way ... you are not using the product as that comes with a compatible java

**Comment by MangyDogUK** [comment]
i think its already set
![image](https://user-images.githubusercontent.com/35331819/140591279-60896af0-8fe0-4c8f-94c7-3f7ae5ea1552.png)

**Comment by MangyDogUK** [comment]
oh wait i see it now

**Comment by MangyDogUK** [comment]
seems to be working now

**Comment by uzi18** [comment]
@MangyDogUK what is your solution?
