### ISSUE TITLE
When creating a workspace, the log always shows 7 errors （v4.4）

### ISSUE THREAD

**Issue by LusterWong** [Sloeber/arduino-eclipse-plugin#1405]
Win10 LTSC
Sloeber for v4.3.3

I created a new workspace, and without adding any files, the error will be displayed in the log.
If you close workspace and open it again, the same error will be displayed.
[err.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/7513667/err.log)

Another problem, if the network connection fails, opening sloeber always shows sit back....wait install until forever...
It cannot be used without network. Can I disable this installation process?

**Comment by jantje** [comment]
The loggings are from mylyn. The mylyn project has resource issues reduced quality. 
Mylyn was removed from Sloeber.
https://github.com/Sloeber/arduino-eclipse-plugin/commit/095a77fc8943ed1528459cdc91b7ecf410616fec

**Comment by LusterWong** [comment]
> The loggings are from mylyn. The mylyn project has resource issues reduced quality. Mylyn was removed from Sloeber. [095a77f](https://github.com/Sloeber/arduino-eclipse-plugin/commit/095a77fc8943ed1528459cdc91b7ecf410616fec)

How do I remove it manually in the latest 4.4 release?

In addition, Is there a solution for offline use?

Thank you.^^

**Comment by jantje** [comment]
>How do I remove it manually in the latest 4.4 release?

I don't know

>In addition, Is there a solution for offline use?

I do not understand your question

**Comment by LusterWong** [comment]
> > How do I remove it manually in the latest 4.4 release?
> 
> I don't know
> 
> > In addition, Is there a solution for offline use?
> 
> I do not understand your question

Using a PC without an Internet connection, open Sloeber was always prompted to wait for installation every time he started it
![e571bf5581264e4af585c7156c76e67](https://user-images.githubusercontent.com/56709609/142427364-6ac9b5ec-bb76-4ade-a16d-ca7d486eb68f.png)
.
Opening Sloeber will prompt you to wait for the download if the project has already been created.
When the network fails, Sloeber will be unavailable. How can I resolve this situation?
Thank you.

**Comment by jantje** [comment]
Sloeber contacts the internet during updates/finishes the installation because you ask to do so
![afbeelding](https://user-images.githubusercontent.com/1175841/142490124-6c3c9048-d8b7-4f9b-a91a-03206cd56bdd.png)
Sloeber also checks your local network for boards. You can disable that
![afbeelding](https://user-images.githubusercontent.com/1175841/142490333-c625a9c1-5f5e-40cd-a389-aa90dda58094.png)
With these 2 options disabled sloeber should not need network access to work properly

**Comment by LusterWong** [comment]
> Sloeber contacts the internet during updates/finishes the installation because you ask to do so ![afbeelding](https://user-images.githubusercontent.com/1175841/142490124-6c3c9048-d8b7-4f9b-a91a-03206cd56bdd.png) Sloeber also checks your local network for boards. You can disable that ![afbeelding](https://user-images.githubusercontent.com/1175841/142490333-c625a9c1-5f5e-40cd-a389-aa90dda58094.png) With these 2 options disabled sloeber should not need network access to work properly

That's great. That'll solve the problem~~
But now there's a new problem, create new workspace and project, compile error use V4.4
![1637333659(1)](https://user-images.githubusercontent.com/56709609/142643518-5fe73e24-bf9a-4000-8f0d-4b7d83314617.png)
.
But the files exist in \Sloeber_440\arduinoPlugin\tools\make\make.exe

**Comment by jantje** [comment]
I have never seen this before. Probably something went wrong with extracting the zip file
Stop sloeber
delete the \Sloeber_440\arduinoPlugin\tools\make folder
start sloeber
try again

**Comment by LusterWong** [comment]
> 

I seem to have found the cause, not the "make" problem
![ss](https://user-images.githubusercontent.com/56709609/142755632-5d2cbe0c-e8d3-4a56-9263-a036bb97a22c.gif)
The automatically generated Makefile path resolution error.  That "ESP32?WROVER?E" The right is “ESP32-WROVER-E”.

**Comment by jantje** [comment]
There have been reports of problems with the - character but they have never been solved/reproducible.
As you can see in your case there are multiple - characters in you path but only 2 are replaced.
As far as I understand your setup (and sloeber) there is no reason to have a different treatment for the - in the 2 parents of ESP32-WROVER-E as they are all parents of the workspace folder Sloeber_440
So I expect the - characters in ESP32-WROVER-E not to be the same - character as in GT-1234M
A dash, minus and hyphen all look very alike but are different characters

**Comment by wimjongman** [comment]
Maybe set explicit encoding in the project properties?

![image](https://user-images.githubusercontent.com/180969/142843435-25ef4793-a865-43fd-b348-eebed6fe5ad5.png)

**Comment by LusterWong** [comment]
> Maybe set explicit encoding in the project properties?
> 
![22](https://user-images.githubusercontent.com/56709609/143036045-4ddab98d-157e-4375-8965-6a32d12fe204.gif)
After changing the encoding to UTF-8, the Makefile resolves correctly, but still fails to compile.
For now I only use a simpler path to solve the problem temporarily.

**Comment by jantje** [comment]
IMHO the characters are not simple hyphens. By making the project UTF-8 the characters are cast to simple hyphens but that makes they do not match the actual name so the file is not found.
As Sloeber only uses standard java and eclipse methods on the workspace path and sloeber home I consider this not a sloeber problem but a java/eclipse problem
If I were you I would rename ESP32-WROVER-E to make sure the hyphens are hyphens to solve the issue
