### ISSUE TITLE
Sloeber plug-in will not install in Eclipse

### ISSUE THREAD

**Issue by Catephatic** [Sloeber/arduino-eclipse-plugin#1415]
I have Eclipse 2021-09 (4.21.0) Build Id 20210910-1417 installed and when I attempt to install the Sloeber plug-in via Marketplace (or Install new software) it downloads files and gets just past the Review Licences stage where I get a box "Installing software has encountered a problem" and when I click on Details, I get the following:
An error occurred while collecting items to be installed
session context was:(profile=C__Users_Dell_eclipse_cpp-2021-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.nebula.cwt,1.1.0.202011020719
No repository found containing: osgi.bundle,org.eclipse.nebula.widgets.cdatetime,1.5.0.202011020719
No repository found containing: osgi.bundle,org.hamcrest.core,1.3.0.v20180420-1519
No repository found containing: osgi.bundle,org.junit,4.13.0.v20200204-1500

Any help would be much appreciated.

**Comment by jantje** [comment]
duplicate #1361
