### ISSUE TITLE
Nightly - Project settings are not persistent / written to .sproject

### ISSUE THREAD

**Issue by ArminJo** [Sloeber/arduino-eclipse-plugin#1441]
This is my current version: 
 Sloeber, the Eclipse Arduino IDE (plugin version)	4.4.1.202201260122	io.sloeber.feature.feature.group	Sloeber.io

.sproject is not changed, not even on closing project, so after re opening all changes (naturally) are lost.
But manual editing works as expected.
Addin a new configuration also failed.

**Comment by ArminJo** [comment]
Restaring Sloeber 2 times helped. Until next time.. (I had the error 3 times in the last 2 days)

**Comment by jantje** [comment]
How do you change .sproject? I mean you should not change .sproject manually. That should not have effect.
You could change .sproject when the project is closed and then on open the changes should be taken into account but this is not a supported/adviced way of working.

**Comment by ArminJo** [comment]
> You could change .sproject when the project is closed

That the way I do it always 😀

**Comment by jantje** [comment]
>That the way I do it always 😀

But you should not modify .sproject files by hand. This is not a supported scenario.

If you want to change the config in text format goto project properties->sloeber->other and check "share in version control" for all configs you want to edit.
You should now have a sloeber.cfg file (which is a subset of the .sproject file).
As to spec (there will be bugs) you can change this file whenever you want and the changes should be taken into account.
