### ISSUE TITLE
Arduino mega 2560 not recognized in IDE

### ISSUE THREAD

**Issue by Herb01** [Sloeber/arduino-eclipse-plugin#1455]
I'm trying to create a project in Sloeber which uses Arduino mega 2560 timers 3, 4 and 5. Also i tried to use port PL, The project is compiling well in the Arduino IDE but Sloeber complains with red underline on counters above counter 2. It looks like it don't recognize the mega. In the project Arduin 2560 is selected.

**Comment by uzi18** [comment]
Screenshots please. What is Your Sloeber version?
