### ISSUE TITLE
Replace httpclient45 with httpclient5

### ISSUE THREAD

**Issue by wimjongman** [Sloeber/arduino-eclipse-plugin#1456]
As mentioned in issue  #1396 we can't use httpclient45 anymore. It has been replaced by httpclient5.

**Comment by jantje** [comment]
Thanks Wim :-)

**Comment by wimjongman** [comment]
Got your back brother ;)

**Comment by jantje** [comment]
You just made me very happy :-D

**Comment by hreintke** [comment]
Works here also.
Thanks.
