### ISSUE TITLE
Importing old projects without .project file makes sloeber hang

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#1458]
Hi,
Running Windows 10, Sloeber git-master

I have some projects in a previously used workspace which do not (yet) have a .sproject file.
When importing these in a "new workspace" Sloeber/Eclipse doesn't finish but "hangs".

Looking in the .log I cannot find anything specific, although I occasionally see deadlock messages.
I have to kill sloeber to get running again.

After that restart, I see the project in the workspace file location on disk, without a .project file.
But the project doesn't show up in the project explorer in eclipse.

I importing old projects supported ? If not what would be the correct procedure ?

Edit : 
The way I can import is : 
- Copy the project directory to the new workspace
- Import the project with  "Projects from Folder or Archive"
- Set Sloeber properties (board and options)

**Comment by jantje** [comment]
Project conversion old to new is hard to test. The hanging has been reported and then was gone.
If the auto convert doesn't work I would remove all configuration files (.project, .sproject .settings/* ..)
Import the project as a standard project and then convert it to a sloeber project.
