### ISSUE TITLE
Failure during Eclipse startup, "Unable to make field private final..."

### ISSUE THREAD

**Issue by cabintech** [Sloeber/arduino-eclipse-plugin#1460]
Environment:
- Newly installed Eclipse (2022-03) for Java EE (required for other projects)
- Newly installed CDT plugin for C++ tooling
- Newly installed Sloeber plugin via the Marketplace
- Windows 10

During Eclipse startup it fails to read 3 JSON files with the message:
```
Failed to parse json file "M:\arduinoPlugin\package_index.json"
Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @e1fba9a
```

I did both of the recommendations in issue 705 (run eclipse.exe from a short path via a BAT file, and set windows policy to allow long path names). This does not seem like a path length issue and I could find no other reports of a problem like this.

**Comment by cabintech** [comment]
Ha, OK. Maybe that is a ridiculously obscure message for "file not found". There is no such file at that location. I guess this does not work 'out of the box', 

I am having a hard time finding out exactly how to get boards defined... some instructions say "do it just like the Arduino IDE"... but my Arduino IDE directory does not have those missing files either. This page (http://eclipse.baeyens.it/how_to.shtml#/h) seems out of date because that is not what the Preferences->Arduino settings look like. It shows how to pick a board from the list, but not how to get the list in the first place.

Any help or pointers to how to get this configured and working would be appreciated...

**Comment by cabintech** [comment]
Downloaded package_index.json from https://downloads.arduino.cc/packages/package_index.json and put it into the arduinoPlugin directory.

Same error on startup, and it then deletes the file. Ugh. I don't get how this is supposed to work...

**Comment by cabintech** [comment]
Gave up on the plugin. Downloaded the full integrated Sloeber package. At least it starts properly configured, except...

I am using a Teensy 3.2 board and I cannot get Sloeber configured for it. I added a private hardware path to my existing Arduino IDE "hardware" directory but it does not show up in the board list. 

![image](https://user-images.githubusercontent.com/31935300/161133674-3aa8241c-6725-4b2f-a183-f4338a7a6ea3.png)

![image](https://user-images.githubusercontent.com/31935300/161133322-ec1e02ca-b31b-4976-8bd0-09d742858388.png)

![image](https://user-images.githubusercontent.com/31935300/161133776-109ff733-8a99-45cc-a9f1-80f6bebd49be.png)

Also tried specifying the teensy subdir, and the teensy/avr subdir but still no change in the board list.

**Comment by jantje** [comment]
Stuff added to the private hardware is not managed by the boardsmanager so it should not show up anywhere in the preferences.
It should only be visible in the project properties->sloeber (used to be arduino)

Your original issues are related to java disabling reflection making reading json files (on which the arduino framework relies heavily) failing. Bad json files are deleted by Sloeber as they are unusable. However in this case that makes the behaviour hard to understand.

**Comment by jantje** [comment]
I think this issue can be close. pease reopen if you think this issue is not "fixed" ad explain why you think so
