### ISSUE TITLE
The compilation of SoftwareSerial.h Library of esp32 failed.

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1468]
I can compile successfully in Arduino ide.
![image](https://user-images.githubusercontent.com/75734559/169385704-b785af0f-e002-41db-90e9-53e9bf725853.png)

**Comment by xiezhoubin** [comment]
However, an error will be reported in sloeber, indicating that the library file cannot be found. The library path has been added correctly, because I have tried other libraries in the library path and can compile successfully, but the library "SerialwareSerial.h" cannot.
The link to this library is：https://github.com/dok-net/espsoftwareserial
![image](https://user-images.githubusercontent.com/75734559/169385881-bd9e9d42-d255-4004-a333-001eed74da6f.png)
![image](https://user-images.githubusercontent.com/75734559/169386450-c742907b-4276-4b97-9f52-cc46f660000e.png)

**Comment by jantje** [comment]
There are changes in this area in the nightly. Please try with the current nightly which you can find here
https://github.com/Sloeber/arduino-eclipse-plugin/actions/runs/2287689867

**Comment by xiezhoubin** [comment]
What does this operation mean? I don't quite understand. Can you solve the compilation error problem?

**Comment by jantje** [comment]
Did you check wether softwareserial is in the libraries folder in your project?
If not; did you try to add it via the menu: add library to project?
