### ISSUE TITLE
Esp8266 compilation error

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1470]
![image](https://user-images.githubusercontent.com/75734559/169480654-51b8d794-5aef-44e7-8597-53654dd63efb.png)
![image](https://user-images.githubusercontent.com/75734559/169480718-7d3df7bf-3ab8-445d-b25e-90bfae0bb054.png)

**Comment by jantje** [comment]
This error is not a failed build.
Please provide the console output for failed builds
