### ISSUE TITLE
Failed to compile after renaming the project folder name!

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1471]
Before change.
![$@N_IG2K5ZTDRX3KYD_2GQ5](https://user-images.githubusercontent.com/75734559/169642936-98253f00-f994-46e8-9498-b7446ac8860a.png)

After change.
![7AQF8D~O2P$P{XJ`$3253 S](https://user-images.githubusercontent.com/75734559/169642951-ba82e971-8037-46d3-bd26-ef7f4caa6e92.png)

Change the name of the ino file to match the name of the project folder.
![KXY(74Y9QCK$)81JZH{E8W0](https://user-images.githubusercontent.com/75734559/169642969-31cdfbc3-ace6-4c6f-9dcd-646914dd5299.png)

Re open the software, but there is still a compilation error.
![FU(}C9KXKLTH@44(Y%FMVSR](https://user-images.githubusercontent.com/75734559/169643011-cc79db11-9208-4459-b54b-68cdc54b3a0e.png)

**Comment by xiezhoubin** [comment]
ide version
![image](https://user-images.githubusercontent.com/75734559/169643696-20f0c8c3-0fb0-4030-af93-bb1fc9e615be.png)

**Comment by jantje** [comment]
did you go to project properties->sloeber and select apply and close?

**Comment by xiezhoubin** [comment]
Still report an error. You try that too?
![image](https://user-images.githubusercontent.com/75734559/169651419-c262876d-a976-43e9-b8fd-45312f2ff3c0.png)
![image](https://user-images.githubusercontent.com/75734559/169651433-09c965f8-d9cf-4f4d-9737-8776c86907ad.png)

**Comment by xiezhoubin** [comment]
I tried to change the name of the project folder back to the original name, and the compilation can pass again.
