### ISSUE TITLE
If I want to add "build_flags", what should I do? just like in platformio.

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1473]
![image](https://user-images.githubusercontent.com/75734559/169661917-3bee5adf-f874-4379-9267-36316d6eaa8c.png)
![image](https://user-images.githubusercontent.com/75734559/169661939-a2303a06-11ab-4b23-abda-155d0d855c70.png)
![image](https://user-images.githubusercontent.com/75734559/169661999-1ab4615d-9ccf-4cfd-8c5f-a8979cfc8c08.png)

**Comment by xiezhoubin** [comment]
I seem to have found it, but how can I add multiple "build_flags"?

![image](https://user-images.githubusercontent.com/75734559/169689808-7373a7ce-bca2-4efc-94a1-83b7d4ad2d42.png)

**Comment by xiezhoubin** [comment]
If I do this, I will save an error. What's the reason?
![image](https://user-images.githubusercontent.com/75734559/169690024-0ddf83c8-a705-4595-bdc6-2ad744a0d287.png)
![image](https://user-images.githubusercontent.com/75734559/169690046-d09e403f-caab-4294-b742-e387f401f46a.png)

**Comment by erdemuncuoglu** [comment]
If this helps...
![2022-05-22_15-48](https://user-images.githubusercontent.com/4586452/169696001-635868d1-998d-465c-a21a-9595cce1cdc0.png)

**Comment by xiezhoubin** [comment]
> 如果这有帮助... ![2022-05-22_15-48](https://user-images.githubusercontent.com/4586452/169696001-635868d1-998d-465c-a21a-9595cce1cdc0.png)

I have found it, but how can I add multiple "build_flags"?

**Comment by erdemuncuoglu** [comment]
Like doing on command line. 
```-D TEST_FLAG -D OTHER_FLAG```

**Comment by xiezhoubin** [comment]
> 就像在命令行上做的一样。 `-D TEST_FLAG -D OTHER_FLAG`

Single can.
![image](https://user-images.githubusercontent.com/75734559/169698016-2be0d11d-c957-4345-b0d8-532c5495fe98.png)

Two will report a lot of mistakes.
![image](https://user-images.githubusercontent.com/75734559/169698060-138809ec-196f-41c3-b802-fb43ae9d7f25.png)

**Comment by erdemuncuoglu** [comment]
```-D a=1``` may conflict with default ones. Try this? ```-D _a=1``` or any longer name.

**Comment by xiezhoubin** [comment]
> `-D a=1`可能与默认的冲突。试试这个？`-D _a=1`或任何其他名称。

succeed. Thank you.

**Comment by xiezhoubin** [comment]
> 如果我这样做，我将保存一个错误。什么原因？ ![图片](https://user-images.githubusercontent.com/75734559/169690024-0ddf83c8-a705-4595-bdc6-2ad744a0d287.png) ![图片](https://user-images.githubusercontent.com/75734559/169690046-d09e403f-caab-4294-b742-e387f401f46a.png)

Can this problem be solved?

**Comment by xiezhoubin** [comment]
![image](https://user-images.githubusercontent.com/75734559/169698544-183a8fa2-bb83-4a44-8276-953029997a32.png)
![image](https://user-images.githubusercontent.com/75734559/169698562-73b312bd-4b67-44f0-91cf-be3a15257cfd.png)

**Comment by jantje** [comment]
>Can this problem be solved?

only if we get a java stacktrace or are able to reproduce the issue.

**Comment by xiezhoubin** [comment]
> ![图片](https://user-images.githubusercontent.com/75734559/169698544-183a8fa2-bb83-4a44-8276-953029997a32.png) ![图片](https://user-images.githubusercontent.com/75734559/169698562-73b312bd-4b67-44f0-91cf-be3a15257cfd.png)


If "testa==1" can be saved.
![image](https://user-images.githubusercontent.com/75734559/169698637-9482b1de-e566-4d66-b34a-9104dfede595.png)

**Comment by xiezhoubin** [comment]
> > 这个问题能解决吗？
> 
> 仅当我们获得 java stacktrace 或能够重现该问题时。

You can try. It's easy to try to reproduce.

**Comment by jantje** [comment]
As I have never seen this I would say it is not easy to reproduce
You can try to provide the stacktrace, it is easy, it should be in the eclipse log file.
https://wiki.eclipse.org/FAQ_Where_can_I_find_that_elusive_.log_file%3F

**Comment by erdemuncuoglu** [comment]
BTW I tried it with ESP8266 and it ran smoothly even I could see the warning message in console.
Platform: 
 - Eclipse  : 4.23.0.I20220308-0310
 - Sloeber : nightly plugin 4.4.1.202205080021

**Comment by jantje** [comment]
As this is a open source project only supported by volunteers I would really appreciate you to get the stacktrace.
This way:
1) We improve the quality of sloeber
2) other people do not have to go through this 
3) I do not have to go through another issue.

I have been helping you so I would appreciate you helping me by trying to provide a stack trace so I can investigate/fix the issue at hand.
