### ISSUE TITLE
Cannot create a project from a custom code template file.

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1474]
![image](https://user-images.githubusercontent.com/75734559/169676268-35dbf8b8-98a6-4fe2-81d5-a6b259f2cbe5.png)

**Comment by jantje** [comment]
Not sure what you are trying to do but I think you missed this
![afbeelding](https://user-images.githubusercontent.com/1175841/169808101-125c21d0-67dc-495b-a615-df59614be825.png)

**Comment by xiezhoubin** [comment]
ok
