### ISSUE TITLE
Can I set the default encoding to "UTF-8"

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1477]
Every time I create a new project, I need to change the default "GBK" code to "UTF-8". I think this is very troublesome because I use Chinese for code annotation, so "UTF-8" is more common to me.

![image](https://user-images.githubusercontent.com/75734559/169697780-b5e5d666-2d30-49d7-aea2-92398119a72c.png)

**Comment by jantje** [comment]
yes in your workspace preferences

**Comment by xiezhoubin** [comment]
ok
