### ISSUE TITLE
When removing a library or file , arduino paths are lost and compilation fails

### ISSUE THREAD

**Issue by ranm** [Sloeber/arduino-eclipse-plugin#148]
Hey , 
First I want to say how much I love this tool - I'm new to programming for Arduino (not to programming) and it's a much better experience then using the original IDE. 
I've noticed an annoying issue while working on my first Arduino (and Eclipse) project. 
I'm new to Eclipse, so it's totally possible I'm just doing something stupid, but I'm posting this here to help in case this is a real issue. 

To the point : I open a new Arduino sketch and all is fine , I can compile and everything. I can see all compilation paths are correctly assigned: 

![paths_new_project](https://cloud.githubusercontent.com/assets/2144055/3142325/e6607444-e9b8-11e3-82be-798d7c74a87e.jpg)

Then , I'm adding a new library to the sketch , the path is linked correctly and compilation still works fine : 

![paths_with_lib](https://cloud.githubusercontent.com/assets/2144055/3142326/018545b0-e9b9-11e3-9c5c-814932ef7334.jpg)

Now , I delete the new library , by right clicking it and choosing "delete", I click o.k. (it says the content will not be deleted and only the workspace link will be removed. and now the paths are totally different, and also, the path to the deleted library is still there:

![paths_after_lib_removed](https://cloud.githubusercontent.com/assets/2144055/3142331/39917938-e9b9-11e3-8a85-8a58bd03feef.jpg)

now , I cannot compile at all as the main IDE path is missing , and the compiler cannot find "Arduino.h" : 
![paths_after_lib_removed_not_compiling](https://cloud.githubusercontent.com/assets/2144055/3142333/55e95484-e9b9-11e3-87e8-deef462688db.jpg)

I couldn't find a way to easily fix that , besides starting a new project and moving all my work into it. exporting the settings from another project that works didn't work as well - it didn't fix the missing paths. 

Any ideas? 
I'm using Win8
Eclipse IDE for C/C++ Developers
Version: Kepler Service Release 2
Build id: 20140224-0627
Arduino plugin V1.2.5.5 with Arduino IDE 1.0.5-r2 .

**Comment by jantje** [comment]
This issue has been fixed by CDT
