### ISSUE TITLE
The MAC system cannot be installed and used.

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1483]
![R`3AY`UEC9AUTOD_3R)B CW](https://user-images.githubusercontent.com/75734559/171982746-31b1a025-dcda-4513-82e1-f4884329d65f.jpg)
![8PNA92SI`BJ(Y{MSND%C2UL](https://user-images.githubusercontent.com/75734559/171982739-d485430a-8718-4fe2-8d0c-b09027fd463d.jpg)
![DUVRRZ_K_IW3E12N_CK2F60](https://user-images.githubusercontent.com/75734559/171982748-77b6244d-585a-4d53-b4a3-c57dbf7ed315.jpg)
![~Q_I4CVH@Z$1SXRQYZSZTU](https://user-images.githubusercontent.com/75734559/171982751-59ff84e3-c260-4f34-9f24-46e2be2324de.jpg)

**Comment by jantje** [comment]
I'm sorry. I don't know what you are trying to do and I do not understand most of what is visible in those pictures.

**Comment by xiezhoubin** [comment]
> I'm sorry. I don't know what you are trying to do and I do not understand most of what is visible in those pictures.

This means that the MAC system cannot open the installation package, and an error "sloeber is damaged" will be reported. I have tried several versions without success.

**Comment by jantje** [comment]
That is most likely a Mac security feature. Have you seen the install comments here http://eclipse.baeyens.it/stable.php?OS=MacOS

**Comment by dblewis76** [comment]
I have tried to install V4.4.0 on MacOS Monterey also. After downloading, moving the ZIP file out of the Download folder and using the Mac native Archive Utility to unpack and running the sudo command as stated here  http://eclipse.baeyens.it/stable.php?OS=MacOS, when I start Sloeber, I get these errors:
![Screen Shot 2022-07-06 at 10 15 58 PM](https://user-images.githubusercontent.com/25549205/177548294-b0d34ed4-90ed-4a56-b346-bf001b5969d5.png)
![Screen Shot 2022-07-06 at 10 19 51 PM](https://user-images.githubusercontent.com/25549205/177549105-d7a74ea2-67a6-46e2-8c51-53991fd9a114.png)
![Screen Shot 2022-07-06 at 10 20 25 PM](https://user-images.githubusercontent.com/25549205/177549124-09b96ea6-58c7-402b-8fa5-9befacf86a9c.png)
![Screen Shot 2022-07-06 at 10 20 36 PM](https://user-images.githubusercontent.com/25549205/177549160-c5d4c868-aaff-4946-a356-b735c67877fd.png)

Expanding one of these errors shows:
![Screen Shot 2022-07-06 at 10 24 14 PM](https://user-images.githubusercontent.com/25549205/177549479-74da90f5-4e3f-47c2-aa91-3ae3dca517f5.png)

What do I need to do to fix this? I there a specific version of MacOS that V4.4.0 works with?

**Comment by jantje** [comment]
I think I have read somewhere you need to upgrade your java.

**Comment by jantje** [comment]
closing as to long without activity
Please reopen if you have new info
