### ISSUE TITLE
Migration from 4.3.3 to 4.4.0 workspace issues

### ISSUE THREAD

**Issue by ElsomaUwe** [Sloeber/arduino-eclipse-plugin#1486]
---

using Windows 10 on a Lenovo Yoga Laptop
working with Arduino Due projects
using sloeber product
was upgrading from 4.3.3. to 4.4.0
**Using same/old workspace**
![grafik](https://user-images.githubusercontent.com/64010262/175900938-11016870-91b9-4344-ade2-c6efa2efda52.png)

**Describe the bug**   
1) eclipse / sloeber crashes sometimes and does not react
2) compiler/toolchain does not find "something", after changing board to another board and then changing it back, it works
3) darkest dark theme does not work any longer in old workspace. In a new workspace it works.

**Comment by jantje** [comment]
>    eclipse / sloeber crashes sometimes and does not react

This has been reported before. It is a difficult migration and a migration is hard to test.
One properly migrated this should be fixed

>    compiler/toolchain does not find "something", after changing board to another board and then changing it back, it works

The "changing board to another board and then changing it back" procedure is the best known to fix "something" issues.

>   darkest dark theme does not work any longer in old workspace. In a new workspace it works.

Sloeber does not do anything with the Eclipse theme's.

**Comment by jantje** [comment]
Can this issue be closed?

**Comment by ElsomaUwe** [comment]
If there is no major issue with it for all users that migrate to new version, this item can be closed. 
At my PC it is still a migrate old projects in new Version.

**Comment by jantje** [comment]
I'm considering to remove the auto upgrade code and make it a manual process. That should fix the hanging/ not reacting.

**Comment by jantje** [comment]
I removed the auto upgrade which should stop the hanging. It is currently in the nightly
