### ISSUE TITLE
bootloader was overwritten without warning

### ISSUE THREAD

**Issue by ChristianBrandtner** [Sloeber/arduino-eclipse-plugin#1487]
it is possible to flash a program even though it is too big, in Arduino IDE it is not possible.
See Screenshot:
![bootloader_Overwrite](https://user-images.githubusercontent.com/60114001/176466049-8ca47cac-3b92-4837-ad8d-2b0bec96337d.png)

Eclipse Version: 2022-06 (4.24.0)
Sloeber, the Eclipse Arduino IDE (plugin version)	4.4.0.202107110422
Arduino Version 1.18.19, or 1.18.15

**Comment by jantje** [comment]
Yes there is no size test in Sloeber

**Comment by ChristianBrandtner** [comment]
is it now a feature for ever?

**Comment by jantje** [comment]
Feel free to fix it or find some easy way to fix it that would convince me to take it up.

**Comment by ChristianBrandtner** [comment]
if i could, i would have done it already.
Thanks for your answer.
