### ISSUE TITLE
>What do I need to do to fix this?

### ISSUE THREAD

**Issue by dblewis76** [Sloeber/arduino-eclipse-plugin#1488]
>What do I need to do to fix this? 

Allow sloeber access to the internet.

_Originally posted by @jantje in https://github.com/Sloeber/arduino-eclipse-plugin/issues/1483#issuecomment-1176200202_

**Comment by dblewis76** [comment]
It has full access to the Internet. Even after adding Sloeber.app to the firewall, it failed. By changing the "https" to "http" in Sloeber->Preferences->Third party index URLs it can now access them.

**Comment by jantje** [comment]
so the fix is to install AdoptOpenJDK 11
thanks
PS the to be released soon release manages it own java version.
