### ISSUE TITLE
Entries in 'append to link' have no effect

### ISSUE THREAD

**Issue by JojoS62** [Sloeber/arduino-eclipse-plugin#1494]
**Describe your environment**   
Sloeber product   
Sloeber version number  4.4.0
windows 10

**Describe the bug**   
additional link option in project settings-Arduino-append to link are not used.

**To Reproduce**   
1. Go to 'Project/Properties/Arduino'
2. Add some weird name in 'append to link'
3. run build
4. See no error

**Problem**

wrong env variable in link command, needs to be 'sloeber.extra.link'

![grafik](https://user-images.githubusercontent.com/6775562/180591228-e9abf67d-58ed-4d52-93b2-67f67f2e57da.png)

Credits go to user  frutziputzi in mikrocontroller.net who discovered the reason for this bug.

**Comment by jantje** [comment]
Great issue description :-) thanks
Workaround: modify the Arduino combiner command line patters (replace _ with .)

**Comment by JojoS62** [comment]
thanks also for the fast response,
Yes, that workaround did it already. But also adding an additional object file became obsolete. Changing from additional objcopy to using an assembler source was more compliant with the standard build system.
And it seems that this feature wasn't used by someone for long time :)

**Comment by jantje** [comment]
I don't think this feature was ever used.
When I added the code to add to the c/c++ code line (which I use) I added all the other arduino code commands extensions in one go; for compliance and for "god knows who will ever need this"
