### ISSUE TITLE
Build failing successfully Or successfully failing! A Strange one...

### ISSUE THREAD

**Issue by MangyDogUK** [Sloeber/arduino-eclipse-plugin#1503]
Ok this is a new one to me, I fixed the environment but... But now Im having this really strange one...
![image](https://user-images.githubusercontent.com/35331819/193949018-5b0a9c95-cbd1-4875-9b4a-0a23abfcf704.png)

When I do a fresh build after a clean. I get a failed build warning. But the build was actually successful, and a bin is created.

If I run the build again. It builds with no errors or fails. 

Like I say, this is a strange one. 

Sloeber app, Stable.

**Comment by jantje** [comment]
Seems like the combiner sees a problem but doesn't return an error and creates the output file
So the build continues
And as the last command is successfull the build is successfull
Seems like a problem in the arm-none-eabi-g++ you use

**Comment by MangyDogUK** [comment]
I just updated the arm tool chain, its still happening. I dont think its the toolchain

**Comment by jantje** [comment]
Can you check the return/status code of the command? You can turn off the automatic makefile generation and then modify it as described here https://stackoverflow.com/questions/748445/shell-status-codes-in-make#748494

**Comment by MangyDogUK** [comment]
I did have a mistake in my code, the header call had static for the function call while the cpp file didnt.

That triggered the first error. Though not sure why it would skip it on the second

**Comment by jantje** [comment]
From what I can see, there is an error in the code but the gcc program seeing the error returned a status that is wrong or incompatible with the make sloeber is using.

**Comment by jantje** [comment]
Closing as to long open without response
