### ISSUE TITLE
Error while trying to install sparkfun boards

### ISSUE THREAD

**Issue by mobacon** [Sloeber/arduino-eclipse-plugin#1507]
**Describe your environment**   
I use the Sloeber plugin (Version 4.4.1)
OS: Windows 10 and Kubuntu 22.04

**Describe the bug**   
After adding a new board source I get an error when I want to install boards.

**To Reproduce**   
1. Go to Preferences | Sloeber | Third party index url's 
2. Add the URL https://raw.githubusercontent.com/sparkfun/Arduino_Boards/main/IDE_Board_Manager/package_sparkfun_index.json
3. Go to Preferences | Sloeber | Platforms and Boards
4. Click on the first Sparkfun checkbox
5. See the error report: **An error has occurred. See error log for more details.
Cannot read the array length because "inScopeVersions" is null**

**Expected behavior**   
I can select one of the Sparkfun AVR boards from the list.

**Comment by mobacon** [comment]
Duplicate of #1497
Sorry for wasting your time!

**Comment by jantje** [comment]
Thanks :-)
