### ISSUE TITLE
Cant' check a checkbox in Platforms and Boards

### ISSUE THREAD

**Issue by freeride01** [Sloeber/arduino-eclipse-plugin#1514]
Hi,
I downloaded the latest Sloeber V4.4.1 for Linux and installed it on Fedora. I want to add ESP32 support to it.
In Preferences-> Sloeber -> Third party index url's I entered " https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
Then in Platforms and boards I see the "package_esp32_index.json" option, but cant' select *any* option inside the package box. Any idea why?

P.S. Just tried the Windows 10 version - the *exact same problem* exists there too.

**Comment by jantje** [comment]
You have to click the > untill you get to versions.
![afbeelding](https://user-images.githubusercontent.com/1175841/201364489-d83c98c1-0a99-4014-969d-a5e28bc983e0.png)

**Comment by freeride01** [comment]
Thanks, it works now.
I have another issue, however. The project I import uses the NimBLE stack, so I installed it, but when I try to build the project , I get `NimBLEDevice.h: No such file or directory`
The library shows as installed in Library Manager, but it seems it's not added to the project for some reason.

**Comment by jantje** [comment]
great have fun
