### ISSUE TITLE
usage of C++17 on STM32

### ISSUE THREAD

**Issue by MasteringTheMess** [Sloeber/arduino-eclipse-plugin#1532]
I tried to get the compiler to use C++17 standard

Therefore I modified platform.txt and the corresponding platform.sloeber.txt in the C:\Sloeber\arduinoPlugin folder.
Although this works for Arduino IDE, it has no effect and __cplusplus still outputs 201402

Is compiler.cpp.std set somewhere else?

in the build Environment, the changes are apparent:

![image](https://user-images.githubusercontent.com/85557472/206720415-58f83270-44b1-454a-a213-b441aa85edb3.png)

**Comment by jantje** [comment]
How to modify a .txt file
1) Modify the .txt file
2) delete the corresponding *.sloeber.txt file.
3) for each project that should be impacted: goto project properties->sloeber->apply and close
3 check) if the sloeber.txt file is not there something went wrong and your change has not been taken into account in any project by Sloeber.
4) force Sloeber to recreate the makefile by deleting the build output folder
5) build

**Comment by jantje** [comment]
Also see the newly created discussion for a better way 
https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1533

**Comment by MasteringTheMess** [comment]
Hooray! it works now!

Thanks for clarifying how to fiddle with the .txt-files :)
