### ISSUE TITLE
MiniCore-Master platform use

### ISSUE THREAD

**Issue by Mattpisti** [Sloeber/arduino-eclipse-plugin#1535]
Hi there, I just installed version 4.4.1 and added the MiniCore-Master platform.  Unfortunately all my projects based on that cores do not compile any more showing syntax errors.

Everything works with version 4.3.3 

Any clue?
Thanks
Matt

**Comment by jantje** [comment]
How did you install the MiniCore-Master platform.
What compile errors do you get?

**Comment by Mattpisti** [comment]
I added the Mini-Core platform (I tried also with the newer release at https://github.com/MCUdude/MiniCore/releases ) with Sloeber\Preferences\Private Hardware Path and then in Project\Properties as in the attached picture 

![image](https://user-images.githubusercontent.com/67509942/209164013-6576866c-bd0f-4d1e-bafe-7db2fca4a0a8.png)

This is the compile error

"C:\\Sloeber4.4.1\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ..\sloeber.ino.cpp'
'Starting C++ compile'
"/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=8000000L -DARDUINO=10812 -DARDUINO_AVR_ATmega328 -DARDUINO_ARCH_AVR     -I"D:\arduino-1.8.13\hardware\MiniCore-master\avr\cores\MCUdude_corefiles" -I"D:\arduino-1.8.13\hardware\MiniCore-master\avr\variants\standard" -I"D:\arduino-1.8.13\hardware\MiniCore-master\avr\libraries\EEPROM\src" -I"D:\arduino-1.8.13\libraries\jeelib-master" -I"D:\arduino-1.8.13\libraries\arduino-libs-manchester-master" -I"D:\arduino-1.8.13\libraries\truerandom" -I"C:\Users\vince\Documents\Arduino\libraries\OneWire" -I"C:\Users\vince\Documents\Arduino\libraries\DallasTemperature" -MMD -MP -MF"sloeber.ino.cpp.d" -MT"sloeber.ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "..\sloeber.ino.cpp"   -o "sloeber.ino.cpp.o"
sh: /bin/avr-g++: Permission denied
make: *** [subdir.mk:20: sloeber.ino.cpp.o] Error 126
"C:/Sloeber4.4.1/arduinoPlugin/tools/make/make all" terminated with exit code 2. Build might be incomplete.

Hope this helps

**Comment by jantje** [comment]
When using private hardware there is platform.json file so not all environment variables are known.
You will need to look in the platform.txt file and find the environment variable in the compile command that points to the gcc install folder
Then create this environment variable in sloeber or the platform.txt or your OS (whatever suits your taste)

**Comment by Mattpisti** [comment]
Sorry but I am a novice and don't fully understand what you mean. As I wrote, after using Arduino IDE, I used V4.3.3 that works just fine adding the MiniCore  platform in the same way I did for V4.4.1.
 I would appreciate if you are so kind to explain what I should do step by step.
For your reference I am attaching the platform.txt file contained in the MiniCore platform
Thanks

[platform.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/10293374/platform.txt)

**Comment by jantje** [comment]
Novices should not use private hardware.
Why not use https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json ?

**Comment by Mattpisti** [comment]
I tried using it but I get an error, see pictures, and I am stuck, any suggestion?
Why V4.3.3 works with private hw and 4.4.1 doesn't?

![1](https://user-images.githubusercontent.com/67509942/209480583-986642d1-edbd-4591-ab2a-44bbe39e1821.jpg)


![2](https://user-images.githubusercontent.com/67509942/209480585-63d2ff93-583f-4843-858a-9491333d89ab.jpg)

**Comment by jantje** [comment]
It is unclear to me what you are trying to do but it doesn't comply with how Sloeber is supposed to work.
1) in the menu select Sloeber->preferences
2) add https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json to the "Third party index url's" page
![afbeelding](https://user-images.githubusercontent.com/1175841/209482993-1a9449a2-deeb-4bed-8041-6130ea28ecea.png)

3) select apply/close
4) in the menu select Sloeber->preferences
5) in Sloeber->Platform and boards check all the versions you want to install
![afbeelding](https://user-images.githubusercontent.com/1175841/209483009-2de0c266-a1c4-4982-9325-0716d6c090d6.png)
6)Select apply and close
7)wait for Sloeber to download and install all needed stuff
![afbeelding](https://user-images.githubusercontent.com/1175841/209483028-3aeff7d5-1d08-49c6-9d4e-9bcea5a4f39e.png)


You are ready to use the MicroCore Boards

**Comment by Mattpisti** [comment]
Thanks, it works now and I am understanding a little bit more how Sloeber works.

**Comment by jantje** [comment]
This is exactly the same behaviour as Arduino IDE.
Different places same behaviour.
Anyway I think this issue can be closed.
