### ISSUE TITLE
Sloeber (features) wiped out after Eclipse "Check for updates"

### ISSUE THREAD

**Issue by dsptech** [Sloeber/arduino-eclipse-plugin#1542]
Hi,
I have a Sloeber installation (Windows) done two year ago (4.2 or 4.3?). The original installation was done via the integrated package and was later updated via the Eclipse update system (Sloeber nightly too).
Over the time, "update sites" and java (now 15) have been updated according to the other Github issues and everything worked fine up to yesterday.
By applying the last update, Eclipse CDT appear to work, but Sloeber (and other extensions as the themes) seems to be wiped out and lots of errors are showing in the workspace log.
I suspect that the issue is someway related to: https://github.com/Sloeber/arduino-eclipse-plugin/issues/1529.

Honestly, I have no idea how to deal the problem and also if this a Sloeber, Eclipse or Java version issue. Does anyone have any suggestion?.

Thank you.

P.S.: I attach the screen capture of:
1) Sloeber before the update
2) Configured update sites
3) Installation details
4) Proposed updates (performed with no update errors)
5) Final (bad) result with errors.

![SloeberBeforeUpdates](https://user-images.githubusercontent.com/26789495/211792031-1774acc3-16a2-4d83-abb3-486ded8aa3fc.jpg)
![SloeberUpdateSites](https://user-images.githubusercontent.com/26789495/211792072-71ab12fc-e3e9-4524-8e0a-57b3dd9019ed.jpg)

![SloeberDetailsPart1](https://user-images.githubusercontent.com/26789495/211792190-bc74c8a2-08f0-4b64-a98c-0e5ebe091b75.jpg)
![SloeberDetailsPart2](https://user-images.githubusercontent.com/26789495/211792220-92562e64-78de-44ce-8524-3d3557165749.jpg)
![SloeberProposedUpdates](https://user-images.githubusercontent.com/26789495/211792255-f9cb6eaf-f293-4e54-9b6f-969417061a0d.jpg)
![SloeberReviewAndConfirmUpdates](https://user-images.githubusercontent.com/26789495/211792267-2e507d54-8b92-4a06-88ec-cf6eb4ea6795.jpg)
![SloeberBadResult](https://user-images.githubusercontent.com/26789495/211792298-1763a47f-d5b5-40e3-9019-33522446ccbf.jpg)

**Comment by jantje** [comment]
From the log it seems some parts of the CDT ui are no longer available.
This is normal as you did a CDT upgrade that requires java 17 and you say you run java 15.
I would also recommend to clean up your update sites. Only keep the latest versions of the sites that have multiple versions.

**Comment by dsptech** [comment]
Hi,
as you suggested I replaced Java 15 with Java 17 (JRE from https://adoptium.net/temurin/archive/) and now also assume that the info at http://eclipse.baeyens.it/stable.php?OS=Windows are outdated (it says max V.15)

With Java17, the update doesn't produce any final error but some plugins is still wiped. Focusing on Sloeber, I noticed that the "Sloeber" menu item is missing from the main menu, and now there is no icon for the Sloeber's perspective.
However the perspective seems to work (switching to Egit and Sloeber again restores the correct view) and the Sloeber entry also exists in the general preferences. Finally, all the Sloeber icons in the toolbars seems to work properly. 

Sadly, in the existing Arduino Projects the project context menu does no longer show the "Sloeber" entry so, for example, I'm no longer able to change the board.

Just for checking, has the last nightly the version number: 4.4.1.202209072349 ?
Thank you.
![SloeberUpdatedWJava17_somethingMissing](https://user-images.githubusercontent.com/26789495/212490030-06b38386-eaf1-4ff0-ac1c-e06c51fcc249.jpg)

**Comment by dsptech** [comment]
Hi,
as you suggest, I performed the update with Java 17 (JRE from https://adoptium.net) ... and now I also assume that the info at: http://eclipse.baeyens.it/stable.php?OS=Windows are outdated (it says Java max 15).

Now the update appear to work but themes continue do be wiped out.  
Focusing on Sloeber, the "Sloeber" entry in the main menu' is missings. Also the icon of the Sloeber perspective is missing but it appear to work properly, this mean that switching, for example, to the Egit perspective and again to Slober work as expected.

Sloeber entry is also present in the main preferences and it is also accessible via project context menu. Finally, the Sloeber toolbars appear to work fine. 

How to fix the missing items ? 

![SloeberUpdatedWJava17_somethingMissing](https://user-images.githubusercontent.com/26789495/212549012-706ea1b9-b668-45e1-89d8-3d0ea65758e6.jpg)

**Comment by jantje** [comment]
>Focusing on Sloeber, the "Sloeber" entry in the main menu' is missings. 

This is only there when you are in the Sloeber or C/C++ perspective. Seems you are not in one of those perspectives.

>How to fix the missing items ?

I advice to download the latest Sloeber product and start from there.
This because an old eclipse install with many updates is prone to issues.

**Comment by dsptech** [comment]
Hi @jantje,
I performed further test as remove the instlled plugins, update on a fresh workspace, change Java version etc, but but every attempt is failed so I place this thing in stand-by for a fresh installation.

By the way, in a fresh Windows 10 installation I downloded (from github) and installed the full package as you suggested. After a successfull update I found the that the list of the update sites has been totally emptied. Not sure if this is expected (and I have to reenter them) or I have to fill a new issue.

Finally, also the installation the Sloeber plugin in a fresh Eclipse installation has failed. Problems are similar to https://github.com/Sloeber/arduino-eclipse-plugin/issues/1529 and https://github.com/Sloeber/arduino-eclipse-plugin/issues/1492 but the proposed solutions do not work. I will post on a 1529 soon.

**Comment by dsptech** [comment]
I'm no able to find a reason for the erasing of the update sites list (see previous message). I suspect now about a bug in the Eclipse update system. A further investigation should be required but this is over my skills so I will use this: https://github.com/Sloeber/arduino-eclipse-plugin/issues/1529#issuecomment-1399234045.
Regards.
