### ISSUE TITLE
Project name doesn't match folder name

### ISSUE THREAD

**Issue by jonahgraham** [Sloeber/arduino-eclipse-plugin#1569]
While it is certainly permitted, it caught me out that the folder name didn't match the project name (autoBuild vs ManagedBuild)

https://github.com/Sloeber/arduino-eclipse-plugin/blob/dca2c6677d57af23fe51961ccfdca2f4aecbbdd4/io.sloeber.ManagedBuild/.project#LL3C8-L3C28

**Comment by jantje** [comment]
I noticed that as well.
If I noticed correctly this is a consequence of renaming ManagedBuild to AutoBuild with linked project folder.
I'm not yet at the cleanup phase but that will be one to fix.
Because I'm not even sure AutoBuild is a good name 🤔

**Comment by jantje** [comment]
fixed this somewhere a long time ago.
