### ISSUE TITLE
Eclipse complains that sloeber uses a path name that is too long

### ISSUE THREAD

**Issue by jonbarril** [Sloeber/arduino-eclipse-plugin#1571]
This problem has occurred at least for the past few years that I have been using sloeber. It still happens with the latest version. Not a big problem but it only happens with the sloeber plugin, and eclipse will just sit there while I think it is starting up until I find the hidden popup and press the OK button.

--jon

**Comment by jonbarril** [comment]
Attached is the eclipse error popup....

![SloeberLongPath-small](https://github.com/Sloeber/arduino-eclipse-plugin/assets/20114096/bbe39adc-99c3-47c2-807d-85e793b30df8)

**Comment by jonbarril** [comment]
Oooops. This has been happening for so long I never read the message all the way. Sorry for reporting this:-)

**Comment by jonbarril** [comment]
OK. Read #705, And decided to reopen this issue as #705 seems to fall short of a clear answer....

Please forgive my ignorance but something seems fishy here. Why doesn't any other of the many plugins that my eclipse uses have this problem? What is it about sloeber that uniquely qualifies it to have this problem, and requires it to have a special solution different from all other eclipse software in marketplace?

I have generally found that software that requires such special treatment will come back and bite you down the road when you forget the special magic required to make it work. The less magic the better. If the answer is "I/we don't have the time or resources to fix it" then please say so (I think you sort of kind of said this in #705 but there was a lot of noise there), I/your user base will certainly understand, and it might even inspire some of us to try and help out:-)

--jon

**Comment by jantje** [comment]
The problem is Sloeber, windows and it bites in make.
2 things are out of my control.
CDT has the same issue
Sloeber makes it worse because the arduino framework is installed in the sloeber install folder.
You can define SLOEBER_HOME (as c:\ or c:\sloeber\ ...) to decouple the Arduino framework install from your sloeber install

**Comment by jonbarril** [comment]
I am familiar with eclipse environment variable in java runtime configs. I'm not familiar with environment variables elsewhere in eclipse.

I tried googling the environment variables in eclipse but nothing obvious is jumping out. Where do I put SLOEBER_HOME in eclipse to fix this problem? Can you suggest a link where I can find the info, or the eclipse menu path to find it?

Thanks
--jon

**Comment by jonbarril** [comment]
In eclipse I found Window->Preferences->General->Workspace->Linked Resources. I can create SLOEBER_HOME there that points to the "arduinoPlugin" directory mentioned in the eclipse startup message. How do I tell Eclipse or Sloeber to use it?

--jon

**Comment by jantje** [comment]
I create the SLOEBER_HOME environment variable at the OS level.
I also have used a script to set a value to SLOEBER_HOME and then start Sloeber

**Comment by jonbarril** [comment]
The way I installed sloeber is via eclipse marketplace. That is the only way I have installed and used it for the past few years. Perhaps you are referring to some way to use it standalone. I don't know and haven't explored such possibilities.

I did a quick search in my windows directory under by eclipse install directory. It seems my sloeber "arduinoPlugin" install directory is hardwired throughout the sloeber plugin software (i.e. library .c and .h files). I don't understand how defining a SLOEBER_HOME system environment variable will do anything for this. After a bit of research I also haven't figured out how to tell eclipse to get the sloeber plugin from SLOEBER_HOME instead of wherever it installed and configured the location when I used the eclipse marketplace installer. The info I found is about old versions of eclipse.

There seem to be many moving parts in all of this and it is beyond my knowledge and experience with eclipse configuration and internals. If you have some quick suggestions to try great, otherwise I'll just hit the OK button whenever eclipse complains about the Sloeber long path name at start up.

--jon

**Comment by jantje** [comment]
As you can see here in the code Sloeber reads the environment variable SLOEBER_HOME and if it is available it uses that instead of the default
https://github.com/Sloeber/arduino-eclipse-plugin/blob/463885dc9d56653c735962598be6fa6fff3ca1bb/io.sloeber.core/src/io/sloeber/core/common/Common.java#L34-L56

There are many ways to set environment variables.
My guess would be that you would prefer to set a environment variable in windows at the OS level:
https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/

Amongst others I set it for debug runs in eclipse itself
![afbeelding](https://github.com/Sloeber/arduino-eclipse-plugin/assets/1175841/675eb767-dc98-4840-a720-f7da2d80012f)

As I said before you can create a command file that set environment variables and then start sloeber.

**Comment by jonbarril** [comment]
OK. Now I think I understand. SLOEBER_HOME is already baked into your code. All I have to do is define an OS environment variable (which I already knew how to do -- thought I had to do it via Eclipse to make the plugin understand).

Unclear about where the sloeber "home" directory is to put in SLOEBER_HOME. Since I installed Sloeber via marketplace it seems to have placed sloeber at....

    C:\Users\Jonb\eclipse\java-2022-09\eclipse\arduinoPlugin 

Is this what I should use when defining SLOEBER_HOME?

--jon

**Comment by jantje** [comment]
If you define SLOEBER_HOME as C:\
Sloeber will use C:\arduinoPlugin  instead of the default [Where I installed Sloeber]\arduinoPlugin which is in your case  C:\Users\Jonb\eclipse\java-2022-09\eclipse\arduinoPlugin 
Which makes the path way smaller.
