### ISSUE TITLE
Eclipse/sloeber updated, install fails, sloeber is broken

### ISSUE THREAD

**Issue by jonbarril** [Sloeber/arduino-eclipse-plugin#1573]
Just updated eclipse (originally 2022-09, splash now says 2023-06) and presumably Sloeber. When I start eclipse it complains about the Sloeber long path problem (with an even longer message than before) . Hitting OK eclipse starts but soon complains about an illegal character in the arduinoPlugin make file....

    An internal error occurred during: "Finishing the installation ..".
    Illegal char <:> at index 2:  C:\Users\Jonb\eclipse\java-2022-09\eclipse\arduinoPlugin\arduinoPlugin\downloads\make1.zip

The sloeber plugin no longer works because it complains that it is waiting for the install to finish:-(

--jon

**Comment by jantje** [comment]
That seems like a perfectly fine path (bit long though 😒 )
Seems like a bug/incompatibility with eclipse 2023-06
do you have a stack trace

>The sloeber plugin no longer works because it complains that it is waiting for the install to finish:-(

as the installation failed that seems normal.
