### ISSUE TITLE
Builds for the ESP32 platform v 2.0.x are very slow at generating makefiles

### ISSUE THREAD

**Issue by judge2005** [Sloeber/arduino-eclipse-plugin#1581]
**Environment**
Using Sloeber 4.4.1 product on MacOS Monterey 12.6
ESP32 packages downloaded from https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json, versions 2.0.x (tried for 2.0.7, 2.0.10 and 2.0.11).

<img width="823" alt="Screenshot 2023-08-21 at 3 23 01 PM" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/294515/629c7805-2340-4400-91a7-9f276853dccb">

**Bug**
Sloeber is very slow at generating makefiles for my ESP32 projects using platform version 2.0.x, in total it runs for several minutes for one of my projects, so even a small change to the .ino file results in long build times. In contrast other platforms I use (mainly ESP8266) and versions 1.0.x of the ESP32 platform take a few seconds at most to generate makefiles. Note that the generation is slow for all makefiles, including those for third party libraries as well the platform source itself.

<img width="519" alt="Screenshot 2023-08-21 at 2 51 54 PM" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/294515/06cda443-f1fe-4607-ae5d-5021d94eada5">

**To Reproduce**   
Create an ESP32 project and build it  - watch the progress in the progress tab and you can see how long it takes. Obviously it is more noticeable with larger projects using more 3rd party libraries. [My bluetooth library](https://github.com/judge2005/ESP32BT) contains an example that can be used, It will generate a build error for platform versions > 1.0.x, but it shows the issue anyway.

**Comment by jantje** [comment]
Having to wait for minutes to generate the makefile is absolutely unacceptable.
However,
1) I tried to reproduce this on my windows machine (lots of memory but really slow CPU) and could not reproduce the problem with my biggest project.
![afbeelding](https://github.com/Sloeber/arduino-eclipse-plugin/assets/1175841/59bd62b4-f30d-4c40-918c-761863839f44)
2) I'm currently rewriting the whole "managed build" which generates the makefile (slow progress but I should get somewhere end this year)

I think it must be a specific OS issue or a specific setup issue.
If someone who owns a mac could try to reproduce we would know a little bit more.
