### ISSUE TITLE
Sloeber 4.4 pre-packaged app for Mac does not run

### ISSUE THREAD

**Issue by GreyCon** [Sloeber/arduino-eclipse-plugin#1586]
I just downloaded and unpacked the 64bit mac image. Running on OSX Ventura. I ran the usual xattr commands to remove the quarantine issue. Firstly, the sloeber-ide is missing the Executable file attribute, so won't start. Easy fix. 

However, after it starts, it fails when trying to unpack and setup board files. See:
Failed to install Arduino AVR Boards
Failed to extract tar.bz2. "/Users/alex/Documents/Sloeber.app/Contents/Eclipse/arduinoPlugin/downloads/avr-1.8.6.tar.bz2".
Cannot run program "chmod": error=2, No such file or directory

Note that this issue was reported a year ago, but closed because the OP managed to get the Eclipse plugin working. I will follow this route now, but I'd prefer to have the supported product version. 

Wrt to the above, I can see that the file Sloeber2.app/Contents/Eclipse/arduinoPlugin/packages/arduino/hardware/avr/1.8.6/programmers.txt has been created. So I don't know why the "chmod" command is failing, there's not much useful info in the logs.

Happy to work on debugging this, if you have any suggestions.

**Comment by jantje** [comment]
Now the build works again 😄 here is the location that probably fails on your os
https://github.com/Sloeber/arduino-eclipse-plugin/blob/4e7007940a22408f155aaadd83a855ff02c0020d/io.sloeber.core/src/io/sloeber/core/tools/PackageManager.java#L259
At least that is the only chmod I know about in the install process and the first place I would look.
