### ISSUE TITLE
Missing icons & Sloeber perspective

### ISSUE THREAD

**Issue by mr-miky** [Sloeber/arduino-eclipse-plugin#1592]
I compiled the plugin by downloading it with git and then passed it on to maven.

Everything went well but when I install the plugin on Eclipse 4.29 does not appear the perspective sloeber among those selectable and also the icon is replaced with a red square as if it did not find the icon but I checked and the png files of the icons there are all.

If instead of installing the plugin in a completely new version I install it in one that had already sloeber installed the perspective remains but here also the icon disappears but it is as if it were the residue of the old configuration and highlights it by placing sloeber between  < >

```
eclipse.buildId=4.29.0.I20230903-1000
eclipse.commands=-os
linux
-ws
gtk
-arch
x86_64
```

![Schermata a 2023-11-24 19-33-07](https://github.com/Sloeber/arduino-eclipse-plugin/assets/12703876/e4c2418a-4658-4f96-96fd-126b148b139a)

**Comment by jantje** [comment]
It is strange that the compile went well because I am currently fixing the "the compile does not work" in issue #1587 .

**Comment by mr-miky** [comment]
> It is strange that the compile went well because I am currently fixing the "the compile does not work" in issue #1587 .

I don’t know what to say maybe we’re building different things.

```
git clone https://github.com/Sloeber/arduino-eclipse-plugin sloeber
cd sloeber
mvn clean verify -Plinux64,latest,NOSDK -DskipTests=true
```


![Schermata a 2023-11-25 13-46-30](https://github.com/Sloeber/arduino-eclipse-plugin/assets/12703876/4feb2480-d63c-4c2d-9509-ae8f383292d2)

**Comment by jantje** [comment]
Strange as it doesn't work for me and has not worked for others
![afbeelding](https://github.com/Sloeber/arduino-eclipse-plugin/assets/1175841/bf0ce937-dba7-4e10-876e-5dc5bcf1d02b)


Anyway the latest eclipse is one way or another not compatible with the latest released Sloeber. As Sloeber hasn't been released for some time I don't know when the incompatibility started.
That is why I'm working on a new release.

**Comment by mr-miky** [comment]
> Anyway the latest eclipse is one way or another not compatible with the latest released Sloeber. As Sloeber hasn't been released for some time I don't know when the incompatibility started. That is why I'm working on a new release.

Last Friday I used a laptop that was unused for a while and sloeber works in the sense that it has the Sloeber perspective. If I remember correctly it uses Eclipse 2023.06 and java 17 anyway tomorrow I can verify.
I surely remember that at the beginning of the current year everything worked then after an update of eclipse maybe 2023.03 the sloeber menu had disappeared but I accidentally discovered that if I use java 17 instead of 11 the menu reappears.

**Comment by jantje** [comment]
> I accidentally discovered that if I use java 17 instead of 11 the menu reappears.

Java17 is a must because Sloeber is based on CDT which requires Java17. If you run from Java11 all menu's and toolbars provided by CDT and Sloeber should disappear.

**Comment by jantje** [comment]
Closing this issue as fixed. Please reopen if you disagree
