### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by DocAlex** [Sloeber/arduino-eclipse-plugin#1606]
Here are some minor suggestions/propbems

### 1. The humbling new user

When you start with 1 project loaded in sloeber and hit the upload button - you get an error messagethat no project is selected.
I understand that in the case of multiple projects this does make sense to avoid accidential compilation. 

But in the case of a single project? I would expect that this is automatically selected

### 2. I understood that the new upload button shall be used only. 

![2023-12-26 18_06_12-sloeber-workspace - Raumfuehler_2_0_Raumfuehler_2_0 ino](https://github.com/Sloeber/arduino-eclipse-plugin/assets/24655926/64c82f5b-3554-4076-a3e3-baea9209545c)

Is there a possibility to get rid of the "old arduino upload" button? It is really annoying when you accidentially hit it. 

### 3. Console

In some cases (I do not understand how this can happen) The very important console view is not showing up. I would like to suggest that a new menue item is added to the "Windows" menu called "show Console". The only way I found was going tho the "help menu" searching for "console" and click on the item. 

Thanks in advance

Alexander

**Comment by DocAlex** [comment]
Forgotten:

4. Properties

for a beginner it is confusing, that there are multiple places for "Properties".

And even depending on what is selected the properties are different:

When libraries are selected - there is no "sloeber" menu

![2023-12-26 18_18_03-sloeber-workspace - Raumfuehler_2_0_Raumfuehler_2_0 ino](https://github.com/Sloeber/arduino-eclipse-plugin/assets/24655926/4fbf172e-1014-4ef2-a75c-2ee83e45a4b1)

When the project is selected - there is a "sloeber" menu.

![2023-12-26 18_18_25-sloeber-workspace - Raumfuehler_2_0_Raumfuehler_2_0 ino](https://github.com/Sloeber/arduino-eclipse-plugin/assets/24655926/c3e58459-8b24-442e-bb2f-a229e979b4eb)

This is confusing me often.

**Comment by jantje** [comment]
1) that could be an option. Feel free to contribute it.
2) you understood wrong
3) are you in the sloeber or the CDT perspective? It should be there. Are you sure you didn't minimize the console or something like that?
4) Eclipse is a professional development environment. That brings a very high confusion level.
