### ISSUE TITLE
Sloeber PLugin in Eclipse C++ IDE Version: 2023-12 (4.30.0) Ubuntu 23.10 wont install due to missing osgi.bundle dependency

### ISSUE THREAD

**Issue by simonboydfoley** [Sloeber/arduino-eclipse-plugin#1613]
When installing via Marketplace the following error occurs;

Cannot complete the install because one or more required items could not be found.
  Software being installed: 
  
  Sloeber, the Eclipse Arduino IDE (plugin version) 4.4.2.202311302107 (io.sloeber.feature.feature.group 4.4.2.202311302107)
  
  Missing requirement: Arduino eclipse plugin 4.4.2.202311302107 (io.sloeber.core 4.4.2.202311302107) requires 
  
  **_'osgi.bundle; org.apache.commons.compress 0.0.0' but it could not be found_**
  
  Cannot satisfy dependency:
    From: Sloeber, the Eclipse Arduino IDE (plugin version) 4.4.2.202311302107 (io.sloeber.feature.feature.group 4.4.2.202311302107)
    To: org.eclipse.equinox.p2.iu; io.sloeber.core [4.4.2.202311302107,4.4.2.202311302107]

I managed  to fix it once by installing a package in apt-get ..... but I can not remember which one it was now and I have spent days trying to find it again :-( its driving me nuts

java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

**Comment by jantje** [comment]
Here is a description of the current state of Sloeber Build:
https://github.com/Sloeber/arduino-eclipse-plugin/issues/1611#issuecomment-1902686623

workaround for now: 

1. use the product.
2. install org.apache.commons.compress in your eclipse install (needed to handle the download files when installing a platform) before installing Sloeber.

PS: I do not know how you can add org.apache.commons.compress to a eclipse install. If you do please provide steps to do so.
