### ISSUE TITLE
Sloeber does not support compiler.optimization_flags.release and debug => more than double size of .elf than Arduino IDE for BluePill F103C8 (64K)

### ISSUE THREAD

**Issue by mkumar2789** [Sloeber/arduino-eclipse-plugin#1625]
Environment
Sloeber Eclipse Plugin  V4.4.2
OS: macOS Sonoma (14.3), M1 MacBook Air (ARM64)

Bug Description  
I was trying to switch from Arduino IDE to Sloeber. So I copy-paste my current myProject.ino code into Sloeber and select Default .cpp file to create Arduino Sketch.
I followed the given tutorial for this:
https://github.com/ArminJo/SloeberTutorial

My configuration is in the screenshot:
1.
<img width="1440" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/14de4277-692b-49c4-8854-3090b0b7ed0c">

2.
<img width="824" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/bc1a1de2-ecbf-4834-8db7-2bb27ae629c7">

3.
<img width="828" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/095cb4a6-ea35-4dbd-9f33-c2d0c8f4116d">

I got an error: (.elf section `.text' will not fit in region `FLASH'; region `FLASH' overflowed by 44808 bytes)
Part-1
<img width="1397" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/27f2fffb-13e7-40e7-8d57-394256b5c70c">

Part-2
<img width="1394" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/7fc001bf-885d-47ad-bde1-d0ffa518a957">

But when I change the existing MCU in Sloeber from BluePill F103C8 (64KB) to BluePill F103CB (128KB), the output shows no error but the size of the code!
<img width="449" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/f3f75c0b-6c5d-47ad-9589-3dbbf8cb28e7">

Now look at Arduino IDE configuration and code size with BluePill F103C8 (64KB)
Config:
<img width="524" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/6f715cdb-ad77-4315-b7d5-c82ef41e3f72">

Output Part-1
<img width="1390" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/7efe24d7-7ba7-46b4-9eed-d35500fcd61d">

Output Part-2
<img width="579" alt="image" src="https://github.com/Sloeber/arduino-eclipse-plugin/assets/103240488/c04badbd-de66-4e21-8518-74ce7e1cfbef">

So why is Sloeber taking up more space than the Arduino IDE? Is there any setting left or any missing steps to do?
As of now, I have to work on the Arduino IDE, but I am willing to work with Sloeber.

Thanks

**Comment by jantje** [comment]
>So why is Sloeber taking up more space than the Arduino IDE? 

I have created a Q&A discussion to explain all possible reasons I can think of.
https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1626

The -DDebug in image number 3 may explain it.

I'll add a discussion to describe what to do if all seems equal but there are Arduino IDE versus Sloeber differences.

**Comment by mkumar2789** [comment]
Thanks for your reply, Jantje.

I just use -DDEBUG in the "append to" options, as explained in the tutorial, which can be avoided in my case.
And I already deleted unneeded libraries and unneeded boards as well.
One more thing to notice: when I upload code with BluePill F103CB (128K) in "Properties" to the BluePill F103C8 (64K) board, even though code was not responding properly, code uploaded with no error console.
And I'm using the only board URL, officially supported by STMicroelectronics, to minimise random behaviour of code.

**Comment by ArminJo** [comment]
The reason for being bigger than Arduino is that arduino introduced new debug target.
so the platform.txt looks now:
```
#compiler.optimization_flags=${compiler.optimization_flags}
compiler.optimization_flags.release=${build.flags.optimize} ${build.flags.debug}
compiler.optimization_flags.debug=-Og -g
```
If you change it to 
```
compiler.optimization_flags=${build.flags.optimize} ${build.flags.debug}
compiler.optimization_flags.release=${build.flags.optimize} ${build.flags.debug}
compiler.optimization_flags.debug=-Og -g
```
the `-Os` contained in build.flags.optimize are now recognized by sloeber and the size is smaller (as in Arduino if all unnecessary libraries are disabled 😀 ).
See also: https://github.com/stm32duino/Arduino_Core_STM32/issues/2159

**Comment by jantje** [comment]
Thanks for the info.
I had a watcher on the platform specification but it didn't pick this change up. 😞 
Seems I had a watcher on a specific version 🤡 
This seems to have been introduced 4 year ago. 
I guess I should have a look and see what else Sloeber is missing.

As a **workaround** you have the option to change the txt file and add
compiler.optimization_flags=${compiler.optimization_flags.release}
or you can create the environment variable compiler.optimization_flags in the windows->preferences with the value ${compiler.optimization_flags.release}

**Comment by MangyDogUK** [comment]
Can confirm this issue is still happening as of August 2024.
I had to ad -Os to the compile append to C and C++ line to get it to optimise my code. It appears to be ignoring the optimise level argument in the stm32duino project settings.

**Comment by jantje** [comment]
I know.
Currently trying to get things back working on Linux.
Then This is on the agenda.
Please join the test effort if you can
https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1660

**Comment by jantje** [comment]
Thinking about this.
The easiest workaround is adding ${compiler.optimization_flags.release} to the  the compile append to C and C++ line

**Comment by jantje** [comment]
This should be fixed in the nightly (I say should as I don't have a reliable way to test) I tried both V 2.7.1 and V2.8.1
Please join the test effort; more info about the test effort for V5 is here https://github.com/Sloeber/arduino-eclipse-plugin/discussions/1660
