### ISSUE TITLE
Third party index urls

### ISSUE THREAD

**Issue by pallik49** [Sloeber/arduino-eclipse-plugin#1636]
I get this error in preferences when I do Apply

Unable to download 
https://v1.cecdn.yun300.cn/100001_2012215089/package_TK499duino_index.json
Failed to download url 
https://v1.cecdn.yun300.cn/100001_2012215089/package_TK499duino_index.json 
error code is: 403

**Comment by jantje** [comment]
Error 403 sounds like a local security issue
https://en.wikipedia.org/wiki/HTTP_403

**Comment by jantje** [comment]
Closing as been open without activity for a long time.
Please reopen if you disagree
