### ISSUE TITLE
V5.0 testing regression with multiple ino files. line endings are not inserted as sloeber.ino.cpp is generated.

### ISSUE THREAD

**Issue by JAndrassy** [Sloeber/arduino-eclipse-plugin#1662]
**environment**   
Sloeber	5.0.0.202408132335	io.sloeber.product	
Windows 10

**Describe the bug**   
my project has multiple ino files. in sloeber.ino.cpp after the main ino file, the includes for all other ino files are in one line. line endings are not inserted as the file is generated.

**To Reproduce**   

1. create a project with at least 3 ino files
2. verify
3. see the end of the sloeber.ino.cpp file

**Comment by jantje** [comment]
I told you there would be bugs ;-)
Thanks for testing 👍

**Comment by jantje** [comment]
I fixed this but there are unrelated build issues and therefore no new action build.
