### ISSUE TITLE
V5.0 testing: Intro error

### ISSUE THREAD

**Issue by PerennialNovice** [Sloeber/arduino-eclipse-plugin#1673]
with version 5.0.0.202408181423, right after first startup, I get the following error message:

![image](https://github.com/user-attachments/assets/98c4fd69-efd5-4a6d-88d7-aa15de560998)

**Comment by PerennialNovice** [comment]
and sporadically I get an Index 0 out of bounds messag:

![image](https://github.com/user-attachments/assets/e7c70d3d-f966-454b-84c0-f97006229e3d)

**Comment by jantje** [comment]
Can you provide the logs?

**Comment by PerennialNovice** [comment]
sure, hope it is the right thing ...

There are some lines about messed up project configurations in there too. As far as I can tell, this is unrelated to V5.0

[errorlog.log](https://github.com/user-attachments/files/16675320/errorlog.log)

**Comment by jantje** [comment]
The error log tells me you tried to open a pre V5.0 workspace.
V5.0 is really 100% CDT project incompatible with previous versions and I have not yet considered the migration problem.
Only the error below might be Sloeber V5.0 related.
`java.io.FileNotFoundException: C:\Sloeber_Nightly\introContent.xml (The system cannot find the file specified)`

Please do not use existing V4.X.Y sloeber workspaces for testing right now. We are not there yet.

**Comment by PerennialNovice** [comment]
in fact, I created a new workspace but imported an existing project from git.
With config files like .project, .sproject etc ...
I guess that is a problem too, then?

**Comment by PerennialNovice** [comment]
allright, that's the path to follow then!

Thanks for enlightening me :)

**Comment by jantje** [comment]
Closing this issue as user error.
Please reopen if you disagree
