### ISSUE TITLE
Project can build but indexer is not working on ESP32-2.0.17

### ISSUE THREAD

**Issue by Nakio195** [Sloeber/arduino-eclipse-plugin#1686]
**First of all, so many thanks for your work, it's been 4 years I'm using Sloeber and it's just fantastic, !**

**Describe your environment**   

- Sloeber Product version 4.4.3 on Windows 10

**Describe the bug**   
On a fresh install and in a new workspace with the esp32-2.0.17 (so the last one before the 3.0.0 on which I get troubles as mentionned in #1649 and #1652 ), the project builds and upload but the indexer is not working at all.

**To Reproduce**   

1. Install Sloeber 4.4.3 product
2. Add ESP32-2.0.17
3. Create a simple project for a ESP32 Board (in my case WEMOS ESP32 MINI)
4. The project builds but the indexer doesn't recognize anythings from pinMode to uint8
5. Create a simple project for Arduino UNO, or ESP8266 
6. The projects builds and the indexer is ok

![image](https://github.com/user-attachments/assets/d088e086-c140-4f38-8cd3-5a459e8a26fd)

**Expected behavior**   
The indexer doesn't seem to parse the includes

I tested on the last Nightly Build and the indexer is working fine.

Here are some screenshots, the workspace thats shows that there is no "Includes" folder in the ESP32 project
![Workspace](https://github.com/user-attachments/assets/06ea70c4-8753-4278-afa9-4c4d95d363c2)

The indexer working fine on a uno project and not working on the ESP32
![IndexerUno](https://github.com/user-attachments/assets/daa301cf-1c0e-4c70-af43-95ede8e6fa3a)
![NoIndexer](https://github.com/user-attachments/assets/340d31d2-410c-48d7-866c-fcd128412252)

The Paths settings showing an empty configuration on the ESP32 in opposition with a lot of things on a ESP8266 project
![PrepocESP8266](https://github.com/user-attachments/assets/fefbc061-a4f7-40e0-8fd6-18a61ad4ad91)
![PrepocESP32_2 0 17](https://github.com/user-attachments/assets/f11e6882-6000-4723-bc89-397c59ac77a8)

Here are two pastebins showing the result of the indexer log for the two main of the project for a ESP32 and for the UNO
https://pastebin.com/NH5EGNsM  --> ESP32
https://pastebin.com/5hzT9vnU --> ESP8266

I also tried on Sloeber 4.4.2, same result. Maybe it comes from the ESP32 2.0.17 or from my setup, but I can't find a way to add the includes path to be processed in Prepoc tabs under C / C++ General > Preprocessor Include Path, Macros, etc... > Entries

Even if the build succeed it is quite unusable working on a all red underlined code....

**Comment by jantje** [comment]
There are quite a bit of issues with the ESP releases (both due to ESP and Sloeber)
Version 5 (trying to finalize it this year) fixes some (hopefully all) of the Sloeber related issues.
