### ISSUE TITLE
STM32 Support for Sloeber?

### ISSUE THREAD

**Issue by DocAlex** [Sloeber/arduino-eclipse-plugin#1698]
Hello,

I am using Sloeber frequently for arduino projects. Thank you for the tool.

Now I installed STM32Duino to support STM 32 boards. 

In the Arduino IDE its working perfectly (see image). I can generate code for the board an can upload it via the nucleo ST-link Programmer. 

![2024-12-10 18_26_06-Blink _ Arduino IDE 2 3 4](https://github.com/user-attachments/assets/5016f5f4-e359-4927-88ca-f979e4a4d803)

I undestood that sloeber uses the Arduino environment and expected to find the same boards with STM32 processor as well. 

unfortunately that is not the case: (see image):

![2024-12-10 18_22_38-sloeber-workspace - TST_SGP41_Sensirion_lib_Compensation_TST_SGP41_Sensirion_lib](https://github.com/user-attachments/assets/bb5760dc-f493-4a8f-aab9-ec69b9be210d)

Did I miss anything? 

Thank you in advance

Alexander

**Comment by jantje** [comment]
You will not find the STM32 boards in the arduino AVR boards.txt
![image](https://github.com/user-attachments/assets/5112a28f-88c1-4300-a7ea-4d958caf6ff9)
And if you do not find the STM32 boards.txt ... did you install it using the sloeber boards manager?

All that being said; there are some problems with the STM32 boards and the indexer and Sloeber.

**Comment by PerennialNovice** [comment]
Have a look over here at the STM32duino project:
[https://github.com/stm32duino/Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32)

In sloeber, from the top menubar choose "sloeber" -> "preferences" -> "Third party index urls" and add the url `https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json`
now you can choose STM32 under "sloeber" -> "preferences" -> "platforms and boards"

![image](https://github.com/user-attachments/assets/3ff801fd-4595-4cd2-8a74-73f80fe393de)

and click Apply and Close
have some patience until everything is downloaded and installed and after that you can select the STM32 platform in the project settings
