### ISSUE TITLE
Flaw revealed by Arduino V2

### ISSUE THREAD

**Issue by Dan-Essin** [Sloeber/arduino-eclipse-plugin#1700]
**Describe your environment**   
Eclipse 2024-12 with Sloeber plugin 4.4.3
Do you use the Sloeber product or plugin?   

OS: Debian 12
The url of the json that you used to download the platform  
A image of the project properties arduino showing the board settings   

**Describe the bug**   
Although "There is no dependency on the Arduino IDE" the Arduino v2 ide puts the libraries and hardware in a hidden folder - .arduino15
Why 15? I have no idea

When setting the Sloeber prefs, it is necessaty to add these locations because the sepplied defaults are for Arduiino 1.8.

I am using the R4 wifi board which is new and not supported by 1.8.
I also have 1.8 instadded

Clicking add brings up a dialog that hides all hidden folders making it impossible to add the folders found in .arduino15

**To Reproduce**   
This is self explanatory - see above

**Expected behavior**   
folder chooser shows all folders, not just "normal" ones
Also, it should be allowed to manually enter the folder paths without usind the folder browse window

**Data to back up your claim**   
If applicable, add screenshots, console output and/or logs to help explain your problem.   

**Additional context**   
There are, no doubt, workarounds to this problem such as editing config files but I'm too stupid to figure any of that undocumented stuff out. My main objective is to get my arduino projects going. I have already spent 4 hours and multiple reinstalls of Sloeber just to get to this point.

![Screenshot_2024-12-14_11-13-03](https://github.com/user-attachments/assets/e93831d6-1d48-46e7-91f4-aea4fb8cbe0e)

**Comment by jantje** [comment]
Sloeber has its own boardsmanager and library manager.
You should not reference Arduino IDE installed stuff.
