### ISSUE TITLE
Eclipse crashes when connecting to serial monitor

### ISSUE THREAD

**Issue by skutov** [Sloeber/arduino-eclipse-plugin#193]
Running V2.2 of the plug in on eclipse C++ Luna edition under Ubuntu x64 14.04. When attempting to connect to a serial device (specifically an Uno on /dev/ttyACM0) through the serial monitor eclipse freezes and then crashes. The hardware functions correctly with the IDE and uploading to the board from Eclipse seems to work correctly.

When trying to connect the monitor view says "Connected to /dev/ttyACM0 at 57600"  eclipse then freezes and crashes a few moments later. I have tried all baudrates and connecting different devices at a range of addresses.

**Comment by saurjk** [comment]
How did it work? I copied the rxtx library over to [arduino]/lib but my eclipse still crashes when connecting to the serial monitor. Totally perplexed.

**Comment by jantje** [comment]
try upgrading to the nightly. That one no longer uses rxtx.

**Comment by saurjk** [comment]
No dice, the nightly keeps crashing when I try to set New File Type, or see properties of a project.

**Comment by jantje** [comment]
It looks like there is something major wrong on your system.
I think so because the New File Type is a pure CDT functionality. If that crashes it means CDT or even the eclipse framework itself is crashing.

**Comment by saurjk** [comment]
apparently eclipse was crashing because of the gtk appearance theme in KDE. I had to change a file in gtk to fix the issue. It works now. Thanks

**Comment by jantje** [comment]
great you found the issue

**Comment by sgoudelis** [comment]
I have the same issue too. @saurjk what file did you modify and how to fix this ?

**Comment by saurjk** [comment]
I did the one in here:

http://askubuntu.com/questions/396410/eclipse-auto-shutdowns-when-creating-new-project

editing the gtkrc file under /usr/share/themes/oxygen-gtk/gtk-2.0/ as explained in http://stackoverflow.com/questions/26436009/eclipse-luna-crashes-on-new-project-in-ubuntu finally did the trick. Change this line:

 GtkComboBox::appears-as-list = 1

into:

 GtkComboBox::appears-as-list = 0
