### ISSUE TITLE
.settings\org.eclipse.cdt.core.prefs file gets tainted every time the project is opened again

### ISSUE THREAD

**Issue by dniklaus** [Sloeber/arduino-eclipse-plugin#243]
With the EclipseArduino bundle, nightly build version 2015-04-24_02-06-01 (after switching from 2015-04-09_02-06-59), I have now an issue with the following two lines changing on every project re-open action:

```
environment/project/it.baeyens.arduino.core.toolChain.release.256903333/A.EXTRA.TIME.LOCAL/value=1430156500
environment/project/it.baeyens.arduino.core.toolChain.release.256903333/A.EXTRA.TIME.UTC/value=1430149300
```

This brings in some sort of discomfort as long as the project is under version control.

Why has this been changed?

**Comment by jantje** [comment]
This has to do with Teensy. Teensy needs these linking defines that are basically current date and time.
See here for more detail 
https://forum.pjrc.com/threads/27740-Arduino-1-6-0-any-plans-to-support-it?p=64812&viewfull=1#post64812

**Comment by dniklaus** [comment]
Sad story... Maybe you want to just set these to 0, as Paul Stoffregen suggests to do beside other options. And/or make the usage of the feature switchable...

**Comment by jantje** [comment]
Using 0 is not an option. Teensy would not work properly and I plan to use this feature as I already mentioned in the thread mentioned above.
Adding a switch may be an option. Default on.
Maybe there are already defines that can be used to make this static (my preferred option)
Anyway,I accept the issue as being limiting for version control (even forcing manual merges) but it is not high on my to do list.
Jantje

**Comment by dniklaus** [comment]
Ok, thank you!

**Comment by jantje** [comment]
Now the question is.... what is the easiest way to test  this.
Note that for this to work you can not use environment expansion for makefiles otherwise the same problem still exists

**Comment by uzi18** [comment]
Copy before use, to backup file

**Comment by jantje** [comment]
@uzi18  rofl I was only joking :-)

**Comment by jantje** [comment]
I just tested on my working workspace and it worked. I fear it did introduce another issue so do not update unless you really need this
