### ISSUE TITLE
examples with the character minus (-) in the foldername are not processedproperly

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#475]
Basically the - is seen as a new folder indicator

**Comment by wimjongman** [comment]
Should you not always quote folder names?

**Comment by jantje** [comment]
I mean in the create new sketch "using example code" and the example folder is named haha/folder/1-2-3 the wizard will show
haha->folder->1->2->3 So it looks like the folder name is haha/folder/1/2/3
