### ISSUE TITLE
serial monitor: auto-clear on start/reset

### ISSUE THREAD

**Issue by jonbarril** [Sloeber/arduino-eclipse-plugin#502]
Appending new output to old output is often confusing.  An option to auto-clear the output would be helpful, such as upon upload and/or upon reset.

**Comment by jantje** [comment]
As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by jrobert-gh** [comment]
jantje, I agree this would be a useful addition.

**Comment by jantje** [comment]
@jrobert-gh Are you a sponsor@patreon?

**Comment by jrobert-gh** [comment]
Yes, as 'JRobert'.

JRobert

**Comment by jantje** [comment]
If you support a issue as patron best what you can do is post the issue number here https://www.patreon.com/posts/i-support-issue-3700469.

**Comment by jantje** [comment]
I'll have a look at this when I'm in this area. I'm a bit bussy with adding testing right now.

**Comment by jrobert-gh** [comment]
Thanks.

**Comment by jantje** [comment]
It turned out to be relatively easy. Can you test after 06:00 GMT?

**Comment by jrobert-gh** [comment]
I sure will - thanks!

**Comment by jrobert-gh** [comment]
Worked for me. Thanks, Jantje.

**Comment by jantje** [comment]
txs for confirming
