### ISSUE TITLE
Refactor it.baeyens to io.sloeber

### ISSUE THREAD

**Issue by wimjongman** [Sloeber/arduino-eclipse-plugin#533]
Tracking issue.

**Comment by wimjongman** [comment]
Hi, I have refactored most of the code to where I now have a running Sloeber. 

I can:

* Build
* Run
* Create a sketch
* Compile a sketch
* Upload sketch to board

I cannot

* See a splash
* Get to the project properties to change the com port and board

I have created the "refactor" branche in my repo which is on top of the current jantje repo.

**Comment by wimjongman** [comment]
![2016-09-05_1902](https://cloud.githubusercontent.com/assets/180969/18254188/7cc4d7b8-739b-11e6-8452-dbd0bff26615.png)

**Comment by jantje** [comment]
>Get to the project properties to change the com port and board

That is wierd
