### ISSUE TITLE
USBtinyisp (ATtiny) programmer generates a null pointer exception in version 1.1.0

### ISSUE THREAD

**Issue by lakidd** [Sloeber/arduino-eclipse-plugin#537]
As per  patreon.com/posts/3700469
I'm using the ATTinyCore here
https://github.com/SpenceKonde/ATTinyCore
And it lets me select Upload Protocol to select the programmer.
USBasp (ATtiny) works fine but USBtinyisp (ATtiny) generates a NullPointerException
![2016-09-22_20-46-07](https://cloud.githubusercontent.com/assets/7076901/18745503/c18e2daa-8105-11e6-95b4-4d1dfffe7560.png)
I can't seem to find how to generate a stack trace ?

**Comment by jantje** [comment]
I can reproduce the error here with 1.1.0 but there is no problem with 1.1.1.
So I guess there is something "wrong" in 1.1.0. A nicer message should be given though.
As we're in refactoring right now I can't work on that error right now.

If you do not see version 1.1.1 goto windows->preferences>arduino locations and check update local json files (including library) select ok, wait a while and try again.

**Comment by lakidd** [comment]
Yep, that fixes it for me too. Thanks, I'll use 1.1.1

**Comment by jantje** [comment]
txs for the feedback :-)

**Comment by jantje** [comment]
I replaced the null pointer error with a nicer message.

**Comment by lakidd** [comment]
Awesome thanks Jantje !
