### ISSUE TITLE
boardid.upload.tool=arduino:avrdude is not supported. FI for adafruit flora

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#552]
Upload to adafruit flora does not work because the upload is referencing arduino:avrdude.
For the flora it might be a workaround to change the boards.txt to
flora8.upload.tool=avrdude
But I have no flora to test :-(

**Comment by davidtopham** [comment]
After your recent commits this seems to be working now without having to change the boards.txt file at all

**Comment by jantje** [comment]
Thanks for the input. Yes indeed that was the intention. The change was just for testing.
As I thought it was a hard change. I've been through quite some iterations.
