### ISSUE TITLE
ota problem

### ISSUE THREAD

**Issue by simondid** [Sloeber/arduino-eclipse-plugin#553]
hey

arduino ide version 1.6.9
eclipse version 4.5.2
 Arduino Eclipse Extensions 3.1.0.201609060208
bord : nodemcu esp-12e

So i'm trying to get ota upload to work with in eclipse with your plugin :P i can upload from Arduino ide(version 1.6.8) with no problem and same code but when i tray in eclipse i prompted a login screen
![untitled](https://cloud.githubusercontent.com/assets/3244827/19593369/956b5d56-9780-11e6-91ea-ef6062a68c81.png)

i trayed the following logins 

Login = 123 and whatever i set the hostname to 
Password = 123 ore nothing

Then what ever i put in the login boxes it start trying to upload and i get the following messages

> Starting upload
> using ssh loader
> 
> java.net.UnknownHostException:
> 
> myesp8266.local
> 
> failed to upload 

![untitled2](https://cloud.githubusercontent.com/assets/3244827/19593490/1df3bfec-9781-11e6-8f6d-47d5c8b6a444.png)

When I am trying to google the problem, it seems that you have figured it out but I has not made it to reals ore is this still and issue.

also anothere question ota can be don via a web based upload but i can't find the "cpp.bin" ore "ino.bin" file that i shut upload is the eclipse generating such a file? never mind figured out that in the releas folder a projectname.bin files exist witch works but it gives me anothere question whats the diffrence one the projectname.bin file and the randomdomeFilename.bin

**Comment by jantje** [comment]
As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
