### ISSUE TITLE
Add support for Oxygen

### ISSUE THREAD

**Issue by wimjongman** [Sloeber/arduino-eclipse-plugin#574]

**Comment by jantje** [comment]
Should we upgrade the product to oxygen?

**Comment by jantje** [comment]
@wimjongman Do we keep this open to move the product to oxygen or can we close this as it doesn't impact the end user??

**Comment by wimjongman** [comment]
This is the ticket to prepare for Oxygen. We will switch once it is out in
2017.

**Comment by mattb5906** [comment]
Just being nosey: what is Oxygen?

**Comment by jantje** [comment]
The new version of eclipse not yet released as a stable version.

**Comment by mattb5906** [comment]
Ah, of course. Thanks Jantje.

**Comment by jantje** [comment]
I moved to oxygen for the development environment :-)

**Comment by jantje** [comment]
@wimjongman I guess this is done except for #792. So it can be closed.

**Comment by wimjongman** [comment]
Close

**Comment by mjmeijer** [comment]
mvn clean verify -Pmac64,oxygen fails...
```
Resolving dependencies of MavenProject: com.github.brodykenrick.arduino-eclipse-plugin:io.sloeber.updatesite:4.0.1-SNAPSHOT @ /Users/maarten/git/arduino-eclipse-plugin/io.sloeber.updatesite/pom.xml
[INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: io.sloeber.updatesite raw:4.0.1.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.0.1-SNAPSHOT
[ERROR]   Missing requirement: io.sloeber.updatesite raw:4.0.1.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.0.1-SNAPSHOT requires 'org.eclipse.cdt.feature.group [9.0.0.201606062011]' but it could not be found
```

**Comment by mjmeijer** [comment]
In /io.sloeber.updatesite/category.xml remove this for build to work...

`   <feature url="features/org.eclipse.cdt_9.0.0.201606062011.jar" id="org.eclipse.cdt" version="9.0.0.201606062011">
      <category name="Dependencies"/>
   </feature>
`

**Comment by jantje** [comment]
![afbeelding](https://user-images.githubusercontent.com/1175841/30163037-a6604c94-93d7-11e7-9f7f-b435f2b92132.png)

I think it is strange the build succeeds here -I'm not saying you are wrong!!!-
I also dumped my version  platform info and as far as I understand this I'm on 4.7.0.
As far as I remember I tried to upgrade using eclipse upgrade procedure (after having read a article it works fine) and f'ed-up my installation.  So I reinstalled Sloeber. I guess I took a copy from sonatype.

I'm  running mvm clean verify -Pall,oxygen on my sytem and I'll check the eclipse version  it generated.

**Comment by jantje** [comment]
As far as I remember
`<feature url="features/org.eclipse.cdt_9.0.0.201606062011.jar" id="org.eclipse.cdt" version="9.0.0.201606062011"> <category name="Dependencies"/> </feature>`
is there to enable the installation of cdt when installing from base eclipse.
Maybe the version number needs to be updated. But this should not impact the product.
On my install cdt is on 9.3

**Comment by jantje** [comment]
Strangely enough the local build fails now and the jenkins build works fine :-s
![afbeelding](https://user-images.githubusercontent.com/1175841/30164628-6cfeaf1c-93dd-11e7-89f2-29795871f577.png)
I'm on master. Only with a additional toolchain in the plugin.xml of io.sloeber.core.

**Comment by jantje** [comment]
The local build worked fine and both 64 and 32 bit versions return 4.7
![afbeelding](https://user-images.githubusercontent.com/1175841/30189577-1c75cf50-9435-11e7-9b5d-b2ce691b3f3d.png)

**Comment by jantje** [comment]
given the latest progress I think we can close this issue.

**Comment by git1234567890** [comment]
Just to let you know. Installed a fresh Oxygen and added (Marketplace) you plugin.
../Relase/subdir.mk referred ..//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++ ... that folder was not there /arduinoPlugin/packages/arduino/tools!
But with softlinks to the referred programs to the arduino IDE libraries 4.9.2-atmel3.5.4-arduino2 -> /opt/arduino/hardware/tools/avr ALL WORKS FINE!
