### ISSUE TITLE
There is no monitor when installing boards

### ISSUE THREAD

**Issue by felichsm** [Sloeber/arduino-eclipse-plugin#584]
Creating a ESP8266 project after installing the ESP8266 to the Sloeber plugin via the Board Manager, the Projects have a lot errors. They are missing libraries, as well as tools like the compiler and upload tool. 
I figured out, that the needed folders (libraries and build tools) are not installed.
I solved the problem with the steps that I described in this forum post: http://forum.arduino.cc/index.php?topic=413731.0

**Comment by jantje** [comment]
I guess you didn't wait untill the install was done.
