### ISSUE TITLE
Remove dependency on org.eclipse.wb.core.lib

### ISSUE THREAD

**Issue by mjmeijer** [Sloeber/arduino-eclipse-plugin#606]
It is included because it provides (an older version of) `org.apache.commons.lang`
The fix is to include `org.apache.commons.lang 2.6.0` directly from the eclipse orbit site
This affects all OS versions and plugin `io.sloeber.ui `
Please assign to me

**Comment by jantje** [comment]
@mjmeijer Is still valid?
