### ISSUE TITLE
Make default workspace appear in Documents or My Documents

### ISSUE THREAD

**Issue by mjmeijer** [Sloeber/arduino-eclipse-plugin#613]
The default workspace when Sloeber is first starting now appears in the application root folder that is not accessible for beginner type users on Mac. In my view workspace is a document and should appear in the platform default location:

- windows in "\<username\>\My Documents"
- linux in "\<username\>\Documents"
- macosx in "\<username\>\Documents"

This used to be through defining custom config.ini but Maven/Tycho build does not support that.
The proper way is via p2.inf for which I will provide a patch once assigned to me

**Comment by mjmeijer** [comment]
Create a p2.inf file that takes care of setting this up during Tycho build and export. Would look like this on Linux and similar on other platforms.
![screen shot 2016-12-28 at 20 57 26](https://cloud.githubusercontent.com/assets/2027490/21534155/12084dca-cd63-11e6-9535-37e32230ad35.png)

**Comment by jantje** [comment]
ok. Seems like a good idea.

**Comment by universpharmacie** [comment]
The advantage of having it in the Documents folder is (if you use macOS Sierra) that everything is automatically backed up / synchronized towards iCloud. Thus: Great idea!

**Comment by dgolda** [comment]
Beware of filenames with spaces on Windows! I've got a problem with workspce created in My Documents.
BTW, on Windows 10 there is no more My Documents folder but just Documents.

**Comment by mjmeijer** [comment]
Great Tip, we'll change it right @jantje ?

**Comment by jantje** [comment]
>Beware of filenames with spaces on Windows!

Actually on all OS'es. Correctly quoting is not so easy and os and tool dependent.

>Great Tip, we'll change it right @jantje ?
How do you propose to change it?

**Comment by mjmeijer** [comment]
I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=510071

**Comment by mjmeijer** [comment]
Before release and resolution we can move to @user.home fro win32 only in p2.inf file.

**Comment by jantje** [comment]
I propose for now to keep windows in the old way.
I want setup some test environments so I can test spaces.

**Comment by jantje** [comment]
I think this is fixed in V4 or am I wrong?

**Comment by jantje** [comment]
This is fixed in windows.
@mjmeijer 
Does it work as planned on Mac
