### ISSUE TITLE
When only one platform is installed there are no boards to select in the New Sketch wizard

### ISSUE THREAD

**Issue by mjmeijer** [Sloeber/arduino-eclipse-plugin#615]
Both built and from Eclipse the New Sketch Wizard does not work on Mac. Both boards and upload protocol are not filled in. And the Port menu is not resistant to plugging in and out boards while dialog is open.
Using null parameter as switch in BoardDescriptor means get from preferences, that are never initialized? Also though it is said one can change settings later, that is not possible as finish button is disabled.
Also the size is far too wide for the buttons, where does this come from? I cannot shrink without buttons going off screen
![screen shot 2016-12-29 at 13 36 44](https://cloud.githubusercontent.com/assets/2027490/21544013/01104a40-cdcc-11e6-9b7b-420690a0f877.png)

**Comment by mjmeijer** [comment]
Does not work from nightly on Linux either...

**Comment by jantje** [comment]
I guess something is not behaving as you expect as universpharmacie reports using V4 and he works on mac.
There are size issues in V4. I did some work on hiding none used fields but that seems to cause issues in to many occasions. Doing a resize fixes it.
If only a swt expert could have a look ;-)

**Comment by universpharmacie** [comment]
Can not reproduce the issue, at least not for the Teensy processors - I don't work with any others - 8bit is evil! ;-) . After going once into Preferences -> Arduino -> Private hardware path and setting it to '/Applications/Arduino.app/Contents/Java/hardware/teensy/avr', the 'New sketch' wizard works always fine for me (see attached pic)
![capture d ecran 2016-12-30 a 12 12 11](https://cloud.githubusercontent.com/assets/1315464/21564124/001c1344-ce8a-11e6-97a2-b51f1395a831.png)

**Comment by jantje** [comment]
glad to see the gaps between the options are gone on mac as well :-)

**Comment by jantje** [comment]
@mjmeijer 
have you been able to find out what causes the confusion/problem?

**Comment by mjmeijer** [comment]
I can now get it to work after adding some custom hardware and libraries paths, so it has something to do with PreferenceInitializer I think. Will ook into it later. My patch works on my branch, now get from upstream, rebase and push branch then do pull request right?

**Comment by jantje** [comment]
>My patch works on my branch, now get from upstream, rebase and push branch then do pull request right?

Something like that yes ;-)

**Comment by wimjongman** [comment]
Yes.⁣

**Comment by mjmeijer** [comment]
Out of the box, there is a single boards.txt file and the board file menu is hidden, but as selection is not set the other menus are never initialized. Fix is to force selection after the listeners are in place.
I would like to take the liberty to also do some refactoring and renaming to become more Java-like. OK?

**Comment by jantje** [comment]
Be careful when refactoring. This is inherited code that is used in both the wizard and the project properties.
Which means that it fits in 2 "gui integration frameworks" which has it's trick.

As to the problem.
It is quite possible that when only 1 boards.txt file is found the combo is not properly initialized.
This may be so because comparing file names in eclipse is tricky due to the many compatibility options. I had some issues there with the last used stuff so it may have hit us in the "brand new installation" as well.
As we are at it it might be better not to hide the combo. I'm saying this based on feedback I got.

**Comment by mjmeijer** [comment]
When running from Eclipse IDE that combo also becomes very wide because of long path length. I have that fixed as well, looking like this:
![screen shot 2017-01-02 at 16 39 58](https://cloud.githubusercontent.com/assets/2027490/21592069/863ab002-d10a-11e6-87f6-8fe9044254ed.png)
I will test it with both new wizard and properties on project, on Mac and Linux before committing.
If you want I can stop hiding the Combo as well.

**Comment by jantje** [comment]
>When running from Eclipse IDE that combo also becomes very wide because of long path length. I have that fixed as well, looking like this:

Great. I have been looking at this :-)

>If you want I can stop hiding the Combo as well.

please do

**Comment by mjmeijer** [comment]
![linux](https://cloud.githubusercontent.com/assets/2027490/21593363/731529a6-d116-11e6-886c-f9deb5754e18.png)
Shortening also works on Linux...
