### ISSUE TITLE
Change maven group id

### ISSUE THREAD

**Issue by wimjongman** [Sloeber/arduino-eclipse-plugin#641]
The current group id is "com.github.brodykenrick.arduino-eclipse-plugin". I want to rename that to io.sloeber.

Does anyone recall why the group id was named like this?

**Comment by jantje** [comment]
Because @brodykenrick did this and his account is used for the publish.
If we change this we will also need to create a new publish account and change the links on the nightly install page

**Comment by wimjongman** [comment]
Thanks for the ping.

**Comment by jantje** [comment]
Because travis is no longer used the cleanup was relatively easy.
I think we can close this issue
Please reopen if not.
