### ISSUE TITLE
add support for ssh upload with yun

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#645]
Currently only upload via username and password is supported.

**Comment by jantje** [comment]
Also a bug makes it impossible to change/add a username/password.

**Comment by jantje** [comment]
Note that when going to [yun].local->login->configure->advanced configuration panel->system administration the ssh key should be on 1 line starting with the encryption type followed with 1 space. which is in my case ssh-rsa

![afbeelding](https://cloud.githubusercontent.com/assets/1175841/23613103/5445fb2e-027e-11e7-90ab-6b83905ab855.png)

**Comment by jantje** [comment]
Setting/deleting passwords can be done in project properties->arduino
![afbeelding](https://cloud.githubusercontent.com/assets/1175841/23613295/24bdf680-027f-11e7-9ec2-cd1bc7acad2d.png)
Which gives you this page
![afbeelding](https://cloud.githubusercontent.com/assets/1175841/23613319/4102f32c-027f-11e7-86e9-2872f715db2a.png)
note the page will only show up when the port is a "accepted" machine name

**Comment by mjmeijer** [comment]
Shouldn't that password dialog be a real password dialog, using SWT.PASSWORD as per https://goo.gl/vUz3Mn ??

**Comment by jantje** [comment]
@mjmeijer 
I assume you propose to use a password edit box (one that shows * instead of the letters)
I prefer to see the password (I'm dyslectic) but a checkbox "show password" suits both needs.
If you want it secure; you should go for public private key. 
What I'm trying to say: "I can't be bothered. But if you can ... be my guest."
