### ISSUE TITLE
V4 ESP8266 cannot create new Sketch (Finish Button)

### ISSUE THREAD

**Issue by darkhedie** [Sloeber/arduino-eclipse-plugin#649]
Hello

I just downloaded the latest Sloeber V4 IDE.
I have added the ESP8266 Packager with window->preferences -> arduino -> platforms and boards -> esp8266 -> esp8266 -> 2.3.0 

It was downloaded without problems. 

After that it tried to create a new sketch. 
Unfortunately, i am not be able to click the "finish" button. 
The button is grayed out. 
If i chose the arduino (atmel) from the dropdown list as platform folder, then i am able to click finish. 

System: 
Win10 x64
Latest Java (8 update 121)
IDE: Precompiled from here: http://eclipse.baeyens.it/

![sloeber__esp8266v](https://cloud.githubusercontent.com/assets/6323250/22463519/3fd27352-e7b2-11e6-9fb6-816dc2101744.png)

#EDIT: Can be closed, the windows was not streched enough.

**Comment by jantje** [comment]
seems like the resize didn't work for you

**Comment by tischmi** [comment]
it's Works!!!

**Comment by Gizmodo** [comment]
Same problem with window resize 
![image](https://user-images.githubusercontent.com/1078610/62203937-d4e7bf00-b394-11e9-8dc7-4be7977c6b5c.png)
