### ISSUE TITLE
'No project found to build'  should hint at not being in the correct perspective

### ISSUE THREAD

**Issue by judge2005** [Sloeber/arduino-eclipse-plugin#671]
[eclipse.log.zip](https://github.com/Sloeber/arduino-eclipse-plugin/files/820003/eclipse.log.zip)

In io.sloeber.core.ui. This is with a new install of neon and Sloeber latest stable build. There are a whole bunch of errors...

**Comment by judge2005** [comment]
Ignore me. I needed to switch to the arduino perspective. I'll let you decide if you just want to delete this issue!

**Comment by jantje** [comment]
Don't worry. Happened to me as well. I'll add the hint to the message that maybe the perspective is wrong.
