### ISSUE TITLE
 install libraries in sloeber on usage 

### ISSUE THREAD

**Issue by atanisoft** [Sloeber/arduino-eclipse-plugin#679]
It would be great if these libraries could be added to the default available set:
https://github.com/me-no-dev/ESPAsyncWebServer
https://github.com/me-no-dev/ESPAsyncTCP
https://github.com/me-no-dev/ESPAsyncUDP

**Comment by jantje** [comment]
These look like ESP specific libraries and as such should not be on the default list.
I'm considering adding libraries that are not found automatically which should fix this.

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by atanisoft** [comment]
Yes they are ESP specific, is it possible to have a set of default libraries for ESP and a default for Arduino?

**Comment by jantje** [comment]
>is it possible to have a set of default libraries for ESP and a default for Arduino?

Without serious sponsoring I'm not going there.
But importing libraries on usage is something I have on my wish list

**Comment by jantje** [comment]
it is actually install as the library is imported in the project.

**Comment by jantje** [comment]
Please look at issue #825 to set your cdt indexer setting for this feature to work fine.
