### ISSUE TITLE
Including single library

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#685]
When I configure the "Private Library path" with a path of a library like this 

![libs](https://cloud.githubusercontent.com/assets/4587225/24073247/d88124ac-0bf4-11e7-8041-1835c1a52052.JPG)

I get the subdirectories in the list of libraries to include

![liblist](https://cloud.githubusercontent.com/assets/4587225/24073278/57811c44-0bf5-11e7-94d9-bf88112936ca.JPG)

This also shows up in the project library list : 

![liblist2](https://cloud.githubusercontent.com/assets/4587225/24073296/c6cff73c-0bf5-11e7-8830-340b93841773.JPG)

When both of the libraries have the same subfolder (in this case src) only one is available for the project.

**Comment by jantje** [comment]
You need to add the parent of the libraries in other words the libraries folder.
In your case that would be C:\userdata.

**Comment by hreintke** [comment]
I can to that but then I get a lot of "Arduino libraries" which are folders with completely other content.
What is the condition on which a subdirectory is considered as a library ?

**Comment by jantje** [comment]
It is the arduino ide model ..../libraries/[your libraries]/examples
Sloeber wants to know .../libraries

**Comment by hreintke** [comment]
I understand the ../libraries.
My question is on the subdirectories beneath that. 
My c:\userdata contains a lot of non-arduino subdirectories which have a complete other structure and no library.properties. But these do show up in the list of libraries when adding a library to the project.

**Comment by jantje** [comment]
Sloeber doesn't care about library.properties. All subfolders are considered libraries

**Comment by hreintke** [comment]
OK, clear
