### ISSUE TITLE
Setting up plugin dev environment

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#689]
Hi,
Try to setup an eclipse environment for building arduino-plugin.
Based on the description from the readme.

This is the resulting environment : 
Eclipse installed software : 

![ins](https://cloud.githubusercontent.com/assets/4587225/24244155/0ea07534-0fbe-11e7-9f23-57f3bbabffa7.JPG)

These are the project when including using git import

![pe](https://cloud.githubusercontent.com/assets/4587225/24244189/2e81cea2-0fbe-11e7-8ed5-7e6048682b49.JPG)

These are the error I get after import : 

![pb](https://cloud.githubusercontent.com/assets/4587225/24244218/41b0ed3c-0fbe-11e7-8a18-dfb007ed79e3.JPG)

Ant hints where I have made a mistake/missing parts ?

**Comment by jantje** [comment]
Do you have the cdt build environment?

**Comment by hreintke** [comment]
Thanks, I indeed missed the C++ tools.

Working as expected now.
