### ISSUE TITLE
Add support for BBC micro:bit board

### ISSUE THREAD

**Issue by mjmeijer** [Sloeber/arduino-eclipse-plugin#703]
Sloeber can provide tools for all open hardware boards, and I think the micro:bit is one that is well supported in education, but only offers an online tool set using mbed architecture.

All about micro:bit http://microbit.org
Getting Started With C/C++ On The Micro:bit http://bit.ly/2oMGuvp

**Comment by jantje** [comment]
Feel free.
If you want to make it a arduino board the core will be the hardest.

**Comment by mjmeijer** [comment]
More info on using mbed with Eclipse here:
https://developer.mbed.org/cookbook/eclipse-for-building-and-debugging

**Comment by jantje** [comment]
Just tested the board explicitly and it works fine.
The json is also part of the buildandcompile test which tested the board under linux and windows.
Waiting for a mac tester ;-)

**Comment by liebman** [comment]
I should have one by this weekend, I'll give it a try.

**Comment by jantje** [comment]
:-) then the upload can be tested as well :-)

**Comment by liebman** [comment]
confirmed: Both compilation and upload work from MacOS

**Comment by jantje** [comment]
@liebman thanks :-)
