### ISSUE TITLE
Homie framework fails with exception

### ISSUE THREAD

**Issue by DavidR1953** [Sloeber/arduino-eclipse-plugin#707]
Jan - I started this question on Patreon, where you kindly offered to look at the build output.
The Homie framework (https://github.com/marvinroger/homie-esp8266) builds OK in Sloeber but crashes with an exception. Using Sloeber 4.0.0.201701171403
The same code builds and runs with PlatformIO
Here are the two files:
[PlatformIoHomie.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/907581/PlatformIoHomie.txt)

[SloeberHomie.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/907582/SloeberHomie.txt)

and this is what's on the serial monitor:
Exception (28):
epc1=0x4021316d epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000226 depc=0x00000000

ctx: cont 
sp: 3fff1390 end: 3fff15c0 offset: 01a0

>>>stack>>>
3fff1530:  3ffef3c0 3ffe86b2 00000003 3ffe86b2  
3fff1540:  3ffef3c0 00000000 00000000 4020b125  
3fff1550:  3fff2d0c 00000000 00000000 4021b508  
3fff1560:  40206fa8 00000000 4021ad5c 40206f14  
3fff1570:  40206fa8 3fff1590 3ffef600 402148bb  
3fff1580:  3fffdad0 00000000 3ffef600 40207205  
3fff1590:  402070dc feefeffe 4021ad84 4021ad70  
3fff15a0:  feefeffe feefeffe 3fff058c 40219e14  
3fff15b0:  feefeffe feefeffe 3fff05a0 40100714  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3ffe9127
~ld

Please let me know if you need more info.

**Comment by jantje** [comment]
Scanning the differences I found that sloeber only compiles 1 assembly file and platformio does 2 
cores\esp8266\cont.S (both)
esp8266\setjmp.S (platfrmio only)

**Comment by DavidR1953** [comment]
Thanks for looking. The comment in setjmp.S is "Required by PlatformIO unit testing feature" which I'm not using, so I'm guessing that's not the problem.
I do not know how to proceed. Should I close this?

**Comment by jantje** [comment]
I'll check whether I see other differences

**Comment by jantje** [comment]
I have seen that the linking happens with another executable.

**Comment by DavidR1953** [comment]
Could you be more specific 😀

I'm afraid I had to give up on Sloeber/Homie.
I also tried some of the other ESP8266 frameworks - Sonoff/Tasmota,
ESPEasy, all of which work in PlatformIO, but not in Sloeber.

I'm sure it's down to my incompetence, but I cannot seem to progress.

**Comment by jantje** [comment]
Snoff/tasmota seems to have a problem with the Arduino IDE varsion provided with sloeber https://github.com/Sloeber/arduino-eclipse-plugin/issues/708#issuecomment-293719342

**Comment by jantje** [comment]
@DavidR1953
Did you see the comments on the homie issue?

**Comment by DavidR1953** [comment]
@jantje 
Yes I had a look. Where do you think the problem is?

**Comment by jantje** [comment]
> sounds like config is not instantiated

**Comment by jantje** [comment]
Can this issue be closed?

**Comment by DavidR1953** [comment]
I haven't used Sloeber for over a year, but Homie is on GitHub, so you can
give it a try.

Kind regards,

David Read.

**Comment by jantje** [comment]
I used it and worked fine so closing
