### ISSUE TITLE
ARDUINO defined as 10609

### ISSUE THREAD

**Issue by DavidR1953** [Sloeber/arduino-eclipse-plugin#708]
Sloeber V4 defines ARDUINO as 10609. This means that code which checks for a later version of the Arduino IDE fails to build. (Specifically Sonoff/Tasmota - https://github.com/arendst/Sonoff-Tasmota)

**Comment by jantje** [comment]
What is the latest number in Arduino ide right now?

**Comment by DavidR1953** [comment]
I don't actually use the Arduino IDE. The latest version is 1.8.2 according
to their release notes, but Google didn't help to find what the define was.
I think gcc's -dM gives a list of macros. I'll install the IDE and try it,
but it will have to be tomorrow.

**Comment by jantje** [comment]
Do you have a update?

**Comment by DavidR1953** [comment]
Looks like it's 10802.
Not sure if setting it to that is a long term solution, but it's your
call 🙂

Have you got any further with Homie?
Have you tried any other ESP8266 frameworks and got them working?

I can get several of the single example sketches to run, e.g. ArdunoOTA,
WebServer etc. but no more.

Kind regards,

David Read.

**Comment by jantje** [comment]
Homie is not on my todo list.
