### ISSUE TITLE
No way to clear the serial-monitor buffer

### ISSUE THREAD

**Issue by jrobert-gh** [Sloeber/arduino-eclipse-plugin#716]
When the serial monitor has a large backlog of text, it can take minutes for the buffer to empty, compiling and uploading are blocked.
A button to clear the serial monitor buffer would be very welcome in this situation.

JRobert
(patron)

**Comment by jantje** [comment]
I've been there as well. So I know what you are talking about :-)
I'll see whether there is this kind of "flush" functionality

**Comment by jrobert-gh** [comment]
Great - thanks for looking into it.



JRobert





On Fri, Apr 14, 2017, at 03:48 PM, jantje wrote:

> I've been there as well. So I know what you are talking about :-)

>  I'll see whether there is this kind of "flush" functionality



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/Sloeber/arduino-eclipse-plugin/issues/716#issuecomment-294223142

**Comment by jantje** [comment]
When you disconnect now the input stream stopping instantly
