### ISSUE TITLE
Upload Console font is not configurable.

### ISSUE THREAD

**Issue by alex-vas** [Sloeber/arduino-eclipse-plugin#717]
The Upload Console view font is seemingly not using the user preference set at "preferences>colors and fonts>console font" like other console views like C++, Java, SVN, Maven, etc.

<img width="780" alt="screen shot 2017-04-15 at 8 52 25 am" src="https://cloud.githubusercontent.com/assets/6243743/25058052/0d15cebe-21b9-11e7-8b18-55150cd25dc8.png">

Would be nice if the Upload Console view would respect one of the existing font settings like "Debug>Console font" or have its own one.

Cheers

**Comment by jantje** [comment]
I would have expected it to follow the C/C++ build console font but apparently it is not.
Any urgent reason to need this?

**Comment by alex-vas** [comment]
No urgency, it's just I like my consoles to be in a small fonts, so it can fit more, and this one stands out now. Thanks!

**Comment by jantje** [comment]
Can you give this a test?

**Comment by alex-vas** [comment]
Looks good. Thank you!

Three smaller observations:

1. Spelling of the Configuration item should start with capital "U" to be consistent with other settings.
2. The value for the font should inherit from "Terminal Console Font" like other console-like views do.
3. The view should update once the setting is "applied". At the moment setting only effects new created views.

<img width="924" alt="screen shot 2018-05-17 at 09 33 52" src="https://user-images.githubusercontent.com/6243743/40149424-dc16fe14-59b6-11e8-8755-d980185967b6.png">

**Comment by jantje** [comment]
I'll do 1 and 2 but I have no clue how to do 3.
The same issue exists for the serial monitor

**Comment by jantje** [comment]
As to 1. made all first characters capital
As to 2 Apparently the default font should be "text font"
As to 3... you can have a listener and the listener can change the font but..that would not work with the colours as they are decided on based on the input to the text field.
So the font could change on apply but the colours not. 
This is why I prefer to change nothing on apply
The change should be available tomorrow on the update site.

**Comment by alex-vas** [comment]
> This is why I prefer to change nothing on apply
Fair enough. 
Looks good!
Thank you.

**Comment by jantje** [comment]
closing as it is fixed in the nightly
