### ISSUE TITLE
Project build if called function from both time.h and Time.h

### ISSUE THREAD

**Issue by dpeddi** [Sloeber/arduino-eclipse-plugin#730]
If you use function exopsed  by Time library and function exposed by time.h you may get into trouble.

Under windows you get Time.o and since windows is case insensitive you wont get time.o build. Probably on linux all would work...

Arduino ide seems to differentiate the obj name of core and library so doesn't have this issue.

Other ide have same issue like sloeber (platformio).. I've opened an issue to Time developer but simply answered... On Arduino it works...

**Comment by jantje** [comment]
Can you provide the console output so I can understand better?

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by dpeddi** [comment]
Actually I can't reproduce it

**Comment by jantje** [comment]
:-)
