### ISSUE TITLE
Problem with generated utf-8 .ino file

### ISSUE THREAD

**Issue by nicoverduin** [Sloeber/arduino-eclipse-plugin#750]
Not shure this has been reported before but I noticed the following issue:
**Situation**
I use Sloeber versie 4.0. All my code is generated using Software Ideas Modeler 10.68. This means the code for  a .ino file and c++ classes as well. ****
**Problem**
If I generate the code in UTF-8 format including a sketch file of type .cpp there is no problem. All are completely compiled by both Sloeber and the Arduino IDE.
If I generate the sketch as .ino file UTF-8 format I get an error from the compiler stating that my includes are missing the last double-quotes. If I rename this sketch file back to .cpp all compiles fine.
If I generate the sketch the sketch in ascii format as .ino all compiles well. 

Based on the above the problem seems to arise from where Sloeber copies the .ino into a .ino.cpp file?
I did check the generated files and all have the 3 byte UTF-8 signature at the beginning. If I blank out these 3 bytes (using a hex editor) as spaces the problem is gone. 

Regards
Nico

**Comment by jantje** [comment]
It  is quite possible that the parsing doesn't work properly when using "other file formats"
Mine is set to CP1252.
I'm actually surprised you want to use ino format if you have cpp at your disposal.
To investigate look at the .ino.cpp file. SOmething must be "incorrect there"

**Comment by nicoverduin** [comment]
The only reason still spending effort for .ino is for those morons that persistently stick to the arduino ide..... it seems the .ino.cpp is missing all the last double quotes of the includes. But as i am the only one having this issue (why would you want to generate all the code after all :) ) i'll close this one as the workaround is in any case plain ascii

**Comment by jantje** [comment]
txs. It is probably more work to setup a test environment for me than to fix the problem.
The problem is here (and 3 lines below).
https://github.com/Sloeber/arduino-eclipse-plugin/blob/master/io.sloeber.core/src/io/sloeber/core/tools/PdePreprocessor.java#L185.
As you have everything at your disposal it should be easy to set a breakpoint and have a look.

**Comment by nicoverduin** [comment]
I have setup the environment in the past. Of course that is no longer existing.... Is there a setup procedure for Windows?

**Comment by jantje** [comment]
Short version: install eclipse java add cdt and gnuarm and import the project from github

**Comment by jantje** [comment]
och you also need to add nebula

**Comment by nicoverduin** [comment]
It seems a bit more complicated than jus removing the first 3 bytes. Ther could be specia characters inside the file as well as the user of SIM can type anything in. Exporting to ascii solves that problem. I will leave it as is.

**Comment by jantje** [comment]
ok. 
Thinking about it I think the problem is that a external tool is saving a file in a format different than eclipse is told to save in.
So It might work with utf-8 if you set the text file encoding under windows->preferences->general->workspace to utf-8.

**Comment by nicoverduin** [comment]
Unfortunately makes no difference. 

 

Van: jantje [mailto:notifications@github.com] 
Verzonden: dinsdag 23 mei 2017 22:36
Aan: Sloeber/arduino-eclipse-plugin <arduino-eclipse-plugin@noreply.github.com>
CC: Nico Verduin <nico.verduin@ziggo.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Sloeber/arduino-eclipse-plugin] Problem with generated utf-8 .ino file (#750)

 

ok.
Thinking about it I think the problem is that a external tool is saving a file in a format different than eclipse is told to save in.
So It might work with utf-8 if you set the text file encoding under windows->preferences->general->workspace to utf-8.

**Comment by jantje** [comment]
then debugging is the only way to find the root cause
