### ISSUE TITLE
Download links for Linux 4.1 are broken

### ISSUE THREAD

**Issue by fish2eggs** [Sloeber/arduino-eclipse-plugin#756]
On http://eclipse.baeyens.it/stable.php?OS=Linux, both the "Download 64 bits Bundle" and the "Download 32 bits Bundle" buttons result in a 404 error.

**Comment by jantje** [comment]
I noticed this as well.
Should be fixed in a couple of hours.
You can find the downloads here https://github.com/Sloeber/arduino-eclipse-plugin/releases/tag/V4_1

**Comment by jantje** [comment]
is fxed now
