### ISSUE TITLE
Update site should point to https

### ISSUE THREAD

**Issue by DareDevil73** [Sloeber/arduino-eclipse-plugin#761]
Hi, I cannot get updates by  the update site http://eclipse.baeyens.it/update/V4/stable configured inside my IDE.

The response, got from a web browser, is:

> If you ended up here you took a shortcut and failed. Go back to start. Start is here installAdvice.shtml

Could you help me please?

**Comment by jantje** [comment]
Thanks for the allert
I disabled http on the server 
So the update sites should point to https.
I'll reenable http for now

**Comment by DareDevil73** [comment]
Now it works!

**Comment by jantje** [comment]
I'm reopening this to make the update site point to https

**Comment by jantje** [comment]
Main reason is that google requires https for all sites that requests passwords which I do for my gallerij and blog so I will be tagged as "untrustworthy" by google.
So I want to disable http on the site and serve only https and standard eclipse does not seem to be able to redirect (which seems ok to me from a security point of view)

**Comment by jantje** [comment]
I also need to point to the https variant for the "what is new page"

**Comment by DareDevil73** [comment]
Today the GNUARM repository site is not reachable.

Thank you!

**Comment by jantje** [comment]
Strange, all my update sites are gone after upgrading to the last nightly :-(

**Comment by jantje** [comment]
These are the "needed" update sites
jantje
For sloeber
https://eclipse.baeyens.it/update/V4/stable
https://eclipse.baeyens.it/update/V4/nightly

For Eclipse
http://download.eclipse.org/eclipse/updates/4.6
http://download.eclipse.org/releases/neon

For CDT
http://download.eclipse.org/tools/cdt/releases/9.2

For debugging functionality
http://gnuarmeclipse.sourceforge.net/updates
