### ISSUE TITLE
removing V3 from eclipse..

### ISSUE THREAD

**Issue by DrObscure** [Sloeber/arduino-eclipse-plugin#763]
I have moved to the V4 plugin, and I use the internal eclipse uninstall to remove V3.. however, the uninstall still left vestiges of the old V3 in the form of several "it.baeyens.arduino.xxx" files in the tree...
Can we assume that all these can be physically removed, even though the uninstall left them in place??

I'm getting an error from eclipse referencing one as creating a CoreException since the dir tree move..

**Comment by jantje** [comment]
I think starting eclipse with -clean should clean these up

**Comment by DrObscure** [comment]
-clean didn't remove much, so I just deleted them manually...
also, it appears I missed an old V3 project that was likely generating the Eclipse error..  once I upgraded its config the error went away as well...

**Comment by MaxRusse11** [comment]
Is there a means to remove this altogether from eclipse?
