### ISSUE TITLE
Spaces in Path Names Breaks Makefile

### ISSUE THREAD

**Issue by coogle** [Sloeber/arduino-eclipse-plugin#785]
Hello,

Great plugin! I just installed it, but I'll certainly throw you a few bucks if I end up using it (which is pretty likely).

Just a quick issue: Your makefile generation breaks if directories have spaces in them. I'm on Mac OS X with Eclipse Oxygen and your latest plugin. I had all of my Workspaces stored in the \Users\john\Local Workspaces\ directory and when i tried to build a simple Blink I got:

No make target for 'Local'

Renaming the directory to local_workspaces fixed the issue.

**Comment by jantje** [comment]
This is a known issue and relates to make.
https://github.com/Sloeber/arduino-eclipse-plugin/issues/643
