### ISSUE TITLE
How to create MKR1000 project with Sloeber

### ISSUE THREAD

**Issue by michael71** [Sloeber/arduino-eclipse-plugin#797]
I successfully have created a few UNO und ProMini projects with sloeber (and all went fine) - however, I cannot create a MKR1000 project, only the avr boards are shown when I select the platform holder "sloeber...". 

Can I  create MKR1000 sketches with sloeber?

thanks,
Michael.

**Comment by michael71** [comment]
i.e.
"is there a board-manager?"

**Comment by jantje** [comment]
There is
https://www.youtube.com/playlist?list=PLCSjf7QmP3TDPSjT_5UIp0DHXzKdhIQsF

**Comment by jantje** [comment]
Can this be closed?

**Comment by michael71** [comment]
Yes, pleased!


Am 28. August 2017 14:57:24 MESZ schrieb jantje <notifications@github.com>:
>Can this be closed?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Sloeber/arduino-eclipse-plugin/issues/797#issuecomment-325345997

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
