### ISSUE TITLE
Recompile when changing Port project properties

### ISSUE THREAD

**Issue by Lahorde** [Sloeber/arduino-eclipse-plugin#80]
Setup ; Arduino IDE 1.5.2 - Eclipse Juno - Arduino Eclipse Plugin 2.1.0.4 

Issue steps :
- compile your sketch by "clicking" on verify button, be sure build is successfull
  -Open Arduino project properties 
  -modify port in Arduino->Arduino board selection ->Port
  -compile your sketch by "clicking" on verify button

Problem : a whole build is done.

**Comment by jantje** [comment]
Thanks to V4.O this turns out to be easy. Well this was one of the issues I was thinking about when I did the V4 changes :-)
