### ISSUE TITLE
V4 Windows 'Product' doesn't run

### ISSUE THREAD

**Issue by pcarew** [Sloeber/arduino-eclipse-plugin#812]
I downloaded the V4 Product 64KB bundle onto a Windows 10 platform.
I used cygwin to gunzip and then extract the files using tar (FYI this workflow is nuts on a windows platform)
I went to run the sloeber-ide.exe and Windows blocked me saying that I didn't have permission.
I tried this also using admin privileges....same result.

I went back to Cygwin and used chmod +x to add execution mode to file.
This time Windows complained that it was missing companion libraries...

Where to from here?

**Comment by jantje** [comment]
I use 7zip to unzip and untar

**Comment by pcarew** [comment]
Thank you
