### ISSUE TITLE
Cannot create linked resource XXXXXX  because a folder of the same name exists remotely.

### ISSUE THREAD

**Issue by far5893** [Sloeber/arduino-eclipse-plugin#836]
I synchronize my project with CVS eclipse plugin   but something goes wrong (seems like start synchronizing  private library path) now it won't compile neither add needed  library.

I try to reattach library but it give me this error when i try to manually add (automatically not work).

Where is "remotely" ? On cvs server ? On some hidden project configuration file ? on file system?

There is only one in private library path folder with the library.

> !ENTRY io.sloeber.arduino.core 2 0 2017-10-06 16:49:08.426
> !MESSAGE Removed invalid include path/esp8266_WebServices/libraries/SMTPClient
> 
> !ENTRY io.sloeber.arduino.core 2 0 2017-10-06 16:49:08.430
> !MESSAGE Removed invalid include path/esp8266_WebServices/libraries/SMTPClient
> 
> !ENTRY io.sloeber.arduino.core 2 0 2017-10-06 16:49:08.431
> !MESSAGE Removed invalid include path/esp8266_WebServices/libraries/SMTPClient
> 
> !ENTRY io.sloeber.arduino.core 4 0 2017-10-06 16:49:11.109
> !MESSAGE Could not create folderlibraries/SMTPClient
> !STACK 1
> org.eclipse.core.internal.resources.ResourceException: Cannot create linked resource '/esp8266_WebServices/libraries/SMTPClient' because a folder of the same name exists remotely.
> 	at org.eclipse.core.internal.resources.Resource.assertLinkRequirements(Resource.java:175)
> 	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:640)
> 	at io.sloeber.core.tools.Helpers.createNewFolder(Helpers.java:451)
> 	at io.sloeber.core.tools.Helpers.LinkFolderToFolder(Helpers.java:234)
> 	at io.sloeber.core.tools.Helpers.addCodeFolder(Helpers.java:270)
> 	at io.sloeber.core.tools.Libraries.addLibrariesToProject(Libraries.java:174)
> 	at io.sloeber.core.tools.Libraries.addLibrariesToProject(Libraries.java:165)
> 	at io.sloeber.core.tools.Libraries.addLibrariesToProject(Libraries.java:228)
> 	at io.sloeber.core.api.Sketch.addLibrariesToProject(Sketch.java:184)
> 	at io.sloeber.ui.Import_Libraries_Page.PerformFinish(Import_Libraries_Page.java:139)
> 	at io.sloeber.ui.ImportLibraries.performFinish(ImportLibraries.java:169)
> 	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:778)
> 	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:417)
> 	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
> 	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
> 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
> 	at org.eclipse.jface.window.Window.open(Window.java:794)
> 	at io.sloeber.ui.actions.AddLibraryAction.execute(AddLibraryAction.java:48)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
> !SUBENTRY 1 org.eclipse.team.cvs.core 4 4 2017-10-06 16:49:11.109
> !MESSAGE Cannot create linked resource '/esp8266_WebServices/libraries/SMTPClient' because a folder of the same name exists remotely.

**Comment by jantje** [comment]
I think you have made a mistake when checking the code in into cvs.
I don't know cvs so I can't help you out for that.
What I can tell you is that you should not check in the libraries folder nor the core folder.
In Sloeber for each file you can see the properties and in resource you can see where the actual file is.
As I can't help you out further I'm closing this ticket.
