### ISSUE TITLE
Error when passing ENUM as a function parameter.

### ISSUE THREAD

**Issue by helltp** [Sloeber/arduino-eclipse-plugin#843]
In my main ino file i have got an enumeration llike this:
`enum Color {Red, Green,Blue}`
And a function that has a Color type parameter:
`void setColor(Color newColor){...}`

When I try to build it throws an error:

> ..\\.ino.cpp:17:19: error: 'Color' was not declared in this scope

I checked the ino file, although it says that it is generated and it should not be modified, if I change the function prototype from void `setColor(Color newColor);` to void `setColor(int newColor);` it works.

Edit:
Of course as soon as it regenerates the file it overwrites the workaround.

**Comment by jantje** [comment]
put your 
`enum Color {Red, Green,Blue}`
in a header file

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by helltp** [comment]
Thank you for the help and the answer. 

As a senior softwer engineer student I'm considering to help you in my spare time.
