### ISSUE TITLE
Invalid Arguments

### ISSUE THREAD

**Issue by Nonth8031** [Sloeber/arduino-eclipse-plugin#858]
Hello:

I fixed my previous problem #855 but now Slober doesn't recognize the arguments, I don't know if I must download any software or not. I have this error before but I thought that the other (#855) should be more important.
In adition to that, when I try to upload the program to my Arduino Mega 2560, It doesn't work. I have configured correctly all settings, at least I think that.
![invalid arguments](https://user-images.githubusercontent.com/33115890/32316980-8dbda66c-bfb2-11e7-8885-07cfabf19178.JPG)

Thank you for your time 😅

**Comment by jantje** [comment]
Please read the faq http://eclipse.baeyens.it/faq.shtml#/troubleshooting
