### ISSUE TITLE
eclipse crashes while uploading the code to arduino

### ISSUE THREAD

**Issue by manishthumala12** [Sloeber/arduino-eclipse-plugin#859]

**Comment by manishthumala12** [comment]
I am using arduino mega when eclipse is trying to acesses com ports on the system eclipse crashes down..... Please help me with this issue

**Comment by wimjongman** [comment]
Go to your workspace directory and attach the metadata/.log to this issue. Add your screenshots and other stuff that will help to resolve the problem.  Also consider contributing to this project https://www.patreon.com/bePatron?c=177453

**Comment by jantje** [comment]
Closinbg due to no input
