### ISSUE TITLE
I am working on a unit test of arduino code using sloeber. I am not sure what I am doing wrong.

### ISSUE THREAD

**Issue by Danial-Zafar** [Sloeber/arduino-eclipse-plugin#867]
![errors](https://user-images.githubusercontent.com/16437575/33016768-96281b62-ce11-11e7-8ada-69bfd0560ed0.png)
![gcc](https://user-images.githubusercontent.com/16437575/33016769-965e9a34-ce11-11e7-9bf6-fc285a8dc761.png)

**Comment by jantje** [comment]
>I am not sure what I am doing wrong.

So am I

**Comment by Danial-Zafar** [comment]
so kindly tell me why I'm facing these errors I have done everything that is mentioned in that video https://www.youtube.com/watch?v=d-Vt21BIHl0&t=312s 
why 'm facing these errors
it gives me an error for ...\Arduino eclipse IDE\sloeber\arduinoPlugin\tools\make\make": Launching failed
there is no \tools\make\make,  in my directory

**Comment by wimjongman** [comment]
Have you read the FAQ? If you do not want to read it then you can support the project on Patreon which enables you to ask questions without reading the documentation ;)

(Hint 1: no spaces in the pathname)

[1] http://eclipse.baeyens.it/faq.shtml
[2] https://www.patreon.com/jantje

**Comment by Danial-Zafar** [comment]
(Hint 1: no spaces in the pathname) I remove the space but still facing two error :( 

make: *** [sloeber.ino.cpp.o] Error 1
recipe for target 'sloeber.ino.cpp.o' failed	subdir.mk

**Comment by ichigo92** [comment]
I am also facing similar issue with `make`, i have added details on issue #867.

**Comment by wimjongman** [comment]
@Danial-Zafar what version are you using. It looks like a very old version of sloeber. Please upgrade. 

![image](https://user-images.githubusercontent.com/180969/33131683-a698082c-cf97-11e7-91f3-4df7b9fb2e6f.png)

**Comment by wimjongman** [comment]
Closed. See #870

**Comment by Danial-Zafar** [comment]
I'm using 4.2 now before that I was using 4.0 and 4.1
