### ISSUE TITLE
After upgrading to V4.2 the product is still V4.0 

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#868]
![afbeelding](https://user-images.githubusercontent.com/1175841/33046639-2318b33e-ce52-11e7-8c2c-4b658792cd55.png)
Which means #866 is not included.

**Comment by wimjongman** [comment]
I don't understand this issue. What exactly is the problem?

**Comment by wimjongman** [comment]
I see that 4.2 is installed in the 4.0 product.

**Comment by jantje** [comment]
I upgraded my working eclipse and I wanted to check whether everything was upgraded and I saw that the product is still on 4.0 and that is not what I expected.

**Comment by wimjongman** [comment]
It is expected.

See this fresh install:

![image](https://user-images.githubusercontent.com/180969/33080697-ff03aa08-ced8-11e7-91f3-23f63e5d6903.png)

all is fine:

![image](https://user-images.githubusercontent.com/180969/33080854-5953bc3c-ced9-11e7-9dc4-a76000a42e78.png)

**Comment by wimjongman** [comment]
There is a way to upgrade the ini file of an existing product but it is not easy. Also a fresh install gets the latest Arduino stuff.

So reinstall the product for a shiny result  
![image](https://user-images.githubusercontent.com/180969/33081122-c265f7e4-ced9-11e7-97ab-82a8ad1bded0.png)

**Comment by jantje** [comment]
ok. Thanks
