### ISSUE TITLE
sloeber(buildall error)

### ISSUE THREAD

**Issue by toobayounas** [Sloeber/arduino-eclipse-plugin#870]
--> windows8.1, sloeber **buildall error**

![image](https://user-images.githubusercontent.com/31401294/33068893-83a0fb4e-ced4-11e7-98f2-e4ffd00781c1.png)
 I am trying to debug arduino on sloeber version 4.1, and i'm facing error shown in png,

**Comment by wimjongman** [comment]
Are you posting the same issue under two different github users? #869

**Comment by Danial-Zafar** [comment]
no

**Comment by wimjongman** [comment]
Or should I call you @ichigo92?

**Comment by wimjongman** [comment]
@Danial-Zafar @ichigo92 and @toobayounas, why are you posting the same screenshots under three different users?

**Comment by ichigo92** [comment]
@wimjongman i don't know what makes you think the other two are me, just to clarify i am not them, i am facing a similar issue as @toobayounas, i posted the details to the error i am getting on  issue #853.

**Comment by Danial-Zafar** [comment]
@wimjongman I have no I intention to irritate you. It is just that I and @toobayounas has an assignment related to ardunio unit testing. We are students and we are trying to come up with a solution.
@toobayounas she is my batch mate so she has the similar task to told her about the sloeber. I, @toobayounas  and @ichigo92 are three different persons. 
It will be very kind of you if you please guide us to the solution.

**Comment by Danial-Zafar** [comment]
If you are guessing that we are the same persons by the same file names of our projects, it is due to we were following the @jantje youtube debugging and unit testing tutorials.

**Comment by wimjongman** [comment]
Alright. It is just that you are posting the same information in the same way about exactly the same problem. 

If you want our help, please do not open different issues about the same problem or crosspost to issues that are already closed. 

From this point on, @Danial-Zafar @ichigo92 and @toobayounas, we will be using this issue to see if we can help you. OK?

**Comment by ichigo92** [comment]
@wimjongman alright, i am using v4.2

**Comment by Danial-Zafar** [comment]
I'm using 4.2 now before that I was using 4.0 and 4.1

**Comment by Danial-Zafar** [comment]
@wimjongman fine.

**Comment by wimjongman** [comment]
Okay so what are you trying to do? It looks like you follow an advanced video. Is it your intention to follow an advanced video or do you just want to get started?

**Comment by Danial-Zafar** [comment]
Yes, my intention is to follow that, as I want to unit test Arduino code...

**Comment by jantje** [comment]
The video is outdated. In 4.2 it is lots easier.
But as @wimjongman  (and I already told you) Do not use spaces in the path. Read the faq and try simple things first (F.I. install zero package and compile)
In a new 4.2 install you should have jantje hardware you can install and use to debug/unit test.
And issues on the jantje hardware part should be posted on the hardware repository https://github.com/jantje/hardware and not here and for sure not on unrelated patron posts.

**Comment by wimjongman** [comment]
![image](https://user-images.githubusercontent.com/180969/33139688-4fa62d0c-cfae-11e7-9db4-26c103b873cb.png)

**Comment by Danial-Zafar** [comment]
@jantje there is no space in path now...

**Comment by wimjongman** [comment]
Also not in the workspace path?

**Comment by uzi18** [comment]
Anywhere

22.11.2017 6:51 PM "Wim Jongman" <notifications@github.com> napisał(a):

**Comment by Danial-Zafar** [comment]
yes, there is no space in workspace path as well...

**Comment by jantje** [comment]
Please provide from one and the system workspace and eclipse installation following information in the order as given (Even better is to record a video doing these actions),
Delete the release and local debug folder in the project
Screenshot of the platform and boards (like wim's screenshot but where we can see what is installed)
Screenshot of the project properties->arduino->localdebug configuration
Screenshot of the whole workspace (visible project manager,console and main ino file)
Do build of release configuration
Screenshot of the whole workspace (visible project manager,console and main ino file)
Do build of localdebug configuration
Screenshot of the whole workspace (visible project manager,console and main ino file)
Content of the console (so no screenshot but actual text)
