### ISSUE TITLE
When creating a new sketched  based on a example using linking the linked to folder must be added to the include path 

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#872]
When creating a new sketched  based on a example using linking the linked to folder must be added to the include path.
If not header files will not be found in the sloeber.ino.cpp as this file is in the workspace and the header is in the eclipse install.
Workaround: add the folder manually if needed.
Note: This is only needed when linking to the code and the .ino file references header files that are part of the example.

**Comment by wimjongman** [comment]
Contribution guide is here:

https://github.com/Sloeber/arduino-eclipse-plugin/wiki/Contribution-Guide
