### ISSUE TITLE
SVN connector installation issues in Sloeber stable and nightly

### ISSUE THREAD

**Issue by dalbert2** [Sloeber/arduino-eclipse-plugin#888]
Tested on Ubuntu 16.04 and Windows 8.1 x64

1) Install Subversive SVN Integration (Help->Add New Software->Work with Eclipse oxygen repository->filter text svn->select Subversive SVN Team Provide->Finish.  When installation finishes, SVN shows up under Preferences->Team (good).
2) Install the connector: Windows->Preferences->Team->SVN->SVN Connector Tab->Get Connectors button and choose SVN Kit (or any of the others, none work) -> Press Apply
3) A dialog or two flash on the screen very quickly and disappear, the connector does not get installed.

I have tried with both Subversive Subversion installed and for windows also with TortoiseSVN.

I did this quite a few times and after many attempts, it finally worked, but I have no idea what made it work.  The out-of-the-box install always fails and does so many times.

**Comment by wimjongman** [comment]
Hi @dalbert2 Thanks for using Sloeber. I have tried this as well on my Sloeber and indeed, the installation is a bit flaky on windows too. However, this is not our software, this is a third party tool that you install into Eclipse and we do not support it.

I'm glad you made it work. If you want you can report the problem at the eclipse subversion guys. Closing as not a sloeber problem.
