### ISSUE TITLE
No carriage return in the serial monitor

### ISSUE THREAD

**Issue by netbomo** [Sloeber/arduino-eclipse-plugin#893]
Hello,
I've just install your plugin on Eclipse Neon on a debian stretch laptop.
I'm using a simple Serial.println("foo"); and new line have an effect but not the carriage return.
I mean, on GTKterm each line is correctly set on the left but not on your serial monitor (shell console).

There is a option somewhere to select the right end line sequence?
I've taken a look in your FAQ but I've found no things.

Thanks you,
gilou

**Comment by wimjongman** [comment]
![image](https://user-images.githubusercontent.com/180969/34408355-9c6141c8-ebc3-11e7-912f-664edb8e3f5d.png)

**Comment by netbomo** [comment]
Hello,
Thanks you for your reply.
My console don't look as your, I've not the control bar with lists and buttons...
![console-error](https://user-images.githubusercontent.com/7942324/34408636-7cadbabc-ebc5-11e7-94a2-09d45fb480c4.png)

**Comment by wimjongman** [comment]
That is not our software. Please download the Sloeber IDE here [1].

[1] http://eclipse.baeyens.it/stable.php?OS=Linux

**Comment by netbomo** [comment]
Hum,
Now I understand. I've install the eclipse plugin, not download the complete IDE.

Thanks.
gilou

**Comment by wimjongman** [comment]
You did not install the Sloeber plugin but something else.
