### ISSUE TITLE
Editing Thrid party  index  url's  give  error   ( Malformed url  no protocol:  )

### ISSUE THREAD

**Issue by miky2k** [Sloeber/arduino-eclipse-plugin#906]
After delete of a line and leave empty  in  Thrid party  index  url's   it give the error Malformed url  no protocol: .
I try to restore to default or empty all but error persist.

eclipse 

Eclipse Platform
Version: Oxygen.2 (4.7.2)
Build id: M20171130-0510
OS: Linux, v.4.13.0-26-lowlatency, x86_64 / gtk 3.18.9

And last slober

**Comment by jantje** [comment]
I do not get this issue when restoring to default.
Malformed url no protocol means there is no http: in front of a url
Please provide more details like your list of url's
sloeber version

**Comment by miky2k** [comment]
Sorry but seems a race condition when changing something(i remove and re-add esp8266 json to force 2.4 version download) and give apply,

pheraps network error or slow net appling json, 

did not see any activity indicator during json downloading  
but now i see esp8266 2.4 so it load updated json and did not give me any error.

I cannot reproduce.

**Comment by jantje** [comment]
thanks for the feedback
