### ISSUE TITLE
Welcome screen/window has misspellings

### ISSUE THREAD

**Issue by sk8nfool** [Sloeber/arduino-eclipse-plugin#908]
Under "Good to Know" second bullet "... uput ..." probably should be "... output ..."
Same bullet "... tab in the ..." probably should be "... tab at the ..."
Same for the 4th bullet
in the 6th bullet "... feedback of ...." probably should be "... feedback for ..."

**Comment by jantje** [comment]
Thanks
Should be fixed tomorrow
