### ISSUE TITLE
platform.txt support is broken for Arduino 1.8.5?

### ISSUE THREAD

**Issue by easyvolts** [Sloeber/arduino-eclipse-plugin#914]
Windows 4.2 Latest Stable build (run on Win10 x64) was not able to build a project for Arduino Zero board (cortex-m0). It looks like the arduino plugin was not able to resolve variables "runtime.tools.arm-none-eabi-gcc.path", "runtime.tools.CMSIS-4.5.0.path" and "runtime.tools.CMSIS-Atmel-1.1.0.path" in platform.txt file. But at the same time ArduinoIDE 1.8.5 was able to build the project. After I defined these paths explicitly in the platform.txt file the project was built successfully.

**Comment by jantje** [comment]
I assume you referenced the arduino ide maintaned packages which is not supported.

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
