### ISSUE TITLE
Failed to run the Upload recipe 

### ISSUE THREAD

**Issue by JBerg60** [Sloeber/arduino-eclipse-plugin#915]
I am using 4.2 on a Mac, added some boards from `http://dan.drown.org/stm32duino/package_STM32duino_index.json`

Then building the blink sketch for a Maple Mini gives `Failed to run the Upload recipe `

Console shows
`Launching/Applications/sloeber.app/Contents/Eclipse//arduinoPlugin/packages/stm32duino/tools/stm32tools/2018.2.11/win/maple_upload`

Obviousy the win folder does not exists on my Mac, the maple_upload is in the macosx folder

How to fix this?

edit: renaming the macosx folder to win moved me to the next error `Failed to open serial device` 
`dfu-util: No DFU capable USB device available` 

in terminal the serial device is present, and this device is also selected with the project

**Comment by jantje** [comment]
Are you sure the package supports mac?

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by jantje** [comment]
closing due to no input
