### ISSUE TITLE
mvn fast build

### ISSUE THREAD

**Issue by uzi18** [Sloeber/arduino-eclipse-plugin#923]
Is it possible to build sloeber without downloading/fetching everything from internet? 
And also without creating archive at the end? 

I use symlink on arduinoPlugin dir to not download all every run. 
I need to have fast build and launch to fix some issues. 

@jentje please help with this :)

**Comment by jantje** [comment]
install eclipse and debug? https://youtu.be/ZkJNrSjKSW0

**Comment by uzi18** [comment]
Thank You Roberto. 

I'm able to build sloeber with maven and trying to understand how it work. 

@jentje how to debug plugin,  i have use System.out.println() to get info to terminal,  maybe there is better way? 
Did not try to build eclipse plugin in another eclipse...  is it a way?

I'm investigating how sloeber search libraries, because want to add project private libraries (in lib or libraries dir). 
After added it encounter strange behaviour, sloeber didn't find libs in hardware dir.

**Comment by uzi18** [comment]
Need to take a look in details on this Youtube clip from @jantje.

**Comment by jantje** [comment]
@uzi18 I do all the Sloeber development, debugging and testing in eclipse.
The video shows how to install eclipse to develop Sloeber. One you have done that you can set breakpoints and step through the code for a better understanding.

**Comment by uzi18** [comment]
If it is possible to do breakpoints it will realy help a lot. Thanks.

**Comment by jantje** [comment]
off course it is. eclipse is a full featured development environment.

**Comment by wimjongman** [comment]
You can use -P SDK in maven to build the SDK

**Comment by jantje** [comment]
@wimjongman indeed great work of yours. Sorry I forgot about that. I should test this and make a new video :-)

**Comment by uzi18** [comment]
Thanks for info @wimjongman

**Comment by uzi18** [comment]
ok it works for me now, I'm able to debug sloeber now :)

**Comment by jantje** [comment]
Next step is to contribute :-)

**Comment by uzi18** [comment]
I need to find myself in sloeber and try first fix what is not working for me.
Something have fixed but not sure if aproch is ok for @jantje to integrate it into master :)
Now testing ;)

**Comment by jantje** [comment]
Best is to start by creating a issue to describe the something that needs fixing.
