### ISSUE TITLE
Sloeber fails to switch workspaces

### ISSUE THREAD

**Issue by sk8nfool** [Sloeber/arduino-eclipse-plugin#935]
When I select File->Switch Workspace and select a _different_ workspace the current workspace disappears (as expected), a box of some kind flashes and sloeber disappears.
I tried to configure the log4j logger ([using](https://logging.apache.org/log4j/2.x/manual/configuration.html)) see if I could capture the failure but only succeeded in making sloeber stop dieing. I tried the following

> export LOG4J_DEBUG

which the [above site](https://logging.apache.org/log4j/2.x/manual/configuration.html) said is supposed to turn on a builtin console logger but that didn't work.

BTW - Sloeber always says

> log4j:WARN No appenders could be found for logger (javax.jmdns.impl.JmDNSImpl).
> log4j:WARN Please initialize the log4j system properly.

Which someone said can be ignored but ...

**Comment by jantje** [comment]
I tried it here. Works fine
Here = windows 10 nightly sloeber product
What is here with you?

**Comment by jantje** [comment]
As to the warning...
If you know how to get rid of it ... please inform me :-)

**Comment by sk8nfool** [comment]
I figured out how to configure log4j. First create a file with the following contents

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
  <appender name="console" class="org.apache.log4j.ConsoleAppender"> 
    <param name="Target" value="System.out"/> 
    <layout class="org.apache.log4j.PatternLayout"> 
      <param name="ConversionPattern" value="%-5p %c{1} - %m%n"/> 
    </layout> 
  </appender> 

  <root> 
    <priority value ="debug" /> 
    <appender-ref ref="console" /> 
  </root>

</log4j:configuration>
```
This file can be named as you desire and placed in a folder of you choosing. I used /home/braun/log4j.xml.

Add the following to <wherever>/sloeber-ide.ini (I used /home/braun/.local/share/sloeber/V4.2_linux64.2017-11-20_02-16-52/sloeber-ide.ini)

```
-Dlog4j.debug
-Dlog4j.configuration=file:///home/braun/log4j.xml
```
I placed these with the other -D flags.

This did a few things

1. got rid of the warning
2. caused a bunch of debug/logging output
3. fixed the problem - switches workspaces just fine now

So - the reason you couldn't get it to fail is either because you're using Win 10 and/or have some kind of logging enabled for your development. I just run whatever was installed with V4.2_linux64.2017-11-20_02-16-52.tar.gz (with manual updates installed a few days ago).

**Comment by sk8nfool** [comment]
hmm - I've been running sloeber-ide from a terminal. If I use a shortcut in the launcher it dies. I attached an strace to the process just before switching workspaces and got
```
strace: Process 5395 attached
futex(0x7fce2473c9d0, FUTEX_WAIT, 5397, NULL <unfinished ...>
+++ exited with 24 +++
```

**Comment by sk8nfool** [comment]
sorry - Here for me is Ubuntu 16.04.4 LTS with latest updates

**Comment by jantje** [comment]
I can reproduce the issue on ubuntu.
It seems like java crashes, a error log file is created but it didn't make me wiser.

**Comment by wimjongman** [comment]
Do you think that the logging issues is preventing the workspace switch? I'm happy to add the log4j configuration to Sloeber.

**Comment by jantje** [comment]
@wimjongman That would be cool :-). It annoyed me from time to time.
My gut-feel (no argumentation) is that the crash is caused by jdms which behaves "differently" in ubuntu

**Comment by sk8nfool** [comment]
Just to throw a wrinkle into the mix. The switch works when I configured
logging.

**Comment by jantje** [comment]
@wimjongman As to the pull request Iwould say this has been fixed but when I start a debug session I get
```
log4j:WARN No appenders could be found for logger (com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions).
log4j:WARN Please initialize the log4j system properly.
```
Is there something I need to configure or is it not yet fully fixed?

**Comment by jantje** [comment]
Can this issue be closed?
