### ISSUE TITLE
Sloeber adding extra "/" to project linked resources

### ISSUE THREAD

**Issue by jamesatlasp** [Sloeber/arduino-eclipse-plugin#954]
When trying to compile, I get an error:

```
> 15:04:42 **** Incremental Build of configuration Release for project SBMServerDev ****
/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/tools/make/make all 
Cannot run program "/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/tools/make/make": Unknown reason

Error: Program "/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/tools/make/make" not found in PATH
PATH=[/Applications/sloeber.app/Contents/Eclipse//arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/::/usr/bin:/bin:/usr/sbin:/sbin]
```

If you take a look at the screenshots, I think this is because ECLIPSE_HOME has an extra "/" trailing the path. I cannot figure out how to get rid of it. 

Running on OS X High Sierra, installed the default Sloeber product package. 

![screen shot 2018-04-06 at 3 14 18 pm](https://user-images.githubusercontent.com/38144416/38444766-db656286-39ad-11e8-9fc2-857dafaa51bf.png)
![screen shot 2018-04-06 at 3 14 26 pm](https://user-images.githubusercontent.com/38144416/38444767-db7419fc-39ad-11e8-8098-a096e4d11459.png)

**Comment by jantje** [comment]
> `/Applications/sloeber.app/Contents/Eclipse/arduinoPlugin/tools/make/make`

I thought on mac this should say make without fqn.
Sloeber does not provide a make for mac so it is normal make is not found there.
The make command is defines as
`"${JANTJE.MAKE_LOCATION}make"`
And  JANTJE.MAKE.LOCATION is only set on windows
https://github.com/Sloeber/arduino-eclipse-plugin/blob/fb0fb2ab3076cf5a21e4f587c2085cf8d3b1a9df/io.sloeber.core/src/io/sloeber/core/tools/Helpers.java#L480
IMHO you have set the env var JANTJE.MAKE.LOCATION 
http://eclipse.baeyens.it/installAdvice.shtml

Anyway the double slashes are not a problem and not an issue

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by jamesatlasp** [comment]
Thanks for your reply. We are testing Sloeber out in a collaborative environment at a university where several students contribute to the same git repo. Some students have macs, some have windows machines. 

Do you have any recommendations for keeping this environment variable out of the repo? We already don't track .project as recommended in your previous tickets.

**Comment by jantje** [comment]
I do not really have experience with team development ond different oses.
Issue #243 is fixed in the nightly which should help.
There is code to detect os change which should cope with this but apparently it is not triggered in your case.
With #243 fixed I would check in all files (except the release folder and sloeber.ino.cpp) and do project properties->arduino->apply and close after each pull request.

**Comment by jantje** [comment]
Please share your experiences for others.
