### ISSUE TITLE
Invalid Arguments

### ISSUE THREAD

**Issue by neil-benn** [Sloeber/arduino-eclipse-plugin#964]
Hello,

  I've got an ino that compiles in the Arduino studio but does not compile in this eclipse plugin.  The eclispe is on the root of C so I don't hit the 40 character issue and the Index unused headers checkbox is clear but I get the following output:

13:59:52 **** Incremental Build of configuration Release for project PickerFirmware ****
"C:\\eclipse\\eclipse\\arduinoPlugin\\tools\\make\\make" all 
'Starting combiner'
"C:\eclipse\eclipse\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-gcc" -Wall -Wextra -Os -Wl,--gc-sections,--relax -mmcu=atmega2560 -o "C:\Users\neilb\Documents\GitHub\PickerFirmware/Release/PickerFirmware.elf"    .\picker-firmware\StringTokenizer.cpp.o    C:/Users/neilb/Documents/GitHub/PickerFirmware/Release/arduino.ar  "-LC:\Users\neilb\Documents\GitHub\PickerFirmware/Release" -lm
C:\Users\neilb\AppData\Local\Temp\ccL8SnoP.ltrans0.ltrans.o: In function `main':
ccL8SnoP.ltrans0.o:(.text.startup+0xe0): undefined reference to `setup'
ccL8SnoP.ltrans0.o:(.text.startup+0xe8): undefined reference to `loop'
collect2.exe: error: ld returned 1 exit status
makefile:80: recipe for target 'PickerFirmware.elf' failed
make: *** [PickerFirmware.elf] Error 1

13:59:53 Build Finished (took 1s.574ms)

  In the eclipse editor I get Invalid arguments reported but from the only thing I can find I get a link to the troubleshooting page but this doesn't seem to give me anything for this.  I'm happy to provide the code if required.

Cheers,

Neil

**Comment by jantje** [comment]
I guess this one can be closed.
If not please reopen.
