### ISSUE TITLE
Arduino Due - Linux - bin Directory not included in tar.gz File

### ISSUE THREAD

**Issue by 420579436** [Sloeber/arduino-eclipse-plugin#966]
I got the error message "sloeber//arduinoPlugin/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: not found" and I realised that the bin directory not exists.
And the directory is missing in the gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz file too.

**Comment by jantje** [comment]
Sloeber is downloading and referencing these files based on json files provided by third parties.
There is nothing we can do if information is missing in download files provided by third parties
