### ISSUE TITLE
Setting up repository

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#970]
I like to setup a local repository for the Arduino plugin as mentioned in the readme.

Managed to get the local directory in : 
![softsites](https://user-images.githubusercontent.com/4587225/39255577-29401074-48ad-11e8-9421-1cfecf58e3f8.JPG)

But when checking the local repo for available software I get : 

![repo](https://user-images.githubusercontent.com/4587225/39255669-5b5fea70-48ad-11e8-884d-db2142ff1822.JPG)

Are there additional steps needed ?

**Comment by wimjongman** [comment]
Hi @hreintke 

> I like to setup a local repository for the Arduino plugin as mentioned in the readme.
Why do you want to do this?

**Comment by hreintke** [comment]
To be able to do test/retest local updates to the plugin without setting it up from scratch every time.
That is how I do it now : 

- Maven build plugin
- Copy `C:\temp\sl\arduino-eclipse-plugin\io.sloeber.product\target\products\io.sloeber.product\win32\win32\x86_64\sloeber` to a working directory.
- Start eclipse

But then I always have to reload the platforms etc.

BTW : What IDE are you using for Plugin Development ?

**Comment by jantje** [comment]
>BTW : What IDE are you using for Plugin Development ?

Eclipse

>But then I always have to reload the platforms etc.

you can copy the arduinoplugin folder or copy over the old install

**Comment by jantje** [comment]
Is this still a issue? Can this be closed?
