### ISSUE TITLE
Unable to debug Step by Step and Insert Breakpoints on ESP8266

### ISSUE THREAD

**Issue by felipemcg** [Sloeber/arduino-eclipse-plugin#971]
Hello to everyone. I'm having trouble when degugging the module, with the example code Blinky. The debugging session is started correctly, but when trying to insert a breakpoint, i get a warning saying: "Breakpoint Installation Failed". Apart from that, I can't debug step by step, the button isnt even enabled.
What im using: 
-Sloeber V4.2 as IDE running on Windows 10 
-Arduino Core V 2.3.0 
-Jantje ESP Hardware debug 1.0
-ESP8266(ESP-01 Black version)

Here is the debugger console output:
`GNU gdb (GDB) 7.11`
`Copyright (C) 2016 Free Software Foundation, Inc.`
`License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`
`This is free software: you are free to change and redistribute it.`
`There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.`
`This GDB was configured as "--host=i686-pc-mingw32 --target=xtensa-lx106-elf".`
`Type "show configuration" for configuration details.`
`For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.`
`Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.`
`For help, type "help".`
`Type "apropos word" to search for commands related to "word".`
`(trace) gdbarch_init()`
`(trace) gdbarch_init()`
`(trace) xtensa_unwind_pc (next_frame = 0x82c1e40)`
`(info ) [xtensa_unwind_pc] pc = 0x4010025b`
`(trace) xtensa_alloc_frame_cache ()`
`(trace) call0_analyze_prologue (start = 0x4010025b, pc = 0x4010025b, ...)`
`(verb ) [call0_analyze_prologue] stopped at instr addr 0x4010025b, succeeded`
`gdbstub_do_break_breakpoint_addr () at D:\sloeber\arduinoPlugin\packages\Jantje\hardware\esp8266\1.0.0\libraries\gdb\gdbstub-entry.S:399`
`399		break 0,0`
`Warning: the current language does not match this frame.`
`(trace) xtensa_skip_prologue (start_pc = 0x40107038)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x4010703d)`
`(trace) xtensa_skip_prologue (start_pc = 0x40107038)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x40107044)`
`(trace) xtensa_skip_prologue (start_pc = 0x40106ff8)`
`(trace) xtensa_skip_prologue (start_pc = 0x40106ff8)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x40106ffd)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x40106ffd)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x40106ffd)`
`(trace) xtensa_breakpoint_from_pc (pc = 0x4010703d)`

**Comment by freeck** [comment]
Are you sure you inserted the IRAM directive in the function header you are debugging?
And that the compiler debug flag -Og is set?

**Comment by felipemcg** [comment]
With IRAM directive are you refering to RAMFUNC? If so, I do call it inside the code: 

`#include "Arduino.h"
#include "gdb.h"
#include "gdbstub.h"

const short int BUILTIN_LED1 = 1; //GPIO1
//The setup function is called once at startup of the sketch
void RAMFUNC setup()
{
#ifdef DEBUG
	uart_div_modify(0, UART_CLK_FREQ / 115200);
	Serial.begin(115200);
	gdbstub_init();
#endif
// Add your initialization code here
	pinMode(BUILTIN_LED, OUTPUT);
}

// The loop function is called in an endless loop
void RAMFUNC loop()
{
	digitalWrite(BUILTIN_LED, HIGH);   // turn the LED on (HIGH is the voltage level)
	delay(1000);              // wait for a second
	digitalWrite(BUILTIN_LED, LOW);    // turn the LED off by making the voltage LOW
	delay(1000);              // wait for a second
}`

With respect to the -og flag, where do I set the flags? Its in Project > C/C++ Build > Settings > Arduino C++ Compiler ?

**Comment by felipemcg** [comment]
I created like 4 projects already and all have the same issue. That include is part of jantjes example, its in the video. I really dont know what else to look for

**Comment by freeck** [comment]
Well, I would like to help you, but the problem is that I use my own version. If I can find some time I will try Jantjes version later this week. But let me start asking some questions:
You stated: "The debugging session is started correctly, but when trying to insert a breakpoint, i get a warning saying: "Breakpoint Installation Failed". "....  What do you mean by that? 
1: when the session starts, does Eclipse stop at location "loop()" ? It should....
2: if not, what is the output at the serial port of your target when you reset your target? you should see a short debug message.....the. The target waits for a command from gdb.....

**Comment by felipemcg** [comment]
Thank you! I apreciate any help, because as you can see, I'm not an expert on this subject. By the way, how did you make your own version? 

Answering your questions: 
The problem with the breakpoint is that when I place a breakpoint in the code, I get the following in the problems tab: 
![debu2](https://user-images.githubusercontent.com/9245211/39544948-a5c164b6-4e1d-11e8-9a02-eb97bc123344.PNG)

1) This screenshot is exactly after hitting the Debug button, as you can see, there isnt a cursor indicating at what part of the code has stopped.
![debug](https://user-images.githubusercontent.com/9245211/39544841-5bb33c32-4e1d-11e8-9461-3e512bad89a6.PNG)

2)After loading the code and hitting reset, this is what I get trough the serial port, basically junk: 
![debug3](https://user-images.githubusercontent.com/9245211/39545012-d2853a40-4e1d-11e8-9932-cf7490ec578b.PNG)

**Comment by felipemcg** [comment]
Sorry for the delay in response. I solved the issue, thanks for the help! 
My mistakes were: 
- When I finished uploading the debugging code, I didnt restart the module to enter intodebugging mode. 
- The code loaded with in the ESP8266 was a blinky. Since I'm using the ESP-01, The uart pin is connected to the led, so my code was interfering with the uart needed for debugging.

**Comment by jantje** [comment]
I guess this can be closed now
