### ISSUE TITLE
How to update built-in libraries?

### ISSUE THREAD

**Issue by innodron** [Sloeber/arduino-eclipse-plugin#979]
I could not find a mechanism to update the built-in libraries referenced at `Eclipse -> Preferences -> Arduino -> Library Manager` (which are stored in `/Applications/EclipseCPP.app/Contents/Eclipse/arduinoPlugin/libraries` in Mac OS)

Example: Blynk github latest release is v5.0.2 while Sloeber offers 0.4.8 as the latest. How can one upgrade this properly using the plugin ?

Sloeber version is 4.2.0.201805190609

**Comment by jantje** [comment]
You need to turn on arduino->preferences->arduino->third party index url's ->update local json files.
At next start the newer versions should be there

**Comment by jantje** [comment]
I guess this can be closed

**Comment by jonnieZG** [comment]
This should not be an option. It should be automatically updated every once in a while. There should be just a button saying "Update Now" for forcing an immediate update.
