### ISSUE TITLE
Eclipse indexer syntax highlighting on std::function, std::shared_ptr and lambda's

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#983]
This is an example of the issue I see : 

![indexer](https://user-images.githubusercontent.com/4587225/40585135-95168454-61ad-11e8-810d-539cfb8f0f54.JPG)

On internet the generic solution for this is to  include __cplusplus = 201103L to the properties.
But that is already in the project defined.

Do you have an idea hoe to solve this ?

**Comment by hreintke** [comment]
Agree that it most probably is a cdt problem.
Hoped you had seen it before and knew a solution for it.

**Comment by jantje** [comment]
I know CDT is constantly working on improving so it is likely to be fixed one day.
Maybe this wil fix it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=519819
Are you on the latest CDT? 9.4.3

**Comment by hreintke** [comment]
yes, I am. 
The filename is `org.eclipse.cdt_9.4.3.201802261533` 
Will need to do more internet searching and/or bug reporting.

Thanks for helping.

**Comment by hreintke** [comment]
Searching for solution/comparison I did a re-index of the project in sloeber.
Now all is working as expected.

Do see some small differences between C++ IDE and sloeber.
f.e. color coding of some functions, the printf is colored in C++ IDE and "plain text" in slober.

Not enough to do further investigation for now.

**Comment by jantje** [comment]
Sloeber is a layer on top of CDT feeding CDT with Arduino information.
Sloeber does have its own implementation for making the makefile but further on everything is plain old CDT
Which means that from a indexer and colouring perspective everything "Should be the same". Practise however is a different story. Install history, order of loading plugin's ... so many things can explain "differences"

>Not enough to do further investigation for now.

:-)))

**Comment by hreintke** [comment]
To be clear.

I did not want to say that I expected you to investigate. 
Just that I will leave it as is :-)
