### ISSUE TITLE
Issue with ‘__has_include()’ Macro

### ISSUE THREAD

**Issue by gfvalvo** [Sloeber/arduino-eclipse-plugin#988]
Hi,

The code below compiles and runs without complaint using the Arduino IDE.

It also compiles and successfully runs using Sloeber. However, it displays a couple anomalies:

1. The entire “#if / #endif” conditional macro block is shown as failed in the editor window (i.e. the entire block is “Greyed Out”).

2. When compiled, it complains “Function ‘test1’ could not be resolved”.

But yet, the compiled code downloads and runs correctly.

This behavior occurred when testing with both Arduino Uno and Teensy 3.2.

Thanks!

```
#include <Arduino.h>

#if  __has_include(<Print.h>)
void test1() {
	Serial.println("Conditional Test #1 - PASSED");
}
#endif

void setup() {
	Serial.begin(115200);
	delay(2000);
	Serial.println("Compiled in Sloeber for Uno");
	test1();
}

void loop() {
}
```

**Comment by jantje** [comment]
`__has_include(` is probably not -yet- supported by CDT.
I know it is confusing but this is a CDT issue and not a Sloeber issue
