### ISSUE TITLE
LocalDebug Invalid Arguments Issue

### ISSUE THREAD

**Issue by human890209** [Sloeber/arduino-eclipse-plugin#994]
HI,
I installed 64bit stable version of Sloeber 4.2. And the Arduino plugin was installed automatically (1.6.21). I created a Blink example sketch and verified it then uploaded it to my Arduino UNO. Everything worked. No invalid arguments issue.
Then I installed the Local Debug plugin which is under Perference\Arduino\Platform and Boards\Jantje\Arduino avr Boards(local debug)\1.0.2
After the setup completed. I follow this Youtube Video [https://www.youtube.com/watch?v=ZN-rLSyhBN8] to local debug a BlinkWithoutDelay example.
And set to [Release] Build Configuration(1.6.21), everything worked.
But when changed the Build Configuration to [localdebug].
Invalid arguments were reported by indexer.
And the debug is terminated.
![error](https://user-images.githubusercontent.com/22681924/41828461-df7c7f00-7867-11e8-8e0c-e644f0399b51.PNG)
Then I added [#include "Arduino.h"].
Some invalid Arguments went away. But still get 2 left. pinMode() and digitalWrite() were not recognized.
![error2](https://user-images.githubusercontent.com/22681924/41828547-75d73d0a-7868-11e8-9fb2-30dc32d80c12.PNG)

It's my first time to use Sloeber, Hope somebody could help me. Thanks.

**Comment by jantje** [comment]
check http://eclipse.baeyens.it/faq.shtml#/troubleshooting
section "Eclipse tells me there are bugs in my code but it compiles ok."

**Comment by human890209** [comment]
I checked troubleshooting, cause I searched similar issues about Invalid Arguments before I post here.
Actually, I can't find the "windows->preferences->C/C++->indexer->Files to index upfront . " in 4.2.
And I did #include "Arduino.h" then some errors go away (value error), but some still remain (function error).
![setting](https://user-images.githubusercontent.com/22681924/41946616-0035542c-79e6-11e8-8056-57caee14e258.PNG)

**Comment by jantje** [comment]
What is the console output?

**Comment by human890209** [comment]
Sorry for my late reply.

![projectsetting](https://user-images.githubusercontent.com/22681924/42130336-df0d10d2-7d14-11e8-80bb-d572fe7bd1d2.PNG)
![projectcompile](https://user-images.githubusercontent.com/22681924/42130349-31c59fc4-7d15-11e8-8c2a-8ab4609c7d9f.PNG)
![debugsetting](https://user-images.githubusercontent.com/22681924/42130351-36bfb974-7d15-11e8-9064-e7b08f5c592f.PNG)
![debugconsole](https://user-images.githubusercontent.com/22681924/42130353-3ee6140e-7d15-11e8-9512-7f516e969c16.PNG)
![inoscript](https://user-images.githubusercontent.com/22681924/42130354-484f0956-7d15-11e8-824c-e1f3b2aab790.PNG)

**Comment by human890209** [comment]
Old Problems
![problemswindow](https://user-images.githubusercontent.com/22681924/42130447-dd2ad86e-7d17-11e8-9e53-c5afdb3770f2.PNG)


And #include "Arduino.h" still 2 function error unresolved

![includearduinoh](https://user-images.githubusercontent.com/22681924/42130448-e30ec4c0-7d17-11e8-9c5b-a778e7668e7a.PNG)
![lessproblems](https://user-images.githubusercontent.com/22681924/42130450-e8592c9a-7d17-11e8-9f29-a8fd697b37de.PNG)

**Comment by jantje** [comment]
As far as I can see the console states the build is fine

**Comment by human890209** [comment]
Why the debug is terminated? How to use the local debug?

**Comment by jantje** [comment]
This is "advanced usage". See this video for more info https://youtu.be/szRrvJPvQz4

**Comment by jantje** [comment]
I guess the video fixed this
