### ISSUE TITLE
Wrong Arduino path defaults on macOS

### ISSUE THREAD

**Issue by Crazor** [Sloeber/arduino-eclipse-plugin#997]
I installed Sloeber on macOS and it did not find my installed libraries and boards. Looking into the preferences, Sloeber had `~/Arduino/libraries` and `~/Arduino/hardware` set by default. IIRC this is correct on Linux, but on macOS, the Arduino IDE puts it's stuff under `~/Documents/Arduino` by default. Just a minor inconvenience, but I suppose also an easy fix.

**Comment by jantje** [comment]
Thanks for the info.
Note: Os dependent stuff is never easy.

**Comment by Crazor** [comment]
The FileManager is a fancy way to find special folders like Documents. I've never seen a system where this default has been changed. Localization is not an issue here, because the file system name is always Documents, with a .localized file inside that tells the GUI to render the name localized. So I guess switching for OS and appending Documents is the way to go for virtually everyone on macOS.

**Comment by jantje** [comment]
@Crazor 
Should I test for IS_OS_MAC  or IS_OS_MAC_OSX ?
```
    public static final boolean IS_OS_MAC = getOSMatchesName("Mac");

    /**
     * <p>
     * Is <code>true</code> if this is Mac.
     * </p>
     * 
     * <p>
     * The field will return <code>false</code> if <code>OS_NAME</code> is <code>null</code>.
     * </p>
     * 
     * @since 2.0
     */
    public static final boolean IS_OS_MAC_OSX = getOSMatchesName("Mac OS X");
```

**Comment by jantje** [comment]
I tried IS_OS_MAC.
This can easily be changed later.

**Comment by jantje** [comment]
Due to no response I'm assuming this is fixed.
